Repository Dolibarr/dolibarr, pull requests merged in 2018-08, with the labels that each got.

#9147 FIX multicompany compatibility !
  htdocs/install/mysql/data/llx_accounting_account_be.sql
  htdocs/install/mysql/data/llx_accounting_account_bf.sql
  htdocs/install/mysql/data/llx_accounting_account_bj.sql
  htdocs/install/mysql/data/llx_accounting_account_cd.sql
  htdocs/install/mysql/data/llx_accounting_account_cf.sql
  htdocs/install/mysql/data/llx_accounting_account_cg.sql
  htdocs/install/mysql/data/llx_accounting_account_ch.sql
  htdocs/install/mysql/data/llx_accounting_account_ci.sql
  htdocs/install/mysql/data/llx_accounting_account_cl.sql
  htdocs/install/mysql/data/llx_accounting_account_cm.sql
  htdocs/install/mysql/data/llx_accounting_account_dk.sql
  htdocs/install/mysql/data/llx_accounting_account_es.sql
  htdocs/install/mysql/data/llx_accounting_account_fr.sql
  htdocs/install/mysql/data/llx_accounting_account_ga.sql
  htdocs/install/mysql/data/llx_accounting_account_gb.sql
  htdocs/install/mysql/data/llx_accounting_account_gq.sql
  htdocs/install/mysql/data/llx_accounting_account_km.sql
  htdocs/install/mysql/data/llx_accounting_account_lu.sql
  htdocs/install/mysql/data/llx_accounting_account_ma.sql
  htdocs/install/mysql/data/llx_accounting_account_ml.sql
  htdocs/install/mysql/data/llx_accounting_account_ne.sql
  htdocs/install/mysql/data/llx_accounting_account_sn.sql
  htdocs/install/mysql/data/llx_accounting_account_td.sql
  htdocs/install/mysql/data/llx_accounting_account_tg.sql
  htdocs/install/mysql/data/llx_accounting_account_tn.sql
Labels: PR to fix or conflict to solve

#9093 FIX : page must always be 0 when we search
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/facture/list.php
  htdocs/fourn/commande/list.php
  htdocs/fourn/facture/list.php
  htdocs/societe/list.php
  htdocs/supplier_proposal/list.php
Labels: Discussion

#9158 FIX : missing hook to edit sql
  htdocs/societe/consumption.php
Labels: PR no new feature into freezed/released branch

#9181 FIX : Wrong position of firstname lastname
  htdocs/core/lib/functions.lib.php
Labels: PR to fix or conflict to solve

#9208 fix connect mode for v8 release
  htdocs/public/payment/newpayment.php
Labels: Discussion

#8975 add hooks on stock replenish
  htdocs/product/stock/replenish.php
Labels: PR to fix or conflict to solve, PR to merge

#8671 FIX : Fetch task will now fetch comments
  htdocs/projet/card.php
  htdocs/projet/class/project.class.php
  htdocs/projet/class/task.class.php
  htdocs/projet/comment.php
  htdocs/projet/contact.php
  htdocs/projet/document.php
  htdocs/projet/element.php
  htdocs/projet/ganttview.php
  htdocs/projet/info.php
  htdocs/projet/note.php
  htdocs/projet/tasks.php
  htdocs/projet/tasks/comment.php
  htdocs/projet/tasks/contact.php
  htdocs/projet/tasks/document.php
  htdocs/projet/tasks/note.php
  htdocs/projet/tasks/task.php
  htdocs/projet/tasks/time.php
Labels: PR to fix or conflict to solve

#8996 clean and update code
  htdocs/comm/mailing/cibles.php
  htdocs/fichinter/index.php
  htdocs/fourn/facture/list.php
  htdocs/fourn/facture/rapport.php
Labels: PR to fix or conflict to solve
