Repository Dolibarr/dolibarr, pull requests merged in 2018-06, with the labels that each got.

#9008 clean and update code
  htdocs/comm/mailing/cibles.php
  htdocs/comm/propal/tpl/linkedobjectblock.tpl.php
  htdocs/commande/tpl/linkedobjectblock.tpl.php
  htdocs/compta/facture/tpl/linkedobjectblock.tpl.php
  htdocs/compta/facture/tpl/linkedobjectblockForRec.tpl.php
  htdocs/contrat/tpl/linkedobjectblock.tpl.php
  htdocs/expedition/tpl/linkedobjectblock.tpl.php
  htdocs/externalsite/admin/externalsite.php
  htdocs/fourn/facture/tpl/linkedobjectblock.tpl.php
Labels: PR to fix or conflict to solve

#8999 NEW Add supplier ref in item reception page
  htdocs/fourn/commande/dispatch.php
Labels: PR to merge

#8931 NEW Add hidden option MAIN_DOCUMENTS_DESCRIPTION_FIRST
  htdocs/core/lib/pdf.lib.php
Labels: PR to merge

#8944 New: Option to see line numbers in modules page
  htdocs/admin/modules.php
Labels: PR to merge

#8884 New : fichinter models (like factureRec)
  htdocs/core/lib/fichinter.lib.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/fichinter/card-rec.php
  htdocs/fichinter/card.php
  htdocs/install/mysql/tables/llx_fichinter_rec.key.sql
  htdocs/install/mysql/tables/llx_fichinter_rec.sql
  htdocs/install/mysql/tables/llx_fichinterdet_rec.sql
Labels: PR to merge

#8818 NEW Add link to inventory code
  htdocs/product/stock/mouvement.php
Labels: PR to merge

#8785 Add dateemploymentEnd on user
  htdocs/install/mysql/tables/llx_user.sql
  htdocs/user/card.php
  htdocs/user/class/user.class.php
Labels: PR to merge

#8789 NEW Add CONTRACT_ALLOW_TO_LINK_FROM_OTHER_COMPANY and CONTRACT_HIDE_UNSELECTABLES by SELECT_HIDE_UNSELECTABLES
  htdocs/core/class/html.formcontract.class.php
  htdocs/core/class/html.formprojet.class.php
Labels: PR to merge

#8738 NEW triggers add commercial and del commercial
  htdocs/societe/class/societe.class.php
Labels: PR to merge

#8796 introduce serial and document for holiday module
  htdocs/admin/holiday.php
  htdocs/core/modules/holiday/index.html
  htdocs/core/modules/holiday/mod_holiday_immaculate.php
  htdocs/core/modules/holiday/mod_holiday_madonna.php
  htdocs/core/modules/holiday/modules_holiday.php
  htdocs/core/modules/modHoliday.class.php
Labels: PR postponed, PR to merge
