Repository Dolibarr/dolibarr, pull requests merged in 2018-09, with the labels that each got.

#9298 NEW hook formConfirm always called if hooked
  htdocs/asset/card.php
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
  htdocs/expedition/card.php
  htdocs/expedition/shipment.php
  htdocs/modulebuilder/template/myobject_card.php
  htdocs/product/inventory/card.php
  htdocs/product/stock/card.php
  htdocs/supplier_proposal/card.php
  htdocs/website/websiteaccount_card.php
Labels: Discussion

#9018 Enable auto update PDF on update note
  htdocs/core/actions_setnotes.inc.php
Labels: PR to fix or conflict to solve, PR to merge

#9414 Standardize and update code
  htdocs/commande/class/commande.class.php
  htdocs/compta/bank/class/account.class.php
  htdocs/compta/bank/class/bankcateg.class.php
  htdocs/compta/bank/class/paymentvarious.class.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/localtax/class/localtax.class.php
  htdocs/compta/paiement/cheque/class/remisecheque.class.php
  htdocs/compta/paiement/class/paiement.class.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/salaries/class/paymentsalary.class.php
  htdocs/compta/sociales/class/chargesociales.class.php
  htdocs/compta/sociales/class/paymentsocialcontribution.class.php
  htdocs/compta/tva/class/tva.class.php
  htdocs/contact/class/contact.class.php
  htdocs/contrat/class/contrat.class.php
  htdocs/core/triggers/interface_20_all_Logevents.class.php
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
  htdocs/core/triggers/interface_50_modAgenda_ActionsAuto.class.php
  htdocs/core/triggers/interface_50_modBlockedlog_ActionsBlockedLog.class.php
  htdocs/core/triggers/interface_50_modLdap_Ldapsynchro.class.php
  htdocs/core/triggers/interface_50_modMailmanspip_Mailmanspipsynchro.class.php
  htdocs/core/triggers/interface_50_modNotification_Notification.class.php
  htdocs/cron/class/cronjob.class.php
  htdocs/don/class/don.class.php
  htdocs/don/class/paymentdonation.class.php
  htdocs/ecm/class/ecmdirectory.class.php
  htdocs/ecm/class/ecmfiles.class.php
  htdocs/expedition/class/expedition.class.php
  htdocs/expensereport/class/paymentexpensereport.class.php
  htdocs/fichinter/class/fichinter.class.php
Labels: PR to fix - Continuous Integration Test failed

#9559 correct trimParameters
  htdocs/compta/sociales/class/cchargesociales.class.php
Labels: Discussion

#9121 Generation of the mandate file from the api
  htdocs/societe/class/api_thirdparties.class.php
Labels: PR to fix or conflict to solve, PR to merge

#9201 FIX exclude element of the select
  htdocs/projet/element.php
Labels: PR to fix or conflict to solve

#9545 Fix link display
  htdocs/stripe/transaction.php
Labels: PR to fix - Continuous Integration Test failed

#9578 FIX #9432 Assign yourself as a commercial when you don't have permission to see all thirds
  htdocs/societe/card.php
Labels: PR to fix or conflict to solve

#9501 FIX : According to french law, if seller is in France and buyer isn't…
  htdocs/core/lib/functions.lib.php
Labels: Discussion

#8729 NEW Advanced permission to ignore price min
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/fiche-rec.php
  htdocs/contrat/card.php
  htdocs/core/modules/modProduct.class.php
  htdocs/langs/fr_FR/admin.lang
Labels: PR to fix or conflict to solve

#9582 Standardize and update code from New branch 21 09 2018
  htdocs/adherents/card.php
  htdocs/adherents/class/adherent.class.php
  htdocs/adherents/subscription.php
  htdocs/core/modules/bank/doc/pdf_sepamandate.modules.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/contract/doc/doc_generic_contract_odt.modules.php
  htdocs/core/modules/contract/doc/pdf_strato.modules.php
  htdocs/core/modules/dons/html_cerfafr.modules.php
  htdocs/core/modules/expedition/doc/doc_generic_shipment_odt.modules.php
  htdocs/core/modules/expedition/doc/pdf_merou.modules.php
  htdocs/core/modules/expedition/doc/pdf_rouget.modules.php
  htdocs/core/modules/expensereport/doc/pdf_standard.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/fichinter/doc/pdf_soleil.modules.php
  htdocs/core/modules/livraison/doc/pdf_typhon.modules.php
  htdocs/core/modules/product/doc/doc_generic_product_odt.modules.php
  htdocs/core/modules/project/task/doc/doc_generic_task_odt.modules.php
  htdocs/core/modules/supplier_proposal/doc/pdf_aurore.modules.php
  htdocs/core/modules/ticket/mod_ticket_universal.php
  htdocs/core/modules/user/doc/doc_generic_user_odt.modules.php
  htdocs/core/modules/usergroup/doc/doc_generic_usergroup_odt.modules.php
  htdocs/core/tpl/card_presend.tpl.php
  htdocs/public/members/new.php
  htdocs/public/payment/paymentok.php
Labels: PR to fix or conflict to solve
