Repository Dolibarr/dolibarr, pull requests merged in 2018-04, with the labels that each got.

#8483 Fix: remove html tags and decode html entities
  htdocs/adherents/class/adherent.class.php
  htdocs/adherents/class/adherent_type.class.php
  htdocs/core/lib/functions.lib.php
  htdocs/user/class/user.class.php
  htdocs/user/class/usergroup.class.php
Labels: PR to fix or conflict to solve

#8531 Add insertExtraFields into create/update
  htdocs/product/stock/class/productlot.class.php
Labels: PR not qualified

#7969 FIX #4875 Remove external module code from Dolibarr core code - Introduce hook initSendToSocid instead
  htdocs/core/actions_sendmails.inc.php
Labels: PR postponed

#8653 NEW: work on CommonObject 'array' field typeNew common object array
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#8563 NEW: default add action: new param $backurlforcard to redirect to card
  htdocs/core/actions_addupdatedelete.inc.php
  htdocs/modulebuilder/template/myobject_card.php
Labels: PR to fix or conflict to solve
