Repository Dolibarr/dolibarr, pull requests merged in 2018-12, with the labels that each got.

#9972 FIX Work with new table actioncomm_resources and multiple contact affectation
  htdocs/core/lib/company.lib.php
Labels: PR to fix or conflict to solve

#9056 FIX : Select first mail model by default
  htdocs/core/class/html.formmail.class.php
Labels: Discussion

#10085 FIX Lines are not inserted correctly if VAT have code
  htdocs/comm/propal/class/propal.class.php
  htdocs/commande/class/commande.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/contrat/class/contrat.class.php
  htdocs/expensereport/class/expensereport.class.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
Labels: Discussion

#9534 Add the ability to sort products by category
  htdocs/core/class/html.form.class.php
Labels: Discussion

#10217 various en_US changes
  htdocs/langs/en_US/accountancy.lang
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/agenda.lang
  htdocs/langs/en_US/banks.lang
  htdocs/langs/en_US/bills.lang
  htdocs/langs/en_US/bookmarks.lang
  htdocs/langs/en_US/boxes.lang
  htdocs/langs/en_US/cashdesk.lang
  htdocs/langs/en_US/categories.lang
  htdocs/langs/en_US/commercial.lang
  htdocs/langs/en_US/companies.lang
  htdocs/langs/en_US/compta.lang
  htdocs/langs/en_US/cron.lang
  htdocs/langs/en_US/deliveries.lang
  htdocs/langs/en_US/errors.lang
  htdocs/langs/en_US/exports.lang
  htdocs/langs/en_US/ftp.lang
  htdocs/langs/en_US/help.lang
  htdocs/langs/en_US/holiday.lang
  htdocs/langs/en_US/install.lang
  htdocs/langs/en_US/interventions.lang
  htdocs/langs/en_US/ldap.lang
  htdocs/langs/en_US/mails.lang
  htdocs/langs/en_US/main.lang
  htdocs/langs/en_US/margins.lang
  htdocs/langs/en_US/members.lang
  htdocs/langs/en_US/opensurvey.lang
  htdocs/langs/en_US/orders.lang
  htdocs/langs/en_US/other.lang
  htdocs/langs/en_US/paybox.lang
  htdocs/langs/en_US/paypal.lang
  htdocs/langs/en_US/products.lang
  htdocs/langs/en_US/projects.lang
  htdocs/langs/en_US/propal.lang
  htdocs/langs/en_US/salaries.lang
  htdocs/langs/en_US/sendings.lang
  htdocs/langs/en_US/sms.lang
  htdocs/langs/en_US/stocks.lang
  htdocs/langs/en_US/stripe.lang
  htdocs/langs/en_US/supplier_proposal.lang
  htdocs/langs/en_US/suppliers.lang
  htdocs/langs/en_US/ticket.lang
  htdocs/langs/en_US/users.lang
  htdocs/langs/en_US/website.lang
  htdocs/langs/en_US/withdrawals.lang
  htdocs/langs/en_US/workflow.lang
Labels: Discussion

#9897 NEW Update working chkbxlst filter for lists
  htdocs/core/class/extrafields.class.php
Labels: PR postponed, PR to merge

#9893 remove fieldlabel and add fieldeditkey
  htdocs/adherents/card.php
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/bank/ligne.php
  htdocs/compta/bank/various_payment/card.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/prelevement.php
  htdocs/compta/salaries/card.php
  htdocs/contact/card.php
  htdocs/core/tpl/notes.tpl.php
  htdocs/datapolicy/admin/setupmail.php
  htdocs/expedition/shipment.php
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
  htdocs/hrm/establishment/card.php
  htdocs/societe/card.php
  htdocs/supplier_proposal/card.php
  htdocs/user/card.php
Labels: PR postponed, PR to merge

#9743 New mass generate
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/facture/list.php
  htdocs/contrat/list.php
  htdocs/core/actions_massactions.inc.php
  htdocs/expensereport/list.php
  htdocs/fichinter/list.php
  htdocs/fourn/commande/list.php
  htdocs/fourn/facture/list.php
  htdocs/fourn/product/list.php
  htdocs/langs/en_US/main.lang
  htdocs/product/list.php
  htdocs/projet/list.php
  htdocs/supplier_proposal/list.php
Labels: PR postponed, PR to merge

#10022 FIX use getEntity('invoice') instead getEntity('facture')
  htdocs/accountancy/customer/card.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/lines.php
  htdocs/accountancy/customer/list.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/admin/prelevement.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/api_invoices.class.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/invoicetemplate_list.php
  htdocs/compta/facture/list.php
  htdocs/compta/paiement.php
  htdocs/compta/paiement/class/paiement.class.php
  htdocs/compta/paiement/list.php
  htdocs/compta/paiement/tovalidate.php
  htdocs/compta/prelevement/bons.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/create.php
  htdocs/compta/stats/byratecountry.php
  htdocs/core/boxes/box_activity.php
  htdocs/core/class/html.form.class.php
  htdocs/core/lib/functions.lib.php
  htdocs/core/modules/modFacture.class.php
  htdocs/fourn/facture/card.php
  htdocs/margin/agentMargins.php
  htdocs/margin/checkMargins.php
  htdocs/margin/productMargins.php
  htdocs/product/class/product.class.php
  htdocs/product/stats/facture.php
  htdocs/societe/class/societe.class.php
Labels: PR postponed, PR to merge

#10043 NEW Add afterSelectContactOptions hook
  htdocs/core/class/html.form.class.php
Labels: PR postponed, PR to merge

#10046 reduce complexity of htmlformmail class
  htdocs/core/class/html.formmail.class.php
Labels: PR postponed, PR to merge

#10056 reduce complexity of eldylib menu
  htdocs/core/menus/standard/eldy.lib.php
Labels: PR postponed, PR to merge

#10057 NEW : conf to change concat desc order
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
  htdocs/contrat/card.php
  htdocs/core/lib/functions.lib.php
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
  htdocs/supplier_proposal/card.php
Labels: PR postponed, PR to merge

#10063 NEW: Add hidden config 'ADD_UNSPLASH_LOGIN_BACKGROUND'
  htdocs/core/tpl/login.tpl.php
Labels: PR postponed, PR to merge

#10116 Introduce standard sql date format filter
  htdocs/core/lib/date.lib.php
Labels: PR postponed, PR to merge

#10152 refactoring list.php with dol_sql_datefilter
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/deplacement/list.php
  htdocs/compta/facture/list.php
  htdocs/compta/paiement/list.php
  htdocs/expensereport/list.php
Labels: PR to fix or conflict to solve

#10068 New: Update just the multiprices that have been changed
  htdocs/product/price.php
Labels: PR postponed, PR to merge

#10098 NEW: Add Autofill Remainder Amount to Expense Report Payment Page
  htdocs/expensereport/payment/payment.php
Labels: PR postponed, PR to merge

#10143 8.0 fix #9964
  htdocs/commande/list.php
  htdocs/core/tpl/extrafields_list_search_sql.tpl.php
Labels: PR to fix or conflict to solve

#9965 FIX screen size fall
  htdocs/comm/remx.php
  htdocs/theme/eldy/style.css.php
Labels: Discussion

#10125 NEW massfilesarea feature for plugin modules
  htdocs/core/lib/files.lib.php
Labels: PR postponed, PR to merge

#10160 NEW: Add stats on entries & movements by fiscal year
  htdocs/accountancy/admin/card.php
  htdocs/accountancy/admin/fiscalyear.php
  htdocs/compta/bank/class/account.class.php
  htdocs/core/class/fiscalyear.class.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR postponed, PR to merge

#10171 FIX scrutinizer
  htdocs/adherents/class/adherent.class.php
  htdocs/adherents/index.php
Labels: PR postponed, PR to merge
