Repository Dolibarr/dolibarr, pull requests merged in 2019-04, with the labels that each got.

#10923 NEW automatic / manual selector form
  htdocs/core/class/html.form.class.php
  htdocs/core/class/html.formother.class.php
  htdocs/core/lib/functions.lib.php
Labels: PR to fix or conflict to solve

#10810 NEW improve Expensereport, Inverse Receiver
  ChangeLog
  htdocs/core/modules/expensereport/doc/pdf_standard.modules.php
  htdocs/expedition/class/expedition.class.php
  htdocs/langs/de_DE/main.lang
  htdocs/reception/class/reception.class.php
  htdocs/societe/class/societe.class.php
Labels: Discussion

#10916 Update EBP export
  htdocs/accountancy/class/accountancyexport.class.php
Labels: PR needs tester feedback, PR to merge

#10942 ADD civility label in fetch contact / API
  htdocs/contact/class/contact.class.php
Labels: Discussion

#11016 FIX : Total per day in timespent per week
  htdocs/core/js/timesheet.js
Labels: PR to fix or conflict to solve

#11008 FIX: Update blocked by datec on fiscal year
  htdocs/accountancy/admin/fiscalyear.php
  htdocs/core/class/fiscalyear.class.php
Labels: PR to fix or conflict to solve

#10634 Update stripe version api for payment intent
  htdocs/stripe/config.php
Labels: PR postponed

#10925 NEW morphy value in member type
  htdocs/adherents/class/adherent_type.class.php
  htdocs/adherents/type.php
  htdocs/install/mysql/migration/9.0.0-10.0.0.sql
  htdocs/install/mysql/tables/llx_adherent_type.sql
Labels: PR to fix or conflict to solve
