Repository Dolibarr/dolibarr, pull requests merged in 2019-02, with the labels that each got.

#10404 Fix fetch test
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: PR to fix or conflict to solve

#10477 Fix filter by event type Emailing in show actions done (companylib)
  htdocs/core/lib/company.lib.php
Labels: Discussion

#10520 NEW: Add subledger in various payment
  htdocs/compta/bank/class/paymentvarious.class.php
  htdocs/compta/bank/various_payment/card.php
  htdocs/install/mysql/migration/9.0.0-10.0.0.sql
  htdocs/install/mysql/tables/llx_payment_various.sql
Labels: PR to fix or conflict to solve

#10563 NEW: Stripe payment intent
  htdocs/install/mysql/migration/9.0.0-10.0.0.sql
  htdocs/install/mysql/tables/llx_prelevement_facture_demande.sql
  htdocs/stripe/class/stripe.class.php
Labels: Discussion

#10603 Add default warehouse id for a user
  htdocs/install/mysql/migration/9.0.0-10.0.0.sql
  htdocs/install/mysql/tables/llx_user.sql
Labels: PR to fix or conflict to solve

#10606 update with html5 compliant code
  htdocs/compta/clients.php
  htdocs/compta/compta-files.php
  htdocs/compta/index.php
  htdocs/compta/paiement.php
  htdocs/compta/paiement_charge.php
  htdocs/compta/recap-compta.php
  htdocs/compta/tva/index.php
  htdocs/compta/tva/list.php
  htdocs/compta/tva/quadri_detail.php
  htdocs/contact/consumption.php
Labels: PR to fix - Continuous Integration Test failed

#10518 FIX positive values IN supplier credit notes creating diff on addline rounding
  htdocs/fourn/class/fournisseur.facture.class.php
Labels: Discussion

#10633 NEW options for alternative method
  htdocs/stripe/admin/stripe.php
Labels: Discussion

#10624 selectMulticurrency avoid malformed empty value
  htdocs/core/class/html.form.class.php
Labels: Discussion

#10698 Add parent establishment
  htdocs/core/class/html.form.class.php
  htdocs/hrm/admin/admin_establishment.php
  htdocs/hrm/class/establishment.class.php
  htdocs/hrm/establishment/card.php
Labels: PR to fix or conflict to solve

#10617 NEW Add Default Warehouse to user record (if module stock is on)
  htdocs/user/card.php
  htdocs/user/class/user.class.php
Labels: PR to fix or conflict to solve

#10704 NEW add hidden option MAIN_DOC_UPLOAD_NOT_RENAME_BY_DEFAULT
  htdocs/core/class/html.formfile.class.php
Labels: PR to fix or conflict to solve

#10705 FIX : if empty error message, we just see "error" displayed
  htdocs/core/modules/mailings/modules_mailings.php
  htdocs/core/modules/mailings/xinputfile.modules.php
Labels: PR to fix or conflict to solve
