Repository Dolibarr/dolibarr, pull requests merged in 2019-03, with the labels that each got.

#10728 Html5 margin
  htdocs/livraison/card.php
  htdocs/margin/admin/margin.php
  htdocs/margin/agentMargins.php
  htdocs/margin/checkMargins.php
  htdocs/margin/customerMargins.php
  htdocs/margin/productMargins.php
  htdocs/margin/tabs/productMargins.php
  htdocs/margin/tabs/thirdpartyMargins.php
  htdocs/modulebuilder/admin/setup.php
  htdocs/modulebuilder/index.php
  htdocs/modulebuilder/template/mymoduleindex.php
  htdocs/modulebuilder/template/myobject_list.php
Labels: Discussion

#10729 replace html by html5 in contrat
  htdocs/contrat/card.php
  htdocs/contrat/index.php
  htdocs/contrat/list.php
  htdocs/contrat/services_list.php
  htdocs/contrat/tpl/linkedobjectblock.tpl.php
Labels: PR to fix or conflict to solve

#10730 replace html by html5 in accountancy
  htdocs/accountancy/admin/account.php
  htdocs/accountancy/admin/accountmodel.php
  htdocs/accountancy/admin/categories_list.php
  htdocs/accountancy/admin/closure.php
  htdocs/accountancy/admin/defaultaccounts.php
  htdocs/accountancy/admin/fiscalyear.php
  htdocs/accountancy/admin/importaccounts.php
  htdocs/accountancy/admin/journals_list.php
  htdocs/accountancy/admin/productaccount.php
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/accountancy/bookkeeping/balancebymonth.php
  htdocs/accountancy/bookkeeping/card.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/bookkeeping/thirdparty_lettering_customer.php
  htdocs/accountancy/bookkeeping/thirdparty_lettering_supplier.php
  htdocs/accountancy/customer/lines.php
  htdocs/accountancy/customer/list.php
  htdocs/accountancy/expensereport/lines.php
  htdocs/accountancy/expensereport/list.php
  htdocs/accountancy/journal/bankjournal.php
  htdocs/accountancy/supplier/lines.php
  htdocs/accountancy/supplier/list.php
Labels: Discussion

#10332 FIX : Check for old picture name if the new one was not found
  htdocs/theme/eldy/style.css.php
Labels: Discussion

#10451 Update eldy.lib.php
  htdocs/core/menus/standard/eldy.lib.php
Labels: PR to merge

#10736 Fix remove "canceled" invoices in margin by user
  htdocs/margin/agentMargins.php
  htdocs/margin/checkMargins.php
  htdocs/margin/customerMargins.php
  htdocs/margin/productMargins.php
Labels: PR to fix or conflict to solve

#10783 FIX: Accountancy - Format EBP import
  dev/resources/iso-normes/Accountancy-format_Ebp_txt.pdf
  htdocs/accountancy/class/accountancyexport.class.php
Labels: Discussion

#10647 Factor css and allow use vars
  htdocs/core/lib/functions.lib.php
  htdocs/core/lib/functions2.lib.php
  htdocs/theme/eldy/_badges.css.php
  htdocs/theme/eldy/_global.css.php
  htdocs/theme/eldy/_main_menu_fa_icons.css.php
  htdocs/theme/eldy/doc/badges.php
  htdocs/theme/eldy/doc/doc.css
  htdocs/theme/eldy/img/fontawesome/README
  htdocs/theme/eldy/img/fontawesome/cash-register-solid.svg
  htdocs/theme/eldy/img/fontawesome/home-solid.svg
  htdocs/theme/eldy/main_menu_fa_icons.css
  htdocs/theme/eldy/style.css.php
  htdocs/theme/eldy/theme_vars.php
Labels: PR to merge

#8831 NEW Adding code to show update date of supplier price shown
  htdocs/fourn/class/fournisseur.product.class.php
  htdocs/product/fournisseurs.php
Labels: PR to fix or conflict to solve

#7411 Fix: Custom info view in services
  htdocs/product/card.php
Labels: PR postponed

#9652 FIX : need to round with 2 decimals to avoid movements not correctly balanced
  htdocs/accountancy/bookkeeping/card.php
Labels: PR to fix or conflict to solve

#10846 New branch 15 03 2019
  htdocs/fourn/class/fournisseur.product.class.php
  htdocs/imports/index.php
  htdocs/install/repair.php
  htdocs/install/step2.php
  htdocs/install/upgrade.php
  htdocs/install/upgrade2.php
  htdocs/opensurvey/index.php
  htdocs/opensurvey/list.php
  htdocs/product/admin/dynamic_prices.php
  htdocs/product/admin/product.php
  htdocs/product/admin/product_tools.php
  htdocs/product/composition/card.php
  htdocs/product/inventory/list.php
  htdocs/product/inventory/tpl/inventory.tpl.php
Labels: PR to fix or conflict to solve

#10866 Fix donation list with thirdparty mode when using option DONATION_USE_THIRDPARTIES
  htdocs/don/list.php
Labels: PR to fix or conflict to solve

#10851 Add fk_project to product table
  htdocs/install/mysql/migration/9.0.0-10.0.0.sql
  htdocs/install/mysql/tables/llx_product.key.sql
  htdocs/install/mysql/tables/llx_product.sql
Labels: PR to fix or conflict to solve

#10880 allow empty value for payment conditions like in orders
  htdocs/comm/propal/card.php
Labels: Discussion
