Repository Dolibarr/dolibarr, pull requests merged in 2019-07, with the labels that each got.

#11238 FIX missing "dropdown-icon" replacement
  htdocs/main.inc.php
Labels: Discussion, PR postponed

#11433 FIX: stock increase on shipment deletion if STOCK_CALCULATE_ON_SHIPMENT_CLOSE is set
  htdocs/expedition/card.php
  htdocs/expedition/class/expedition.class.php
  htdocs/langs/fr_FR/sendings.lang
Labels: Discussion

#11022 NEW : manage output languages for free text
  htdocs/admin/bom.php
  htdocs/admin/chequereceipts.php
  htdocs/admin/commande.php
  htdocs/admin/contract.php
  htdocs/admin/expedition.php
  htdocs/admin/expensereport.php
  htdocs/admin/facture.php
  htdocs/admin/fichinter.php
  htdocs/admin/holiday.php
  htdocs/admin/livraison.php
  htdocs/admin/propal.php
  htdocs/admin/supplier_invoice.php
  htdocs/admin/supplier_order.php
  htdocs/admin/supplier_proposal.php
  htdocs/core/actions_setfreetext.inc.php
  htdocs/core/lib/pdf.lib.php
  htdocs/core/tpl/admin_freetext.tpl.php
Labels: PR postponed, PR to merge

#11524 ADD futur_usage stripe.class.php
  htdocs/stripe/class/stripe.class.php
Labels: Discussion

#11528 Fix: Use special_code=4 for Takepos
  htdocs/install/mysql/migration/9.0.0-10.0.0.sql
  htdocs/takepos/invoice.php
Labels: Discussion

#11396 NEW Management of retained warranty on situation invoices
  htdocs/admin/facture_situation.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/list.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/lib/invoice.lib.php
  htdocs/core/lib/pdf.lib.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/install/mysql/migration/8.0.0-9.0.0.sql
  htdocs/install/mysql/tables/llx_facture.sql
  htdocs/langs/en_US/bills.lang
  test/phpunit/FactureTest.php
Labels: Analysis of PR in progres, Discussion
