Repository Dolibarr/dolibarr, pull requests merged in 2019-10, with the labels that each got.

#11933 FIX : change product type must be allowed if we activate hidden conf
  htdocs/product/card.php
Labels: PR to fix or conflict to solve

#12045 [fix #12041] - Generate password mode perso
  htdocs/admin/security.php
Labels: Discussion

#12015 NEW expense request and holiday validator fields
  htdocs/expensereport/card.php
  htdocs/holiday/card.php
  htdocs/langs/en_US/users.lang
  htdocs/user/card.php
Labels: Discussion

#12026 Fix error in triggers process
  htdocs/user/class/user.class.php
Labels: Discussion

#11829 NEW : Address/Contact by default on third parties
  htdocs/contact/card.php
  htdocs/contact/class/contact.class.php
  htdocs/contact/list.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/class/html.formcompany.class.php
  htdocs/core/lib/company.lib.php
  htdocs/core/triggers/interface_90_modSociete_ContactRoles.class.php
  htdocs/install/mysql/migration/10.0.0-11.0.0.sql
  htdocs/install/mysql/tables/llx_societe_contacts.key.sql
  htdocs/install/mysql/tables/llx_societe_contacts.sql
  htdocs/langs/en_US/main.lang
Labels: Discussion, PR to merge

#11920 NEW translation for member type
  htdocs/adherents/class/adherent_type.class.php
  htdocs/adherents/type_translation.php
  htdocs/core/lib/member.lib.php
  htdocs/install/mysql/migration/10.0.0-11.0.0.sql
  htdocs/install/mysql/tables/llx_adherent_type_lang.sql
Labels: PR to fix or conflict to solve

#12062 remove stock data from getsupplierprice
  htdocs/product/class/api_products.class.php
Labels: Discussion

#11371 New:Show labels of countries in modulebuilder
  htdocs/core/class/ccountry.class.php
Labels: Discussion

#11831 NEW auto set closing date and user on invoice
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/list.php
  htdocs/install/mysql/migration/10.0.0-11.0.0.sql
  htdocs/install/mysql/tables/llx_facture.sql
Labels: Discussion

#11340 NEW: capacity value in product
  htdocs/install/mysql/migration/10.0.0-11.0.0.sql
  htdocs/install/mysql/tables/llx_product.sql
  htdocs/product/class/product.class.php
Labels: Discussion

#10960 NEW: look and feel appli
  htdocs/main.inc.php
  htdocs/theme/common/appli_dolibarr_256x256.png
  htdocs/theme/eldy/manifest.json.php
Labels: Discussion

#12093 fix search by roles
  htdocs/core/lib/company.lib.php
Labels: Discussion

#11995 Unlock title button feature
  htdocs/core/lib/functions.lib.php
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/md/style.css.php
Labels: Discussion

#12135 NEW Can update product type with update method
  htdocs/product/class/api_products.class.php
  htdocs/product/class/product.class.php
Labels: Discussion

#12137 Update box_task.php
  htdocs/core/boxes/box_task.php
Labels: Discussion

#12141 Fix non-numeric value encountered on ical export
  htdocs/comm/action/class/actioncomm.class.php
Labels: PR to fix or conflict to solve

#11084 NEW : mass email action on invoice list use billing contact if exists
  htdocs/core/actions_massactions.inc.php
Labels: PR to merge

#12193 NEW: package sql data
  htdocs/install/mysql/migration/10.0.0-11.0.0.sql
  htdocs/install/mysql/tables/llx_c_shipment_package_type
  htdocs/install/mysql/tables/llx_expedition_package.sql
Labels: PR to fix or conflict to solve
