Repository Dolibarr/dolibarr, pull requests merged in 2019-01, with the labels that each got.

#10291 FIX: delete all contact categories
  htdocs/contact/card.php
Labels: Discussion

#10305 Fix #10301 mass bill orders
  htdocs/core/actions_massactions.inc.php
Labels: PR to fix or conflict to solve

#10335 NEW add page to setup opening hours of the company
  htdocs/admin/schedule.php
  htdocs/core/lib/admin.lib.php
Labels: Discussion

#10027 New manage multicompany for invoice
  htdocs/accountancy/class/lettering.class.php
  htdocs/comm/card.php
  htdocs/compta/bank/bankentries_list.php
  htdocs/compta/bank/treso.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/class/facturestats.class.php
  htdocs/compta/index.php
  htdocs/compta/journal/purchasesjournal.php
  htdocs/compta/journal/sellsjournal.php
  htdocs/compta/paiement/card.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/class/rejetprelevement.class.php
  htdocs/compta/prelevement/create.php
  htdocs/compta/prelevement/demandes.php
  htdocs/compta/prelevement/factures.php
  htdocs/compta/prelevement/index.php
  htdocs/compta/prelevement/ligne.php
  htdocs/compta/prelevement/list.php
  htdocs/compta/recap-compta.php
  htdocs/compta/resultat/clientfourn.php
  htdocs/compta/resultat/index.php
  htdocs/compta/stats/cabyprodserv.php
  htdocs/compta/stats/cabyuser.php
  htdocs/compta/stats/casoc.php
  htdocs/compta/stats/index.php
  htdocs/core/boxes/box_factures.php
  htdocs/core/boxes/box_factures_imp.php
  htdocs/core/lib/tax.lib.php
  htdocs/core/modules/facture/mod_facture_mars.php
  htdocs/core/modules/facture/mod_facture_terre.php
  htdocs/core/modules/rapport/pdf_paiement.class.php
  htdocs/margin/tabs/thirdpartyMargins.php
  htdocs/product/index.php
  htdocs/societe/consumption.php
  htdocs/stripe/payment.php
  scripts/accountancy/export-thirdpartyaccount.php
Labels: PR to fix or conflict to solve

#10346 update with html5 compliant code
  build/exe/doliwamp/index.php.install
  htdocs/accountancy/admin/fiscalyear.php
  htdocs/accountancy/admin/importaccounts.php
  htdocs/accountancy/admin/productaccount.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/expensereport/index.php
  htdocs/accountancy/expensereport/lines.php
  htdocs/accountancy/supplier/index.php
  htdocs/fichinter/card-rec.php
  htdocs/fichinter/card.php
  htdocs/reception/card.php
  htdocs/reception/list.php
Labels: PR to fix or conflict to solve

#10345 NEW Api list of currencies
  htdocs/api/class/api_setup.class.php
Labels: PR to fix - Continuous Integration Test failed

#10369 Add configurable days to SEPA Withdrawal Execution Date
  htdocs/admin/prelevement.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/create.php
  htdocs/install/mysql/data/llx_const.sql
  htdocs/install/mysql/migration/8.0.0-9.0.0.sql
  htdocs/langs/en_US/withdrawals.lang
Labels: PR to fix or conflict to solve

#10384 fix php warning
  htdocs/resource/class/dolresource.class.php
Labels: PR to fix or conflict to solve

#10376 Compute value of computed extrafield on fetch, not on show
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/extrafields.class.php
Labels: PR to fix or conflict to solve

#10378 Export journaux
  htdocs/accountancy/journal/bankjournal.php
  htdocs/accountancy/journal/expensereportsjournal.php
  htdocs/accountancy/journal/purchasesjournal.php
Labels: PR to fix or conflict to solve

#10388 FIX JSON.parse not needeed and missing simple quote escaping
  htdocs/takepos/takepos.php
Labels: Discussion

#10413 Add date_livraison substitution
  htdocs/core/lib/functions.lib.php
Labels: PR to fix or conflict to solve

#10368 NEW thirdparty in donation if option ON
  htdocs/don/card.php
  htdocs/don/class/don.class.php
  htdocs/don/list.php
  htdocs/install/mysql/tables/llx_don.sql
Labels: PR to fix or conflict to solve

#10398 Fix missing trigger
  htdocs/compta/sociales/class/chargesociales.class.php
Labels: PR to fix - Continuous Integration Test failed
