Repository Dolibarr/dolibarr, pull requests merged in 2020-11, with the labels that each got.

#15213 FIX - 10.0 - remove 'action' parameter from redirect URL when reordering lines
  htdocs/core/tpl/ajaxrow.tpl.php
Labels: Discussion

#15292 NEW: Add select by supplier category
  htdocs/fourn/facture/list.php
Labels: PR postponed

#15322 NEW include tpl for loading lang file for extra fields in list
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/facture/list.php
  htdocs/contact/list.php
  htdocs/core/tpl/extrafields_list_array_fields.tpl.php
  htdocs/expedition/list.php
  htdocs/modulebuilder/template/myobject_list.php
  htdocs/product/list.php
  htdocs/societe/list.php
  htdocs/ticket/list.php
Labels: PR to fix or conflict to solve

#15429 Fix supplier barcode should be same in fetch and fetch list.
  htdocs/commande/class/commande.class.php
  htdocs/fourn/class/fournisseur.product.class.php
Labels: Discussion

#15433 NEW log sale without lines as error in cash desk
  htdocs/takepos/invoice.php
Labels: Discussion

#15373 New: Reset invalid email script
  htdocs/compta/bank/graph.php
  scripts/emailings/reset-invalid-emails.php
Labels: PR to fix or conflict to solve

#15482 Fix contact API
  htdocs/societe/class/api_contacts.class.php
Labels: PR to fix or conflict to solve

#15180 NEW: Accountancy - Add export for Gestinum (v3 & v5)
  htdocs/accountancy/class/accountancyexport.class.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR postponed

#15512 Fix issue #15506 tansfer line extrafield order to expedition
  htdocs/expedition/card.php
Labels: Discussion
