Repository Dolibarr/dolibarr, pull requests merged in 2020-05, with the labels that each got.

#13649 NEW class tool for converting units
  htdocs/core/class/cunits.class.php
  htdocs/core/db/DoliDB.class.php
Labels: Discussion

#13794 Fix addline titles
  htdocs/core/tpl/objectline_create.tpl.php
Labels: Discussion

#13738 links color for table title line is equal to Text color for table title line
  htdocs/admin/ihm.php
  htdocs/core/lib/usergroups.lib.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/eldy/style.css.php
  htdocs/theme/eldy/theme_vars.inc.php
  htdocs/theme/md/style.css.php
  htdocs/theme/md/theme_vars.inc.php
Labels: Discussion

#13821 NEW Add invoice stat graph and categ search
  htdocs/compta/facture/stats/index.php
  htdocs/core/class/dolgraph.class.php
Labels: PR to fix or conflict to solve

#13862 NEW Accountancy balance - Add a input to show subtotal by group
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR to merge

#13787 Enable multiple mass actions on a single page - dev branch
  htdocs/core/class/html.form.class.php
Labels: PR postponed

#13935 Update paymentloan.class.php
  htdocs/loan/class/paymentloan.class.php
Labels: PR to merge

#13944 Fix board expensereport and holiday
  htdocs/expensereport/class/expensereport.class.php
  htdocs/holiday/class/holiday.class.php
  htdocs/index.php
Labels: PR to merge

#13945 Fix board expense report to approve
  htdocs/index.php
  htdocs/theme/eldy/info-box.inc.php
  htdocs/theme/md/info-box.inc.php
Labels: PR to merge

#13823 NEW: Add quick dropdown menu in top right menu (MAIN_USE_TOP_MENU_QUICKADD_DROPDOWN)
  htdocs/langs/en_US/main.lang
  htdocs/main.inc.php
  htdocs/theme/eldy/dropdown.inc.php
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/eldy/style.css.php
Labels: PR postponed

#13939 Fix : some comment and translation
  htdocs/accountancy/admin/account.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/modulebuilder/template/core/modules/mymodule/mod_myobject_standard.php
Labels: PR to fix or conflict to solve

#13875 NEW Date shipment from order accepts hours
  htdocs/commande/card.php
  htdocs/commande/list.php
  htdocs/expedition/list.php
  htdocs/expedition/shipment.php
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_commande.sql
Labels: PR to fix or conflict to solve

#13703 remove deprecated libelle to fix phpunit
  htdocs/product/stock/card.php
  htdocs/product/stock/class/entrepot.class.php
  htdocs/product/stock/class/mouvementstock.class.php
  htdocs/product/stock/movement_card.php
  htdocs/product/stock/movement_list.php
  htdocs/product/stock/product.php
Labels: PR postponed

#13852 Add columns for multiprices in product list
  htdocs/product/list.php
Labels: Discussion, PR to fix or conflict to solve

#13782 NEW enable free emails input with select2
  htdocs/core/actions_sendmails.inc.php
  htdocs/core/class/html.form.class.php
  htdocs/core/class/html.formmail.class.php
  htdocs/core/lib/project.lib.php
  htdocs/langs/en_US/mails.lang
Labels: Discussion, PR postponed

#13825 NEW Add option to define a default warehouse at user level
  htdocs/admin/stock.php
  htdocs/langs/en_US/stocks.lang
  htdocs/langs/fr_FR/stocks.lang
  htdocs/product/class/html.formproduct.class.php
Labels: Discussion, PR postponed

#13676 Cleanup user rights on forun facture card
  htdocs/fourn/facture/card.php
Labels: PR postponed, PR to merge

#13678 Cleanup user rights forun commande card
  htdocs/fourn/commande/card.php
Labels: PR postponed, PR to merge

#13679 Cleanup user rights on supplier proposal card
  htdocs/supplier_proposal/card.php
Labels: PR postponed, PR to merge

#13582 NEW Use new category API for project list view
  htdocs/core/class/html.formcategory.class.php
  htdocs/product/stock/list.php
  htdocs/projet/list.php
Labels: PR postponed
