Repository Dolibarr/dolibarr, pull requests merged in 2020-09, with the labels that each got.

#14632 NEW translate classification labels in ticket
  htdocs/core/triggers/interface_50_modTicket_TicketEmail.class.php
  htdocs/ticket/card.php
  htdocs/ticket/list.php
Labels: Discussion

#14493 NEW Accountancy - Add options to disable accounting on sales, purchases & expense reports
  htdocs/accountancy/admin/index.php
  htdocs/core/menus/init_menu_auguria.sql
  htdocs/core/menus/standard/auguria.lib.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/langs/en_US/accountancy.lang
Labels: Discussion, PR to merge

#14639 NEW ref_ext in llx_facturedet
  htdocs/compta/facture/class/facture.class.php
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_facturedet.sql
Labels: PR to fix or conflict to solve

#14611 New : add massActions "Validate" and "Sign"
  htdocs/comm/propal/list.php
  htdocs/langs/fr_FR/propal.lang
Labels: PR to fix or conflict to solve

#14603 NEW Accountancy - On transfers, select the periodicity by default
  htdocs/accountancy/admin/index.php
  htdocs/accountancy/journal/bankjournal.php
  htdocs/accountancy/journal/expensereportsjournal.php
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/core/lib/accounting.lib.php
  htdocs/langs/en_US/accountancy.lang
  htdocs/langs/en_US/other.lang
Labels: PR to fix or conflict to solve

#14617 NEW Show header numbers and make it clickable in shipment area
  htdocs/expedition/index.php
Labels: PR to fix or conflict to solve

#14636 NEW Add helper function for table headers with numbers
  htdocs/comm/index.php
  htdocs/core/lib/functions.lib.php
Labels: PR to fix or conflict to solve

#14673 FIX Cron load lang
  htdocs/core/class/translate.class.php
  htdocs/cron/class/cronjob.class.php
Labels: Discussion

#14738 Debugbar - Move to Font Awesome 5 Free
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/md/style.css.php
Labels: PR to merge

#14757 FIX Yogosha report 4426 (backport)
  htdocs/core/class/html.formfile.class.php
  htdocs/ecm/file_card.php
Labels: PR to merge

#14758 FIX Yogosha report 4430 (backport)
  htdocs/fourn/facture/rapport.php
  htdocs/reception/stats/month.php
Labels: PR to merge

#14726 Fix display on quickadd dropdown menu
  htdocs/langs/en_US/supplier_proposal.lang
  htdocs/theme/eldy/dropdown.inc.php
Labels: PR to merge

#14668 NEW : Email configuration - Allow auto signed certificat when smtp ssl activated
  htdocs/admin/mails.php
  htdocs/admin/mails_emailing.php
  htdocs/core/class/CMailFile.class.php
  htdocs/core/class/smtps.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: Discussion

#14633 NEW Improve Product API for variant products
  htdocs/product/class/api_products.class.php
Labels: PR to fix or conflict to solve

#14759 FIX Yogosha report 4433 (backport)
  htdocs/document.php
  htdocs/viewimage.php
Labels: PR to fix or conflict to solve

#14760 FIX Yogosha report 4434 (backport)
  htdocs/adherents/card.php
Labels: PR to fix or conflict to solve

#14761 FIX Yogosha report 4435 (backport)
  htdocs/takepos/invoice.php
Labels: PR to fix or conflict to solve

#14772 FIX Yogosha report 4465 (backport)
  htdocs/core/lib/security2.lib.php
Labels: PR to fix or conflict to solve

#14777 NEW Use preselect third-party from list on new card
  htdocs/accountancy/bookkeeping/list.php
  htdocs/categories/index.php
  htdocs/comm/action/list.php
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/bank/list.php
  htdocs/compta/bank/various_payment/list.php
  htdocs/compta/facture/list.php
  htdocs/compta/localtax/list.php
  htdocs/compta/paiement/cheque/list.php
  htdocs/compta/tva/list.php
  htdocs/contact/list.php
  htdocs/contrat/list.php
  htdocs/expedition/list.php
  htdocs/expensereport/list.php
  htdocs/fichinter/list.php
  htdocs/fourn/commande/list.php
  htdocs/fourn/facture/list.php
  htdocs/holiday/list.php
  htdocs/loan/list.php
  htdocs/product/list.php
  htdocs/projet/list.php
  htdocs/projet/tasks/list.php
  htdocs/salaries/list.php
  htdocs/societe/list.php
  htdocs/supplier_proposal/list.php
  htdocs/ticket/list.php
  htdocs/user/list.php
Labels: PR to fix or conflict to solve

#14671 NEW: Added incoterms to substitution array
  htdocs/core/class/commondocgenerator.class.php
Labels: PR to fix or conflict to solve

#14447 fix document.php external module multidiroutput
  htdocs/core/lib/files.lib.php
Labels: PR to fix or conflict to solve

#14741 FIX: Allow product price equal zero in new lines
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
Labels: Discussion

#14849 NEW Add column vat rate in page to define accounting account on product/service
  htdocs/accountancy/admin/productaccount.php
Labels: Discussion

#14825 Fix notification system
  htdocs/comm/action/card.php
  htdocs/comm/action/class/actioncomm.class.php
Labels: Discussion

#14856 new:bankline_prepare_head for bank lines
  htdocs/compta/bank/line.php
  htdocs/core/lib/payments.lib.php
Labels: Discussion

#14837 NEW: Introducing new modal boxes in TakePOS
  htdocs/takepos/css/pos.css.php
  htdocs/takepos/index.php
Labels: Discussion
