Repository Dolibarr/dolibarr, pull requests merged in 2020-12, with the labels that each got.

#15617 NEW Takepos - Add labels to icons in Numpad
  htdocs/takepos/css/pos.css.php
  htdocs/takepos/pay.php
Labels: Discussion

#15602 API orders: Update demand reason on order update
  htdocs/commande/class/commande.class.php
Labels: Discussion, PR to fix or conflict to solve

#15619 WIP #15383 : New widget: Tunnel of prospection
  htdocs/core/boxes/box_funnel_of_prospection.php
  htdocs/core/modules/modProjet.class.php
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/langs/en_US/boxes.lang
Labels: Discussion, PR to fix or conflict to solve

#15692 FIX 12.0 - XSS protection too stringent -> replace 'alphanohtml' with 'restricthtml'
  htdocs/product/card.php
Labels: Discussion

#15727 add option hide topmenu in Config/Display
  htdocs/admin/ihm.php
  htdocs/core/lib/usergroups.lib.php
Labels: Discussion

#15756 Update V12 fournisseurs.php to Fix #15755 Product: purchase price tab, supplier price table with list of products not "responsive"
  htdocs/product/fournisseurs.php
Labels: Bug, Works for me / Can't reproduce

#15566 remove warnings
  htdocs/comm/mailing/card.php
  htdocs/comm/mailing/class/mailing.class.php
  htdocs/comm/mailing/info.php
Labels: PR postponed

#15765 NEW: Accountancy - In ledger & journals, show link on bank transaction
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/bookkeeping/listbysubaccount.php
Labels: PR postponed, PR to merge

#15585 NEW Can toggle FCKeditor on public/private notes
  htdocs/admin/fckeditor.php
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/deplacement/card.php
  htdocs/compta/facture/card-rec.php
  htdocs/compta/facture/card.php
  htdocs/contact/card.php
  htdocs/contrat/card.php
  htdocs/don/card.php
  htdocs/expedition/card.php
  htdocs/expensereport/card.php
  htdocs/fichinter/card.php
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
  htdocs/loan/card.php
  htdocs/reception/card.php
Labels: PR postponed

#15500 NEW add db fields note_public note_private for ecm
  htdocs/core/class/commonobject.class.php
  htdocs/core/lib/ecm.lib.php
  htdocs/core/tpl/notes.tpl.php
  htdocs/ecm/class/ecmfiles.class.php
  htdocs/ecm/file_card.php
  htdocs/ecm/file_note.php
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_ecm_directories.sql
  htdocs/install/mysql/tables/llx_ecm_files.sql
Labels: PR postponed, PR to merge

#15476 Fix edition of tag/category which used type parameter instead of object's type
  htdocs/categories/edit.php
  htdocs/categories/info.php
  htdocs/categories/photos.php
  htdocs/categories/traduction.php
  htdocs/categories/viewcat.php
  htdocs/core/lib/categories.lib.php
Labels: Discussion, PR postponed, PR to merge

#15478 NEW: Add edit/delete action icons on categories list pages
  htdocs/categories/edit.php
  htdocs/categories/index.php
  htdocs/categories/viewcat.php
Labels: PR postponed, PR to merge

#15351 separate ref and rowid in members
  htdocs/adherents/card.php
  htdocs/adherents/cartes/carte.php
  htdocs/adherents/class/adherent.class.php
  htdocs/adherents/list.php
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_adherent.key.sql
  htdocs/install/mysql/tables/llx_adherent.sql
  test/phpunit/AdherentTest.php
Labels: PR postponed, PR to merge

#15802 FIX: Accountancy - Retire entire opening balance feature
  htdocs/accountancy/bookkeeping/balance.php
Labels: PR to fix or conflict to solve, PR to merge

#15283 NEW massaction for Bank Transfer
  htdocs/fourn/facture/list.php
  htdocs/langs/en_US/withdrawals.lang
Labels: PR postponed, PR to merge

#15308 NEW: Dictionary for availability - Add column position
  htdocs/admin/dict.php
  htdocs/core/class/html.form.class.php
  htdocs/install/mysql/data/llx_c_availability.sql
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_c_availability.sql
Labels: PR postponed, PR to merge

#15328 Dev multifilter jounal on bookeping
  htdocs/accountancy/admin/index.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/core/class/html.formaccounting.class.php
  htdocs/langs/en_US/accountancy.lang
  htdocs/langs/fr_FR/accountancy.lang
Labels: PR postponed, PR to merge

#15339 Dev multifilter journal on ledger (complete)
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/bookkeeping/listbysubaccount.php
  htdocs/accountancy/class/bookkeeping.class.php
Labels: PR postponed, PR to merge

#15434 NEW Dev default date filter module builder
  htdocs/modulebuilder/template/myobject_list.php
Labels: PR postponed, PR to merge
