Repository Dolibarr/dolibarr, pull requests merged in 2020-06, with the labels that each got.

#13922 11.0 new add hook select warehouses
  htdocs/product/class/html.formproduct.class.php
Labels: Discussion, PR to fix or conflict to solve

#13973 FIX : #13968
  htdocs/contact/class/contact.class.php
  htdocs/core/class/commonobject.class.php
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve

#14048 replenish : select expedition quantities only from opened orders when…
  htdocs/product/stock/replenish.php
Labels: Discussion

#14006 fix:The label must be a dictionary key
  htdocs/modulebuilder/index.php
Labels: Discussion

#14037 FIX free text on cash desk
  htdocs/takepos/admin/setup.php
Labels: Discussion

#14032 NEW convert all subscription in datetime
  htdocs/adherents/class/subscription.class.php
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_subscription.sql
Labels: PR to fix or conflict to solve

#13799 NEW Can set type of price without tax) per defaut for new sale price creation
  htdocs/install/mysql/data/llx_const.sql
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/langs/en_US/products.lang
  htdocs/langs/fr_FR/products.lang
  htdocs/product/admin/product.php
  htdocs/product/card.php
Labels: PR to fix or conflict to solve, PR to merge

#14061 FIX : percent must be displayed on one line
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
Labels: Discussion
