Repository Dolibarr/dolibarr, pull requests merged in 2020-08, with the labels that each got.

#13759 NEW: Add prospect status managment for the contact with managment of custom icon
  htdocs/admin/dict.php
  htdocs/comm/card.php
  htdocs/comm/prospect/index.php
  htdocs/contact/card.php
  htdocs/contact/class/contact.class.php
  htdocs/contact/list.php
  htdocs/core/class/html.formcompany.class.php
  htdocs/core/lib/functions.lib.php
  htdocs/install/mysql/data/llx_c_prospectcontactlevel.sql
  htdocs/install/mysql/data/llx_c_stcommcontact.sql
  htdocs/install/mysql/migration/11.0.0-12.0.0.sql
  htdocs/install/mysql/tables/llx_c_prospectcontactlevel.sql
  htdocs/install/mysql/tables/llx_c_stcommcontact.key.sql
  htdocs/install/mysql/tables/llx_c_stcommcontact.sql
  htdocs/install/mysql/tables/llx_socpeople.sql
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
  htdocs/societe/class/client.class.php
  htdocs/societe/class/societe.class.php
  htdocs/societe/list.php
Labels: PR postponed, PR to fix or conflict to solve

#14355 Fix: User can see events that are not assigned to it
  htdocs/core/lib/security.lib.php
Labels: PR to fix or conflict to solve

#14379 FIX filter warehouse list on status
  htdocs/product/stock/list.php
Labels: PR to fix or conflict to solve

#14465 NEW : Declinaison price level compatibility
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_product_attribute_combination_price_level.sql
  htdocs/langs/en_US/products.lang
  htdocs/product/class/product.class.php
  htdocs/variants/class/ProductCombination.class.php
  htdocs/variants/combinations.php
Labels: Discussion

#14427 FIX Visible 0 on accounting account
  htdocs/core/lib/accounting.lib.php
Labels: PR needs feedback

#14451 Bug, this option disable topic input.
  htdocs/admin/mails_templates.php
Labels: Discussion

#14364 fix: restore autofill lost functionality on expeditions
  htdocs/expedition/card.php
Labels: Discussion, PR to fix or conflict to solve

#14531 NEW: Print payment method and change in TakePOS
  htdocs/compta/paiement/class/paiement.class.php
  htdocs/core/class/dolreceiptprinter.class.php
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_paiement.sql
  htdocs/langs/en_US/cashdesk.lang
  htdocs/takepos/admin/receipt.php
  htdocs/takepos/invoice.php
  htdocs/takepos/pay.php
  htdocs/takepos/receipt.php
Labels: PR to fix or conflict to solve

#14520 NEW Show user on external calender events (when found)
  htdocs/comm/action/index.php
  htdocs/user/class/user.class.php
Labels: PR to fix or conflict to solve

#14574 FIX 11.0 - expenses lines overlapping the total amounts frame
  htdocs/core/modules/expensereport/doc/pdf_standard.modules.php
Labels: PR to fix or conflict to solve

#14540 FIX non-numeric value on multicurrency payment (part 1)
  htdocs/fourn/facture/paiement.php
Labels: PR to fix or conflict to solve

#14560 NEW display resiliate status in takepos for member
  htdocs/takepos/invoice.php
Labels: Discussion
