Repository Dolibarr/dolibarr, pull requests merged in 2021-11, with the labels that each got.

#19234 FIX show connected server if we have a primary and secondary ldap server
  htdocs/adherents/ldap.php
  htdocs/adherents/type_ldap.php
  htdocs/admin/ldap.php
  htdocs/admin/ldap_users.php
  htdocs/contact/ldap.php
  htdocs/core/class/ldap.class.php
  htdocs/core/lib/ldap.lib.php
  htdocs/core/lib/security.lib.php
  htdocs/core/login/functions_ldap.php
  htdocs/user/card.php
  htdocs/user/class/user.class.php
  htdocs/user/group/ldap.php
  htdocs/user/ldap.php
Labels: Discussion

#19181 fix warnings in commande list
  htdocs/commande/list.php
Labels: DevCamp 2021 Valence

#19304 Fix default enddate subscription must be in futur
  htdocs/adherents/subscription.php
Labels: Discussion

#19345 FIX lost superadmin grade after edit user card
  htdocs/user/card.php
  htdocs/user/class/user.class.php
Labels: Discussion

#19275 fix error
  htdocs/core/modules/printing/modules_printing.php
Labels: Discussion

#19170 NEW : setup form class to help setup page creation
  htdocs/core/class/html.formsetup.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/modulebuilder/template/admin/setup.php
Labels: PR to fix or conflict to solve, DevCamp 2021 Valence

#18940 NEW : info of number of product still to dispatched in a supplier order
  htdocs/core/lib/fourn.lib.php
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: Discussion, PR to fix or conflict to solve

#17998 FIX: Reload values of the specified entity when change entity in the execution of cron jobs
  htdocs/core/class/conf.class.php
  htdocs/cron/class/cronjob.class.php
Labels: PR to merge

#19370 ADD new stripe provider in dictionnary
  htdocs/install/mysql/data/llx_c_paiement.sql
  htdocs/install/mysql/migration/14.0.0-15.0.0.sql
Labels: PR to fix or conflict to solve

#19281 NEW Thirdparty - Add advanced right to add / edit payment information
  htdocs/core/lib/company.lib.php
  htdocs/core/modules/modSociete.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/societe/paymentmodes.php
Labels: PR to merge

#19163 Fix: php 8.0 warnings project
  htdocs/core/tpl/list_print_total.tpl.php
  htdocs/eventorganization/conferenceorbooth_list.php
  htdocs/projet/activity/perday.php
  htdocs/projet/activity/perweek.php
  htdocs/projet/tasks/list.php
Labels: PR to merge (after fix suggested), DevCamp 2021 Valence

#18331 FIX: multicurrency: fields in discount unitialized when creating deposit
  htdocs/compta/facture/card.php
Labels: PR to merge

#19165 Fix: php 8.0 warning commercial part
  htdocs/comm/propal/card.php
  htdocs/comm/propal/index.php
  htdocs/comm/propal/list.php
  htdocs/commande/card.php
  htdocs/commande/list.php
  htdocs/contrat/list.php
  htdocs/contrat/services_list.php
  htdocs/fourn/commande/list.php
Labels: PR to merge (after fix suggested), DevCamp 2021 Valence
