Repository Dolibarr/dolibarr, pull requests merged in 2021-02, with the labels that each got.

#16158 Add hidden conf to display supplier in object lines
  htdocs/core/tpl/objectline_view.tpl.php
Labels: PR to fix or conflict to solve

#16020 NEW VAT payment request and VAT payment are 2 different steps in workflow on VAT payment recording
  htdocs/compta/bank/bankentries_list.php
  htdocs/compta/bank/line.php
  htdocs/compta/paiement_vat.php
  htdocs/compta/payment_vat/card.php
  htdocs/compta/tva/card.php
  htdocs/compta/tva/class/paymentvat.class.php
  htdocs/compta/tva/class/tva.class.php
  htdocs/compta/tva/index.php
  htdocs/compta/tva/list.php
  htdocs/compta/tva/payments.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/lib/functions.lib.php
  htdocs/core/lib/vat.lib.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_payment_vat.sql
  htdocs/install/mysql/tables/llx_tva.sql
  htdocs/langs/en_US/bills.lang
  htdocs/langs/en_US/compta.lang
Labels: PR to fix or conflict to solve

#16252 Add Hook in stockmouvement
  htdocs/product/stock/class/mouvementstock.class.php
Labels: Discussion

#16253 contract - uses of multidir_output for file path
  htdocs/contrat/card.php
  htdocs/contrat/class/contrat.class.php
  htdocs/contrat/document.php
  htdocs/contrat/list.php
  htdocs/core/lib/contract.lib.php
  htdocs/core/lib/files.lib.php
  htdocs/core/modules/contract/doc/doc_generic_contract_odt.modules.php
  htdocs/core/modules/contract/doc/pdf_strato.modules.php
Labels: PR to fix or conflict to solve

#16210 deprecate api operation
  htdocs/api/class/api_setup.class.php
Labels: Discussion

#16278 new : hook context subscriptioncard and restrictedArea block for subscriptions
  htdocs/adherents/subscription/card.php
Labels: Discussion

#16139 NEW: Stock movement list - Add more complete date field
  htdocs/product/stock/movement_list.php
Labels: PR to merge

#16260 New bank entries tax salary social display user
  htdocs/compta/bank/bankentries_list.php
  htdocs/compta/sociales/class/paymentsocialcontribution.class.php
Labels: PR to fix or conflict to solve

#16353 Code enhanced - Standardize field name #14697
  ChangeLog
  htdocs/comm/propal/class/propal.class.php
  htdocs/comm/propal/index.php
  htdocs/comm/propal/list.php
  htdocs/core/class/commonobject.class.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_propal.sql
Labels: PR to merge

#16335 count actioncomm for thirdparty tab agenda
  htdocs/core/lib/company.lib.php
  htdocs/core/lib/memory.lib.php
Labels: Discussion

#16371 add log for token reclaimed
  htdocs/main.inc.php
Labels: Discussion

#16357 Add substitution for delivry date
  htdocs/core/lib/functions.lib.php
Labels: PR to fix or conflict to solve

#16368 NEW : Tab on project for Event Organization #FoundationFunding
  htdocs/core/lib/project.lib.php
  htdocs/core/modules/modEventOrganization.class.php
  htdocs/eventorganization/class/conferenceorbooth.class.php
  htdocs/eventorganization/conferenceorbooth_agenda.php
  htdocs/eventorganization/conferenceorbooth_card.php
  htdocs/eventorganization/conferenceorbooth_contact.php
  htdocs/eventorganization/conferenceorbooth_document.php
  htdocs/eventorganization/conferenceorbooth_list.php
  htdocs/eventorganization/conferenceorbooth_note.php
  htdocs/eventorganization/eventorganizationindex.php
  htdocs/eventorganization/lib/eventorganization_conferenceorbooth.lib.php
  htdocs/install/mysql/data/llx_c_email_templates.sql
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_projet.sql
  htdocs/langs/en_US/eventorganization.lang
  htdocs/projet/card.php
  htdocs/projet/class/project.class.php
  htdocs/projet/event.php
  htdocs/projet/list.php
Labels: PR to fix or conflict to solve

#16434 differentiate serial numbers from lot management
  htdocs/langs/en_US/productbatch.lang
  htdocs/langs/fr_FR/productbatch.lang
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/list.php
Labels: Discussion

#16124 Fix avoid missing url and token
  htdocs/core/js/lib_head.js.php
Labels: PR to fix or conflict to solve

#16112 Add missing pmp valorisation to MO production. (Issue #16072)
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_mrp_production.sql
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_movements.php
  htdocs/mrp/mo_production.php
Labels: Discussion, Priority Top Strategic

#16469 code syntax r... dir
  htdocs/reception/card.php
  htdocs/reception/class/reception.class.php
  htdocs/reception/class/receptionstats.class.php
  htdocs/reception/contact.php
  htdocs/reception/index.php
  htdocs/reception/list.php
  htdocs/reception/note.php
  htdocs/reception/stats/index.php
  htdocs/reception/stats/month.php
  htdocs/reception/tpl/linkedobjectblock.tpl.php
  htdocs/recruitment/admin/candidature_extrafields.php
  htdocs/recruitment/admin/jobposition_extrafields.php
  htdocs/recruitment/admin/public_interface.php
  htdocs/recruitment/admin/setup.php
  htdocs/recruitment/admin/setup_candidatures.php
  htdocs/recruitment/class/recruitmentcandidature.class.php
  htdocs/recruitment/class/recruitmentjobposition.class.php
  htdocs/recruitment/core/modules/recruitment/doc/doc_generic_recruitmentjobposition_odt.modules.php
  htdocs/recruitment/core/modules/recruitment/doc/pdf_standard_recruitmentjobposition.modules.php
  htdocs/recruitment/core/modules/recruitment/mod_recruitmentcandidature_standard.php
  htdocs/recruitment/core/modules/recruitment/mod_recruitmentjobposition_advanced.php
  htdocs/recruitment/core/modules/recruitment/mod_recruitmentjobposition_standard.php
  htdocs/recruitment/core/modules/recruitment/modules_recruitmentcandidature.php
  htdocs/recruitment/core/modules/recruitment/modules_recruitmentjobposition.php
  htdocs/recruitment/lib/recruitment_recruitmentcandidature.lib.php
  htdocs/recruitment/lib/recruitment_recruitmentjobposition.lib.php
  htdocs/recruitment/recruitmentcandidature_agenda.php
  htdocs/recruitment/recruitmentcandidature_card.php
  htdocs/recruitment/recruitmentcandidature_document.php
  htdocs/recruitment/recruitmentcandidature_list.php
  htdocs/recruitment/recruitmentcandidature_note.php
  htdocs/recruitment/recruitmentindex.php
  htdocs/recruitment/recruitmentjobposition_agenda.php
  htdocs/recruitment/recruitmentjobposition_applications.php
  htdocs/recruitment/recruitmentjobposition_card.php
  htdocs/recruitment/recruitmentjobposition_document.php
  htdocs/recruitment/recruitmentjobposition_list.php
  htdocs/recruitment/recruitmentjobposition_note.php
  htdocs/resource/agenda.php
  htdocs/resource/card.php
  htdocs/resource/class/dolresource.class.php
  htdocs/resource/class/html.formresource.class.php
  htdocs/resource/contact.php
  htdocs/resource/document.php
  htdocs/resource/element_resource.php
  htdocs/resource/list.php
  htdocs/resource/note.php
Labels: PR to fix or conflict to solve
