Repository Dolibarr/dolibarr, pull requests merged in 2021-08, with the labels that each got.

#18224 FIX: Missing column Date validation in ledger & subledger
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/bookkeeping/listbysubaccount.php
Labels: Discussion

#18324 Close #18043 : fk_user_assign in create ticket
  htdocs/core/class/html.formticket.class.php
  htdocs/ticket/card.php
Labels: Discussion

#18190 add categories tickets migration
  htdocs/install/check.php
  htdocs/install/mysql/migration/14.0.0-15.0.0.sql
Labels: PR to fix or conflict to solve

#15548 NEW Can set the default BOM on a product
  htdocs/install/mysql/tables/llx_product.sql
  htdocs/product/card.php
  htdocs/product/class/product.class.php
Labels: PR postponed

#17640 NEW Add sale representative in order and invoice list
  htdocs/commande/list.php
  htdocs/compta/facture/list.php
Labels: PR postponed

#18374 NEW Add option to hide customer code on PDF documents
  htdocs/admin/pdf.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/contract/doc/pdf_strato.modules.php
  htdocs/core/modules/expedition/doc/pdf_espadon.modules.php
  htdocs/core/modules/expedition/doc/pdf_rouget.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/fichinter/doc/pdf_soleil.modules.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix or conflict to solve

#18372 [NEW] PDF show Frame option
  htdocs/admin/pdf.php
  htdocs/admin/pdf_other.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/contract/doc/pdf_strato.modules.php
  htdocs/core/modules/expedition/doc/pdf_espadon.modules.php
  htdocs/core/modules/expedition/doc/pdf_rouget.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/fichinter/doc/pdf_soleil.modules.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix or conflict to solve

#18337 Fix : we only want employee users for holidays
  htdocs/holiday/class/holiday.class.php
Labels: Discussion

#17076 NEW add action trigger for member excluded
  htdocs/install/mysql/data/llx_c_action_trigger.sql
Labels: Discussion

#17687 NEW : mass action paid customer invoice
  htdocs/compta/facture/list.php
  htdocs/core/class/html.form.class.php
  htdocs/langs/en_US/bills.lang
Labels: PR to merge, PR postponed

#18282 FIX: Manage credit note on situation invoice for calculate margin
  htdocs/core/class/html.formmargin.class.php
Labels: PR to merge

#17865 New develop autocomplete accounting account groups
  htdocs/accountancy/admin/card.php
Labels: PR to merge

#17537 New Add option MAIN_FORCE_SHARING_ON_ANY_UPLOADED_FILE to share file on any file upload
  htdocs/core/lib/files.lib.php
Labels: PR to fix or conflict to solve

#18159 New : Language support for knowledge record
  htdocs/core/actions_addupdatedelete.inc.php
  htdocs/core/tpl/commonfields_add.tpl.php
  htdocs/core/tpl/commonfields_edit.tpl.php
  htdocs/core/tpl/commonfields_view.tpl.php
  htdocs/install/mysql/tables/llx_knowledgemanagement_knowledgerecord.sql
  htdocs/knowledgemanagement/class/knowledgerecord.class.php
  htdocs/knowledgemanagement/knowledgerecord_card.php
  htdocs/knowledgemanagement/knowledgerecord_list.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#18409 NEW : Allows product ref generation after the form is validated with PRODUCT_GENERATE_REF_AFTER_FORM
  htdocs/product/card.php
Labels: PR to fix or conflict to solve

#18424 Undefined
  htdocs/comm/action/card.php
  htdocs/comm/action/index.php
  htdocs/contrat/services_list.php
  htdocs/main.inc.php
  htdocs/societe/list.php
  htdocs/supplier_proposal/list.php
Labels: PR to fix or conflict to solve

#18507 Customer Invoice - Multicurrency Remaining to Pay (updated)
  htdocs/compta/facture/card.php
Labels: PR to fix or conflict to solve

#18462 fix : Undefined property: stdClass:: in C:\wamp64\www\dolibarr-140\ht…
  htdocs/comm/propal/card.php
  htdocs/core/actions_builddoc.inc.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/extrafields.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/modules/modBlockedLog.class.php
  htdocs/core/modules/modFicheinter.class.php
  htdocs/product/class/propalmergepdfproduct.class.php
Labels: PR to merge (after fix suggested)

#18445 Fix: TechnicalID displayed 2 times in both MO and BOM the PR hides 1.
  htdocs/bom/class/bom.class.php
  htdocs/mrp/class/mo.class.php
Labels: PR to merge (after fix suggested)

#18475 FIX invoice fetch not found syslog debug level instead of error
  htdocs/compta/facture/class/facture.class.php
Labels: Discussion

#18373 [NEW] PDF Document ref in title option
  htdocs/admin/pdf.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/contract/doc/pdf_strato.modules.php
  htdocs/core/modules/expedition/doc/pdf_espadon.modules.php
  htdocs/core/modules/expedition/doc/pdf_rouget.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/fichinter/doc/pdf_soleil.modules.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
Labels: Discussion
