Repository Dolibarr/dolibarr, pull requests merged in 2021-10, with the labels that each got.

#18832 NEW : integration HRM sql and migration files
  htdocs/install/mysql/migration/14.0.0-15.0.0.sql
  htdocs/install/mysql/tables/llx_hrm_evaluation.key.sql
  htdocs/install/mysql/tables/llx_hrm_evaluation.sql
  htdocs/install/mysql/tables/llx_hrm_evaluation_extrafields.key.sql
  htdocs/install/mysql/tables/llx_hrm_evaluation_extrafields.sql
  htdocs/install/mysql/tables/llx_hrm_evaluationdet.key.sql
  htdocs/install/mysql/tables/llx_hrm_evaluationdet.sql
  htdocs/install/mysql/tables/llx_hrm_evaluationdet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_hrm_evaluationdet_extrafields.sql
  htdocs/install/mysql/tables/llx_hrm_job.key.sql
  htdocs/install/mysql/tables/llx_hrm_job.sql
  htdocs/install/mysql/tables/llx_hrm_job_extrafields.key.sql
  htdocs/install/mysql/tables/llx_hrm_job_extrafields.sql
  htdocs/install/mysql/tables/llx_hrm_job_user.key.sql
  htdocs/install/mysql/tables/llx_hrm_job_user.sql
  htdocs/install/mysql/tables/llx_hrm_job_user_extrafields.key.sql
  htdocs/install/mysql/tables/llx_hrm_job_user_extrafields.sql
  htdocs/install/mysql/tables/llx_hrm_skill.key.sql
  htdocs/install/mysql/tables/llx_hrm_skill.sql
  htdocs/install/mysql/tables/llx_hrm_skill_extrafields.key.sql
  htdocs/install/mysql/tables/llx_hrm_skill_extrafields.sql
  htdocs/install/mysql/tables/llx_hrm_skilldet.key.sql
  htdocs/install/mysql/tables/llx_hrm_skilldet.sql
  htdocs/install/mysql/tables/llx_hrm_skilldet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_hrm_skilldet_extrafields.sql
  htdocs/install/mysql/tables/llx_hrm_skillrank.key.sql
  htdocs/install/mysql/tables/llx_hrm_skillrank.sql
Labels: Discussion, PR to merge (after fix suggested)

#18862 NEW: expense report: show link to already existing overlapping expense report
  htdocs/expensereport/card.php
  htdocs/expensereport/class/expensereport.class.php
Labels: PR to merge (after fix suggested)

#18863 NEW: expense reports: make project field required on lines
  htdocs/admin/expensereport.php
  htdocs/expensereport/card.php
  htdocs/langs/en_US/admin.lang
Labels: Discussion

#18831 NEW Can select existing batch numbers for a combo list (in mrp consumtion)
  htdocs/mrp/mo_production.php
  htdocs/product/class/html.formproduct.class.php
Labels: PR to fix or conflict to solve

#18520 allow supplier order to not generate pdfs
  htdocs/admin/supplier_order.php
  htdocs/admin/supplier_payment.php
  htdocs/fourn/commande/card.php
Labels: Discussion

#19178 fix not defined
  htdocs/projet/tasks/list.php
Labels: DevCamp 2021 Valence

#19182 fix warnings in propal list
  htdocs/comm/propal/list.php
  htdocs/core/class/html.formpropal.class.php
Labels: DevCamp 2021 Valence

#19179 fix warnings in task list
  htdocs/projet/tasks/list.php
Labels: DevCamp 2021 Valence

#19058 fix php8 warning
  htdocs/comm/action/card.php
  htdocs/contact/list.php
  htdocs/core/extrafieldsinexport.inc.php
  htdocs/core/lib/pdf.lib.php
  htdocs/core/modules/bank/doc/pdf_sepamandate.modules.php
  htdocs/core/modules/societe/mod_codeclient_elephant.php
  htdocs/core/tpl/extrafields_list_print_fields.tpl.php
  htdocs/document.php
  htdocs/product/card.php
  htdocs/product/fournisseurs.php
  htdocs/societe/admin/societe.php
  htdocs/societe/consumption.php
  htdocs/societe/paymentmodes.php
  htdocs/ticket/list.php
Labels: PR to fix or conflict to solve, DevCamp 2021 Valence

#18975 FIX Accountancy - If deposit invoice is used, force binding in deposit accounting account to solve transaction
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/list.php
Labels: Priority Medium, PR to merge, hacktoberfest
