Repository Dolibarr/dolibarr, pull requests merged in 2021-09, with the labels that each got.

#18498 Undef vars2
  htdocs/blockedlog/admin/blockedlog_list.php
  htdocs/comm/action/peruser.php
  htdocs/core/class/html.form.class.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/projet/list.php
  htdocs/ticket/list.php
Labels: PR to fix or conflict to solve

#18446 Added function - using list of location_incoterms
  htdocs/core/ajax/locationincoterms.php
  htdocs/core/class/html.form.class.php
Labels: PR to fix or conflict to solve

#18598 Increase the width of column for General Set-ups - Update dolibarr.php
  htdocs/admin/system/dolibarr.php
Labels: Discussion

#18648 NEW : mass action delete, no more break if at least one object has child
  htdocs/core/actions_massactions.inc.php
  htdocs/core/class/commonobject.class.php
  htdocs/langs/en_US/errors.lang
  htdocs/langs/fr_FR/errors.lang
Labels: Discussion

#18637 FIX multicompany transverse mode compatibility
  htdocs/comm/action/peruser.php
  htdocs/user/class/user.class.php
Labels: Discussion

#18661 Fix #18660 : fix rights of supplier order with API
  htdocs/fourn/class/api_supplier_orders.class.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#18624 Close #18584 : Code enhancement of MO
  htdocs/langs/en_US/mrp.lang
  htdocs/langs/fr_FR/mrp.lang
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_production.php
Labels: Discussion

#18509 NEW IHM - Include new options to manage dashboard
  htdocs/admin/ihm.php
  htdocs/core/lib/admin.lib.php
  htdocs/index.php
  htdocs/langs/en_US/admin.lang
Labels: Discussion

#18628 FIX #18627 REST API: Allow users with self read / modify rights to get own info
  htdocs/user/class/api_users.class.php
Labels: PR to fix or conflict to solve

#18672 NEW Survey - Add a clickable link in email send
  htdocs/public/opensurvey/studs.php
Labels: PR to merge

#18737 FIX: task time: can't filter by user with pgsql + show error message
  htdocs/projet/tasks/time.php
Labels: PR to fix or conflict to solve

#18641 14.0 fix takepos payment methods
  htdocs/takepos/index.php
  htdocs/takepos/invoice.php
  htdocs/takepos/pay.php
Labels: Discussion

#18629 Fix : GET extrafields on API "get events list" requests
  htdocs/comm/action/class/actioncomm.class.php
Labels: PR to fix or conflict to solve

#18608 fix entity knowledgerecord
  htdocs/knowledgemanagement/class/knowledgerecord.class.php
Labels: PR to fix or conflict to solve

#18761 Fix: #18760 bad rights admin if advanced perms
  htdocs/main.inc.php
Labels: PR to merge (after fix suggested)

#18182 NEW : field and behavior in product object
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
  htdocs/core/tpl/objectline_create.tpl.php
  htdocs/core/tpl/objectline_edit.tpl.php
  htdocs/core/tpl/objectline_view.tpl.php
  htdocs/install/mysql/migration/14.0.0-15.0.0.sql
  htdocs/install/mysql/tables/llx_product.sql
  htdocs/langs/en_US/products.lang
  htdocs/langs/fr_FR/products.lang
  htdocs/product/ajax/products.php
  htdocs/product/card.php
  htdocs/product/class/product.class.php
Labels: Discussion, PR to merge (after fix suggested)

#18771 Allow to edit the header of receipt by using HTML
  htdocs/takepos/admin/receipt.php
  htdocs/takepos/receipt.php
Labels: Discussion

#18778 Fix : KM articles in public/ticket/create_ticket.php
  htdocs/core/ajax/fetchKnowledgeRecord.php
  htdocs/core/class/html.formticket.class.php
Labels: PR to merge (after fix suggested)

#18702 Close #18692 : Possibility to move directories in ecm
  htdocs/ecm/class/htmlecm.form.class.php
  htdocs/ecm/dir_card.php
  htdocs/langs/en_US/ecm.lang
  htdocs/langs/fr_FR/ecm.lang
Labels: PR to merge (after fix suggested)

#18810 FIX Accountancy - Missing specific filename for export on format FEC2
  htdocs/accountancy/tpl/export_journal.tpl.php
Labels: PR to merge

#18723 Explicit date_creation instead of date
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: PR to fix or conflict to solve

#18823 NEW API list of staff units
  htdocs/api/class/api_setup.class.php
Labels: PR to fix or conflict to solve

#17819 NEW : rewrite bind accountancy code finding on sales invoice
  htdocs/accountancy/admin/account.php
  htdocs/accountancy/class/accountingaccount.class.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/list.php
Labels: Priority Top Strategic, PR to merge (after fix suggested)

#18554 NEW : Allow drag and drop on kits
  htdocs/core/ajax/row.php
  htdocs/core/class/commonobject.class.php
  htdocs/install/mysql/migration/14.0.0-15.0.0.sql
  htdocs/install/mysql/tables/llx_product_association.sql
  htdocs/langs/en_US/products.lang
  htdocs/langs/fr_FR/products.lang
  htdocs/product/class/product.class.php
  htdocs/product/composition/card.php
Labels: PR to fix or conflict to solve
