Repository Dolibarr/dolibarr, pull requests merged in 2021-12, with the labels that each got.

#19558 Remove illegal characters in SEPA XML
  htdocs/compta/prelevement/class/bonprelevement.class.php
Labels: Discussion

#19553 Add hookmanager in function pdf_pagefoot of pdf.lib.php
  htdocs/core/lib/pdf.lib.php
Labels: PR to fix or conflict to solve

#19396 fix: #ZENDSI fix margin calc with credit note
  htdocs/accountancy/customer/index.php
Labels: PR to merge

#18167 FIX: line extrafields are inoperative in dispatch cards even when they exist
  htdocs/reception/card.php
Labels: Discussion

#19492 Fix: Import don't work if extrafield is separator
  htdocs/core/modules/modCommande.class.php
  htdocs/core/modules/modFournisseur.class.php
  htdocs/core/modules/modProduct.class.php
  htdocs/core/modules/modPropale.class.php
Labels: PR to merge (after fix suggested)
