Repository Dolibarr/dolibarr, pull requests merged in 2021-07, with the labels that each got.

#18058 add labels and export only latest prices
  htdocs/core/modules/modProduct.class.php
Labels: PR to merge (after fix suggested)

#18092 Fix php8 warning
  htdocs/bom/bom_list.php
  htdocs/compta/cashcontrol/cashcontrol_list.php
  htdocs/core/tpl/commonfields_add.tpl.php
  htdocs/core/tpl/commonfields_edit.tpl.php
  htdocs/eventorganization/conferenceorbooth_list.php
  htdocs/eventorganization/conferenceorboothattendee_list.php
  htdocs/knowledgemanagement/knowledgerecord_list.php
  htdocs/main.inc.php
  htdocs/modulebuilder/template/myobject_list.php
  htdocs/mrp/mo_list.php
  htdocs/partnership/partnership_list.php
  htdocs/product/inventory/card.php
  htdocs/product/inventory/inventory.php
  htdocs/product/inventory/list.php
  htdocs/product/stock/list.php
  htdocs/projet/class/project.class.php
  htdocs/projet/class/task.class.php
  htdocs/projet/list.php
  htdocs/salaries/list.php
  htdocs/salaries/payments.php
  htdocs/supplier_proposal/class/supplier_proposal.class.php
  htdocs/user/class/user.class.php
Labels: Discussion

#18089 add filter
  htdocs/commande/list.php
Labels: Discussion

#18087 New : Add js confirm modal option to BTN created with dolGetButtonAction
  htdocs/core/js/lib_foot.js.php
  htdocs/core/lib/functions.lib.php
  htdocs/langs/en_US/other.lang
  htdocs/langs/fr_FR/other.lang
Labels: Discussion

#18019 NEW: make it easier to set the `keyword`, `keywords` and `description` attributes of an ecm file object
  htdocs/core/lib/files.lib.php
Labels: Discussion

#18125 NEW add hookmanager on note pages
  htdocs/adherents/note.php
  htdocs/asset/note.php
  htdocs/bom/bom_note.php
  htdocs/comm/propal/note.php
  htdocs/commande/card.php
  htdocs/commande/note.php
  htdocs/compta/facture/note.php
  htdocs/contact/note.php
  htdocs/contrat/note.php
  htdocs/don/note.php
  htdocs/eventorganization/conferenceorboothattendee_note.php
  htdocs/expedition/note.php
  htdocs/expensereport/note.php
  htdocs/fichinter/note.php
  htdocs/fourn/commande/note.php
  htdocs/fourn/facture/note.php
  htdocs/knowledgemanagement/knowledgerecord_note.php
  htdocs/loan/note.php
  htdocs/modulebuilder/template/myobject_note.php
  htdocs/mrp/mo_note.php
  htdocs/partnership/partnership_note.php
  htdocs/product/note.php
  htdocs/projet/note.php
  htdocs/projet/tasks/note.php
  htdocs/reception/note.php
  htdocs/recruitment/recruitmentcandidature_note.php
  htdocs/recruitment/recruitmentjobposition_note.php
  htdocs/resource/note.php
  htdocs/societe/note.php
  htdocs/supplier_proposal/note.php
  htdocs/workstation/workstation_note.php
Labels: PR to merge (after fix suggested)

#18128 add: ticket categories functions
  htdocs/categories/class/categorie.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/class/html.formticket.class.php
  htdocs/core/modules/modTicket.class.php
  htdocs/ticket/class/ticket.class.php
Labels: PR to merge (after fix suggested)

#17801 NEW : Auto create invoice for payment done on an order with online payment link of order
  htdocs/public/payment/paymentok.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#17883 NEW: holiday: handle monthly balance updates with cronjob
  htdocs/core/modules/modHoliday.class.php
  htdocs/holiday/class/holiday.class.php
  htdocs/langs/en_US/holiday.lang
  test/phpunit/HolidayTest.php
Labels: PR to fix or conflict to solve

#18297 NEW add hook 'menuLeftMenuItems' to filter the leftmenu items
  htdocs/core/class/hookmanager.class.php
  htdocs/core/menus/standard/eldy.lib.php
Labels: PR to fix or conflict to solve

#18248 NEW add agenda auto creation on supplier_order cancellation
  htdocs/core/triggers/interface_50_modAgenda_ActionsAuto.class.php
  htdocs/fourn/commande/card.php
  htdocs/install/mysql/data/llx_c_action_trigger.sql
  htdocs/install/mysql/migration/14.0.0-15.0.0.sql
Labels: PR to fix or conflict to solve
