Repository Dolibarr/dolibarr, pull requests merged in 2021-04, with the labels that each got.

#16996 llx_product batch_mask definition
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_product.sql
Labels: PR to fix or conflict to solve

#17065 Debug feature to import stock movement from csv file
  htdocs/langs/en_US/stocks.lang
  htdocs/product/stock/massstockmove.php
Labels: PR to fix or conflict to solve

#17096 Close #17073 : Add of select line for mass deletion of chart of account lines
  htdocs/accountancy/admin/account.php
Labels: Discussion

#16376 Code enhanced - Standardize field name #14697
  ChangeLog
  htdocs/comm/card.php
  htdocs/compta/accounting-files.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/invoicetemplate_list.php
  htdocs/compta/facture/list.php
  htdocs/compta/index.php
  htdocs/compta/resultat/clientfourn.php
  htdocs/compta/resultat/index.php
  htdocs/compta/stats/cabyuser.php
  htdocs/compta/stats/casoc.php
  htdocs/compta/stats/index.php
  htdocs/compta/tva/class/tva.class.php
  htdocs/core/boxes/box_factures.php
  htdocs/core/boxes/box_factures_imp.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/modules/modApi.class.php
  htdocs/core/modules/modFacture.class.php
  htdocs/core/modules/modGravatar.class.php
  htdocs/core/modules/modHoliday.class.php
  htdocs/core/modules/modMultiCurrency.class.php
  htdocs/core/modules/modPaybox.class.php
  htdocs/core/modules/modPaypal.class.php
  htdocs/fourn/facture/list.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_facture.sql
  htdocs/install/mysql/tables/llx_facture_rec.sql
  htdocs/intracommreport/class/intracommreport.class.php
  htdocs/margin/customerMargins.php
  htdocs/margin/productMargins.php
  htdocs/margin/tabs/productMargins.php
  htdocs/margin/tabs/thirdpartyMargins.php
  htdocs/recruitment/recruitmentindex.php
  test/phpunit/ExportTest.php
Labels: PR to merge

#17139 FIX: Fix when add or modify ressources on events with duplicate entries
  htdocs/comm/action/class/actioncomm.class.php
Labels: Discussion

#17148 Fix empty string WEBSITE_OTHERLANG (better fix)
  htdocs/core/lib/website2.lib.php
  htdocs/website/class/website.class.php
  htdocs/website/index.php
Labels: Discussion

#17159 Close #17145 : add link to autofill with expected qty
  htdocs/langs/en_US/stocks.lang
  htdocs/product/inventory/inventory.php
Labels: PR to fix or conflict to solve

#17121 NEW Add support for Friday as a holiday
  htdocs/core/lib/date.lib.php
Labels: PR to fix or conflict to solve

#17205 new: working on conference or booth object and event type #FoundationFunding
  htdocs/admin/eventorganization.php
  htdocs/core/lib/project.lib.php
  htdocs/core/tpl/commonfields_view.tpl.php
  htdocs/eventorganization/class/conferenceorbooth.class.php
  htdocs/eventorganization/class/conferenceorboothattendee.class.php
  htdocs/eventorganization/conferenceorbooth_card.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_eventorganization_conferenceorboothattendee.key.sql
  htdocs/install/mysql/tables/llx_eventorganization_conferenceorboothattendee.sql
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/eventorganization.lang
  htdocs/public/eventorganization/attendee_subscription.php
Labels: PR to fix or conflict to solve

#17222 FIX Write right on document
  htdocs/adherents/document.php
  htdocs/asset/document.php
  htdocs/bom/bom_document.php
  htdocs/comm/action/document.php
  htdocs/comm/propal/document.php
  htdocs/commande/document.php
  htdocs/compta/bank/account_statement_document.php
  htdocs/compta/bank/document.php
  htdocs/compta/bank/various_payment/document.php
  htdocs/compta/deplacement/document.php
  htdocs/compta/facture/document.php
  htdocs/compta/sociales/document.php
  htdocs/compta/tva/document.php
  htdocs/contrat/document.php
  htdocs/don/document.php
  htdocs/expedition/document.php
  htdocs/expensereport/document.php
  htdocs/fichinter/document.php
  htdocs/fourn/commande/document.php
  htdocs/holiday/document.php
  htdocs/loan/document.php
  htdocs/modulebuilder/template/myobject_document.php
  htdocs/mrp/mo_document.php
  htdocs/product/document.php
  htdocs/product/stock/productlot_document.php
  htdocs/projet/document.php
  htdocs/projet/tasks/document.php
  htdocs/recruitment/recruitmentcandidature_document.php
  htdocs/recruitment/recruitmentjobposition_document.php
  htdocs/resource/document.php
  htdocs/salaries/document.php
  htdocs/societe/document.php
  htdocs/supplier_proposal/document.php
  htdocs/ticket/document.php
  htdocs/user/document.php
Labels: PR to merge

#17097 Create Partnership Module
  htdocs/core/modules/modPartnership.class.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/langs/en_US/partnership.lang
  htdocs/partnership/COPYING
  htdocs/partnership/ChangeLog.md
  htdocs/partnership/README.md
  htdocs/partnership/admin/about.php
  htdocs/partnership/admin/partnership_extrafields.php
  htdocs/partnership/admin/setup.php
  htdocs/partnership/class/partnership.class.php
  htdocs/partnership/class/partnershiputils.class.php
  htdocs/partnership/core/modules/partnership/mod_partnership_advanced.php
  htdocs/partnership/core/modules/partnership/mod_partnership_standard.php
  htdocs/partnership/core/modules/partnership/modules_partnership.php
  htdocs/partnership/lib/partnership.lib.php
  htdocs/partnership/modulebuilder.txt
  htdocs/partnership/partnership_agenda.php
  htdocs/partnership/partnership_card.php
  htdocs/partnership/partnership_contact.php
  htdocs/partnership/partnership_document.php
  htdocs/partnership/partnership_list.php
  htdocs/partnership/partnership_note.php
  htdocs/partnership/partnershipindex.php
Labels: PR to fix or conflict to solve

#17166 Product masks
  htdocs/core/modules/product_batch/mod_lot_advanced.php
  htdocs/core/modules/product_batch/mod_sn_advanced.php
  htdocs/langs/en_US/productbatch.lang
  htdocs/langs/fr_FR/productbatch.lang
  htdocs/product/admin/product_lot.php
Labels: PR to fix or conflict to solve

#17103 Fix compatibility phpv8
  htdocs/admin/company.php
  htdocs/admin/delais.php
  htdocs/admin/mails.php
  htdocs/core/boxes/box_dolibarr_state_board.php
  htdocs/core/lib/admin.lib.php
  htdocs/core/modules/modDataPolicy.class.php
Labels: PR to fix or conflict to solve

#17255 Compatibility phpv8
  htdocs/admin/mails_senderprofile_list.php
  htdocs/admin/mails_templates.php
  htdocs/core/tpl/list_print_total.tpl.php
Labels: PR to fix or conflict to solve

#17248 Batch mask product
  htdocs/langs/en_US/productbatch.lang
  htdocs/langs/fr_FR/productbatch.lang
  htdocs/product/card.php
  htdocs/product/class/product.class.php
Labels: PR to merge

#17295 FIX : type link extrafield case for advanced target emailing
  htdocs/comm/mailing/class/advtargetemailing.class.php
Labels: PR to fix or conflict to solve

#17409 Update supplier_proposal.class.php
  htdocs/supplier_proposal/class/supplier_proposal.class.php
Labels: PR to fix or conflict to solve

#17400 FIX Supplier invoices (deposit, multicurrency in lines)
  htdocs/core/class/discount.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/fourn/class/paiementfourn.class.php
  htdocs/fourn/facture/card.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_facture_fourn_det.key.sql
  htdocs/install/mysql/tables/llx_facture_fourn_det.sql
Labels: PR to fix or conflict to solve, PR to merge

#17379 FIX : Add function price2num for rounding values in productAlertStock…
  htdocs/core/boxes/box_produits_alerte_stock.php
Labels: Discussion

#17366 Fix #17318 false renew date
  htdocs/public/payment/paymentok.php
Labels: PR to fix or conflict to solve

#17408 Fix Bug replenish + Auto Filter
  htdocs/product/stock/replenish.php
Labels: Discussion

#17405 Fix #17219 : complement of PR 17161
  htdocs/core/tpl/filemanager.tpl.php
Labels: PR to fix or conflict to solve

#17393 Close/CLOSE #17390 Products API, GET /products without variants
  htdocs/product/class/api_products.class.php
Labels: PR to fix or conflict to solve, PR to merge

#17365 Compatibility phpv8
  htdocs/admin/delais.php
  htdocs/admin/security.php
  htdocs/admin/system/dolibarr.php
  htdocs/admin/system/modules.php
Labels: PR to fix or conflict to solve

#17261 Maxi debug of societe/product per entity
  htdocs/accountancy/admin/productaccount.php
  htdocs/accountancy/customer/card.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/lines.php
  htdocs/accountancy/customer/list.php
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/accountancy/supplier/card.php
  htdocs/accountancy/supplier/index.php
  htdocs/accountancy/supplier/lines.php
  htdocs/accountancy/supplier/list.php
  htdocs/compta/journal/sellsjournal.php
  htdocs/core/modules/modFacture.class.php
  htdocs/core/modules/modProduct.class.php
  htdocs/core/modules/modService.class.php
  htdocs/product/class/product.class.php
  htdocs/product/list.php
  htdocs/societe/class/societe.class.php
Labels: PR to merge

#17260 NEW Add Mass action order validate and set to billed
  htdocs/commande/list.php
Labels: PR to fix or conflict to solve
