Repository Dolibarr/dolibarr, pull requests merged in 2021-03, with the labels that each got.

#16489 FIX: Total_ht not show in contract link element
  htdocs/core/class/html.form.class.php
  htdocs/langs/en_US/main.lang
Labels: PR to merge

#16493 FIX: Various payment - Missing fields for check transmitter & bank name
  htdocs/compta/bank/class/paymentvarious.class.php
  htdocs/compta/bank/various_payment/card.php
Labels: PR to merge

#16251 Close #16218 : new button sitemap file
  htdocs/langs/en_US/website.lang
  htdocs/website/index.php
Labels: PR to fix or conflict to solve

#16603 new: working on conference or booth object and event type #FoundationFunding
  htdocs/core/modules/modEventOrganization.class.php
  htdocs/core/triggers/interface_50_modEventOrganization_EventOrganization.class.php
Labels: Discussion

#16591 Replace gender and civility by a picto
  htdocs/adherents/card.php
  htdocs/adherents/subscription.php
  htdocs/core/class/html.form.class.php
  htdocs/user/card.php
Labels: PR to fix or conflict to solve

#16280 New:Constant MAIN_SHOW_SOCIETE2EXTERN to allow access to any thirdparty for external users
  htdocs/core/lib/security.lib.php
  htdocs/societe/card.php
Labels: Discussion, PR to fix or conflict to solve

#16648 fix php8 fatal error
  htdocs/core/lib/memory.lib.php
  htdocs/master.inc.php
Labels: Discussion

#16637 force check if newref needed if project create fail
  htdocs/projet/card.php
Labels: Discussion

#16625 new: working on conference or booth object and event type #FoundationFunding
  htdocs/comm/action/class/actioncomm.class.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/lib/project.lib.php
  htdocs/eventorganization/class/conferenceorbooth.class.php
  htdocs/eventorganization/conferenceorbooth_list.php
  htdocs/modulebuilder/template/myobject_list.php
  htdocs/projet/class/project.class.php
  htdocs/projet/contact.php
  htdocs/projet/element.php
  htdocs/projet/event.php
  htdocs/projet/tasks.php
  htdocs/projet/tasks/time.php
  htdocs/societe/class/societe.class.php
Labels: Discussion

#16673 fix php8 warnings
  htdocs/fichinter/card-rec.php
Labels: Discussion

#16307 NEW: VAT report - Optimisation & collapse by rate
  htdocs/compta/tva/index.php
  htdocs/compta/tva/quadri_detail.php
  htdocs/core/lib/tax.lib.php
  htdocs/langs/en_US/compta.lang
Labels: PR to merge

#16695 Update hook_document.php
  htdocs/zapier/hook_document.php
Labels: Discussion

#16289 fix:Handle constant MAIN_SHOW_SOCIETE2EXTERN in checkUserAccessToObject
  htdocs/core/lib/security.lib.php
Labels: PR to fix or conflict to solve

#16639 Update list.php wrong number presentation in stock
  htdocs/product/list.php
Labels: Discussion

#16776 fix php8 warnings
  htdocs/core/boxes/box_graph_nb_tickets_type.php
  htdocs/core/boxes/box_graph_ticket_by_severity.php
Labels: Discussion

#16818 Code translation
  htdocs/adherents/index.php
Labels: Discussion

#16791 FIX: fix checkbox displayed according to module project setup parameters - work in progress
  htdocs/projet/card.php
  htdocs/projet/contact.php
  htdocs/projet/element.php
  htdocs/projet/tasks.php
  htdocs/projet/tasks/comment.php
  htdocs/projet/tasks/contact.php
  htdocs/projet/tasks/document.php
  htdocs/projet/tasks/note.php
  htdocs/projet/tasks/task.php
  htdocs/projet/tasks/time.php
Labels: Discussion

#16845 FIX avoid php8 warning with multicompany
  htdocs/core/ajax/pingresult.php
  htdocs/core/boxes/box_services_contracts.php
  htdocs/main.inc.php
Labels: PR to fix or conflict to solve

#16612 FIX : Update pencil
  htdocs/compta/sociales/card.php
Labels: PR to merge

#16894 Fix #16893 #16897 V13 picto UpToDate change to Unpaid sometimes
  htdocs/adherents/index.php
Labels: Discussion

#16933 Fix #16794 V13 order by status instead of statut
  htdocs/core/class/html.formother.class.php
Labels: Discussion

#16620 Define Masks for Batch Products Equipments
  htdocs/core/lib/product.lib.php
  htdocs/core/modules/modProductBatch.class.php
  htdocs/core/modules/product_batch/mod_lot_advanced.php
  htdocs/core/modules/product_batch/mod_lot_free.php
  htdocs/core/modules/product_batch/mod_lot_standard.php
  htdocs/core/modules/product_batch/mod_sn_advanced.php
  htdocs/core/modules/product_batch/mod_sn_free.php
  htdocs/core/modules/product_batch/mod_sn_standard.php
  htdocs/core/modules/product_batch/modules_product_batch.class.php
  htdocs/langs/en_US/productbatch.lang
  htdocs/langs/fr_FR/productbatch.lang
  htdocs/product/admin/product_lot.php
Labels: PR to merge

#16956 FIX : old query using tva object for payments list
  htdocs/compta/charges/index.php
Labels: PR not qualified

#16932 NEW Add native compression in rest apis
  htdocs/api/index.php
Labels: PR to fix or conflict to solve

#16929 NEW: Add company info in dropdown login menu
  htdocs/core/lib/functions.lib.php
  htdocs/langs/en_US/companies.lang
  htdocs/langs/en_US/main.lang
  htdocs/main.inc.php
  htdocs/theme/eldy/dropdown.inc.php
  htdocs/theme/md/dropdown.inc.php
Labels: PR to merge

#16930 NEW: Add a sub table to manage accountancy on product/company
  htdocs/accountancy/admin/productaccount.php
  htdocs/accountancy/customer/card.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/lines.php
  htdocs/accountancy/customer/list.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/accountancy/supplier/list.php
  htdocs/compta/journal/sellsjournal.php
  htdocs/core/modules/modFacture.class.php
  htdocs/core/modules/modProduct.class.php
  htdocs/core/modules/modService.class.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_product_perentity.key.sql
  htdocs/install/mysql/tables/llx_product_perentity.sql
  htdocs/install/mysql/tables/llx_societe_perentity.key.sql
  htdocs/install/mysql/tables/llx_societe_perentity.sql
  htdocs/product/class/product.class.php
  htdocs/product/list.php
Labels: PR to merge

#16554 Add standard fields property and fetchAll method to ProductFournisseur class
  htdocs/product/class/productfournisseurprice.class.php
Labels: PR to fix or conflict to solve

#16990 Close #15830 Add setup option ADHERENT_DEFAULT_CREATE_THIRDPARTY
  htdocs/adherents/card.php
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve

#16980 NEW date and user signature on proposal (Issue 16062)
  htdocs/comm/propal/card.php
  htdocs/comm/propal/class/propal.class.php
  htdocs/core/lib/functions2.lib.php
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_propal.key.sql
  htdocs/install/mysql/tables/llx_propal.sql
  htdocs/langs/fr_FR/main.lang
  htdocs/langs/fr_FR/other.lang
Labels: PR to fix or conflict to solve, PR to merge

#17018 FIX: Show Ref.Supplier in LinkToObjectBlock
  htdocs/core/class/html.form.class.php
Labels: PR to fix or conflict to solve

#17053 NEW: Accountancy - Add FEC import
  htdocs/accountancy/class/accountancyimport.class.php
  htdocs/core/modules/modAccounting.class.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR to merge

#16483 NEW Add experimental repair script to switch to dynamic row format and utf8mb4 encoding
  htdocs/core/class/utils.class.php
  htdocs/install/repair.php
Labels: Discussion
