Repository Dolibarr/dolibarr, pull requests merged in 2021-05, with the labels that each got.

#17415 Close #17271 : Replacement of 2 graphes in /compta/index.php
  htdocs/compta/index.php
  htdocs/core/lib/invoice.lib.php
  htdocs/langs/en_US/compta.lang
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#17470 Create EORI.info
  dev/resources/prof-id/EORI.info
Labels: PR to fix or conflict to solve

#17469 Fix show table of pdf payments repports in file order
  htdocs/compta/paiement/rapport.php
Labels: Discussion

#17404 New Add option for doctemplate
  htdocs/admin/pdf.php
  htdocs/admin/pdf_adherent.php
  htdocs/admin/pdf_contrat.php
  htdocs/admin/pdf_expensereport.php
  htdocs/admin/pdf_holiday.php
  htdocs/admin/pdf_intervention.php
  htdocs/admin/pdf_invoice.php
  htdocs/admin/pdf_order.php
  htdocs/admin/pdf_project.php
  htdocs/admin/pdf_proposal.php
  htdocs/admin/pdf_reception.php
  htdocs/admin/pdf_recruitment.php
  htdocs/admin/pdf_shipment.php
  htdocs/admin/pdf_stock.php
  htdocs/admin/pdf_supplierinvoice.php
  htdocs/admin/pdf_supplierorder.php
  htdocs/admin/pdf_supplierproposal.php
  htdocs/admin/pdf_ticket.php
  htdocs/core/lib/pdf.lib.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#17314 NEW mcurrency rate
  htdocs/multicurrency/multicurrency_rate.php
Labels: PR to fix or conflict to solve

#17401 New #14826 Multicompany PMP per entity
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_product_perentity.sql
  htdocs/product/class/product.class.php
  htdocs/product/stock/card.php
  htdocs/product/stock/class/entrepot.class.php
  htdocs/product/stock/list.php
Labels: PR to fix or conflict to solve

#17382 new: working on conference or booth object and event type #FoundationFunding
  htdocs/admin/eventorganization.php
  htdocs/core/class/commonobject.class.php
  htdocs/eventorganization/class/conferenceorbooth.class.php
  htdocs/eventorganization/conferenceorbooth_card.php
  htdocs/eventorganization/conferenceorbooth_list.php
  htdocs/install/mysql/data/llx_c_email_templates.sql
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/langs/en_US/eventorganization.lang
  htdocs/modulebuilder/template/admin/setup.php
  htdocs/public/eventorganization/attendee_subscription.php
  htdocs/public/eventorganization/subscriptionok.php
  htdocs/public/payment/newpayment.php
  htdocs/public/payment/paymentok.php
  htdocs/public/project/index.php
Labels: PR to fix or conflict to solve

#17444 Fix #17361 : change of llx_export_model type to varchar(64)
  htdocs/install/mysql/migration/12.0.0-13.0.0.sql
  htdocs/install/mysql/tables/llx_export_model.sql
Labels: PR to merge (after fix suggested)

#17301 NEW More permission in TakePOS (Can edit added line, can modify once order sent to kitchen)
  htdocs/core/modules/modTakePos.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/takepos/invoice.php
Labels: Discussion, PR to fix or conflict to solve

#17358 Batch status dict
  htdocs/admin/dict.php
  htdocs/install/mysql/data/llx_c_productbatch_qcstatus.sql
  htdocs/install/mysql/migration/13.0.0-14.0.0.sql
  htdocs/install/mysql/tables/llx_c_productbatch_qcstatus.key.sql
  htdocs/install/mysql/tables/llx_c_productbatch_qcstatus.sql
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/productbatch.lang
  htdocs/langs/fr_FR/admin.lang
  htdocs/langs/fr_FR/productbatch.lang
Labels: PR to fix or conflict to solve

#17497 Fix #17491 : date extrafield filter works well now
  htdocs/core/tpl/extrafields_list_search_sql.tpl.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#17512 Stock product card traceability fields
  htdocs/langs/en_US/productbatch.lang
  htdocs/langs/fr_FR/productbatch.lang
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/stock/class/productlot.class.php
  htdocs/product/stock/productlot_card.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#17528 Add phone and address in popup Thirdparty info
  htdocs/societe/class/societe.class.php
Labels: Discussion

#17489 Fix #17475 : Add of List-Unsubscribe in mass emailing
  htdocs/comm/mailing/card.php
  htdocs/core/lib/functions.lib.php
  scripts/emailings/mailing-send.php
Labels: PR to merge (after fix suggested)

#17630 Fix: user rest api rights
  htdocs/user/class/api_users.class.php
Labels: Bug need more information, Works for me / Can't reproduce

#17385 Compatibility phpv8
  htdocs/admin/mails.php
  htdocs/admin/system/filecheck.php
  htdocs/admin/tools/dolibarr_export.php
  htdocs/admin/tools/listevents.php
  htdocs/core/lib/admin.lib.php
Labels: PR to fix or conflict to solve

#17618 Fix add/del user to group modifies LDAP group
  htdocs/core/triggers/interface_50_modLdap_Ldapsynchro.class.php
Labels: PR to fix or conflict to solve

#17642 Compatibility phpv8
  htdocs/admin/system/modules.php
  htdocs/admin/tools/listevents.php
  htdocs/main.inc.php
Labels: PR to fix or conflict to solve
