Repository Dolibarr/dolibarr, pull requests merged in 2022-11, with the labels that each got.

#22600 FIX - advanced permission to read price stock card
  htdocs/product/stock/product.php
Labels: PR to fix or conflict to solve

#22688 FIX: check if contact is active before creating associated ticket
  htdocs/public/ticket/create_ticket.php
Labels: Discussion

#22599 NEW #22594: can chose if VAT ID is unique or not for third parties
  htdocs/societe/admin/societe.php
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve

#22801 New : expand/collapse user permission module
  htdocs/langs/en_US/users.lang
  htdocs/user/perms.php
Labels: Discussion

#22812 Fix issue Scrutinizer in html cerfafr.modules.php
  htdocs/core/modules/dons/html_cerfafr.modules.php
Labels: PR to fix or conflict to solve

#22814 Fix issue Scrutinizer
  htdocs/core/modules/product/doc/doc_generic_product_odt.modules.php
Labels: PR to fix or conflict to solve

#22803 Fix issue scrutinizer htdocs/core/lib/functionsnumtoword.lib.php
  htdocs/core/lib/functionsnumtoword.lib.php
Labels: PR to fix or conflict to solve

#22815 Fix issue Scrutinizer doc_project_odt
  htdocs/core/modules/project/doc/doc_generic_project_odt.modules.php
Labels: PR to fix or conflict to solve

#22810 Fix issue Scrutinizer in modules_barcode.class.php
  htdocs/core/modules/barcode/modules_barcode.class.php
Labels: PR to fix or conflict to solve

#22820 Fix scrutinize supplier_proposal
  htdocs/core/modules/supplier_proposal/mod_supplier_proposal_saphir.php
Labels: PR to fix or conflict to solve

#22817 Fix issue Scrutinizer in core/modules/project/mod_project_universal.php
  htdocs/core/modules/project/mod_project_universal.php
Labels: PR to fix or conflict to solve

#22816 Fix issue scrutinizer in modules_project
  htdocs/core/modules/project/modules_project.php
Labels: PR to fix or conflict to solve

#22806 FIX Accountancy - When origin invoice is deposit, suggest specific account on credit note
  htdocs/accountancy/class/accountingaccount.class.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/list.php
  htdocs/accountancy/supplier/index.php
  htdocs/accountancy/supplier/list.php
Labels: PR to merge

#22799 Fix issue variables whithread and errors
  htdocs/core/class/html.formticket.class.php
Labels: Discussion

#22881 Fix issue #22846
  htdocs/core/tpl/notes.tpl.php
  htdocs/product/note.php
Labels: Discussion

#22842 Fix issue in htdocs/don/payment/payment.php
  htdocs/don/payment/payment.php
Labels: Discussion

#22885 BUG FIXED #22883
  htdocs/compta/resultat/clientfourn.php
Labels: Discussion

#22954 Fix expedition stats abstract method
  htdocs/expedition/class/expeditionstats.class.php
Labels: DevCamp 2022 Nantes

#22958 FIX: Asset - Compatibility SQL, typo, language key, ChangeLog
  ChangeLog
  htdocs/asset/card.php
  htdocs/asset/class/asset.class.php
  htdocs/langs/en_US/main.lang
Labels: DevCamp 2022 Nantes

#22832 NEW - Shipping address to invoice
  htdocs/admin/facture.php
  htdocs/admin/pdf_other.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/facture/mod_facture_mercure.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/bills.lang
Labels: Priority - High / Blocking, PR to fix or conflict to solve

#22680 FIX: Fix the position of the verification condition of the test field in case of multi entities
  htdocs/public/cron/cron_run_jobs_by_url.php
  scripts/cron/cron_run_jobs.php
Labels: Discussion

#22689 NEW Make option PDF_INCLUDE_ALIAS_IN_THIRDPARTY_NAME visible
  htdocs/admin/pdf.php
  htdocs/core/lib/pdf.lib.php
  htdocs/langs/fr_FR/admin.lang
Labels: PR to fix or conflict to solve

#22889 NEW add footer hook accountancy
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
Labels: PR to fix or conflict to solve

#22978 FIX : Bankaccounts API fetch with 'id' and 'socid'
  htdocs/societe/class/companybankaccount.class.php
Labels: DevCamp 2022 Nantes

#22955 fix : dolibarr_changes to match last PR
  dev/dolibarr_changes.txt
Labels: DevCamp 2022 Nantes

#23009 Fix count in lists
  htdocs/adherents/list.php
  htdocs/asset/list.php
  htdocs/bom/bom_list.php
  htdocs/bookmarks/list.php
  htdocs/comm/action/list.php
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/bank/list.php
  htdocs/compta/bank/various_payment/list.php
  htdocs/compta/facture/list.php
  htdocs/compta/paiement/cheque/list.php
  htdocs/compta/paiement/list.php
  htdocs/compta/prelevement/list.php
  htdocs/compta/prelevement/orders_list.php
  htdocs/compta/sociales/list.php
  htdocs/compta/tva/list.php
  htdocs/contact/list.php
  htdocs/expedition/list.php
  htdocs/expensereport/list.php
  htdocs/fichinter/list.php
  htdocs/fourn/commande/list.php
  htdocs/fourn/facture/list.php
  htdocs/fourn/product/list.php
  htdocs/holiday/list.php
  htdocs/loan/list.php
  htdocs/modulebuilder/template/myobject_list.php
  htdocs/mrp/mo_list.php
  htdocs/product/inventory/list.php
  htdocs/product/list.php
  htdocs/product/stock/movement_list.php
  htdocs/reception/list.php
  htdocs/societe/list.php
  htdocs/ticket/list.php
  htdocs/user/list.php
Labels: DevCamp 2022 Nantes

#22996 FIX : Documents API inconsistency
  htdocs/api/class/api_documents.class.php
Labels: DevCamp 2022 Nantes

#23003 fix #22766: better API response HTTP code
  htdocs/adherents/class/api_members.class.php
  htdocs/adherents/class/api_memberstypes.class.php
  htdocs/adherents/class/api_subscriptions.class.php
  htdocs/product/class/api_products.class.php
  htdocs/societe/class/api_thirdparties.class.php
  htdocs/user/class/api_users.class.php
Labels: DevCamp 2022 Nantes

#23006 fix #23005: change lire to creer (rights)
  htdocs/projet/tasks/time.php
Labels: DevCamp 2022 Nantes

#22995 Fix #22935 parse_str need 2 arguments
  build/generate_filelist_xml.php
Labels: DevCamp 2022 Nantes

#22997 Fix #21357
  htdocs/fourn/facture/card.php
Labels: DevCamp 2022 Nantes

#22994 Fix #20685 User Id not transmitted on Api addTimeSpent
  htdocs/projet/class/api_tasks.class.php
Labels: DevCamp 2022 Nantes

#23007 FIX Negative consumption in MO creates additional goods issue #21343
  htdocs/mrp/mo_production.php
Labels: DevCamp 2022 Nantes

#23004 FIX: #22509 default value on integer fields don't retrieve by setSaveQuery
  htdocs/core/class/commonobject.class.php
Labels: DevCamp 2022 Nantes

#23000 Fix #20533 Dispatch Tab Quantity
  htdocs/core/lib/fourn.lib.php
Labels: DevCamp 2022 Nantes

#23017 Fix : php 8.1 warnings
  htdocs/comm/action/card.php
  htdocs/compta/bank/bankentries_list.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/core/lib/modulebuilder.lib.php
  htdocs/hrm/skill_card.php
  htdocs/modulebuilder/index.php
  htdocs/reception/card.php
  htdocs/stripe/charge.php
Labels: DevCamp 2022 Nantes

#22981 Fix #19789 Visibility of private contacts
  htdocs/contact/card.php
  htdocs/core/lib/company.lib.php
Labels: PR to fix or conflict to solve, DevCamp 2022 Nantes

#22963 NEW Filter on task time
  htdocs/projet/tasks/time.php
Labels: PR postponed

#23020 NEW : HRM module as STABLE
  htdocs/core/modules/modHRM.class.php
Labels: DevCamp 2022 Nantes

#23021 NEW : StockTransfer module as Experimental
  htdocs/core/modules/modStockTransfer.class.php
Labels: DevCamp 2022 Nantes

#23025 Fix issue #23023
  htdocs/admin/fckeditor.php
Labels: PR to fix or conflict to solve

#23016 FIX product_type 9
  htdocs/adherents/class/api_members.class.php
  htdocs/adherents/class/api_memberstypes.class.php
  htdocs/adherents/class/api_subscriptions.class.php
  htdocs/api/class/api_documents.class.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/delivery/class/delivery.class.php
  htdocs/expensereport/class/expensereport.class.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/product/class/api_products.class.php
  htdocs/societe/class/api_thirdparties.class.php
  htdocs/user/class/api_users.class.php
Labels: Bug, DevCamp 2022 Nantes
