Repository Dolibarr/dolibarr, pull requests merged in 2022-04, with the labels that each got.

#20498 Avoid grouping lines with ordered lines
  htdocs/takepos/invoice.php
Labels: PR to fix or conflict to solve

#20478 fix #20477: add online_payment_url on orders API requests
  htdocs/commande/class/api_orders.class.php
  htdocs/commande/class/commande.class.php
Labels: PR needs feedback

#20190 FIX: replace butAction to dolGetButtonAction on product card
  htdocs/product/card.php
Labels: Discussion

#20225 NEW: add a workflow to auto link contract on a ticket
  htdocs/admin/ticket.php
  htdocs/admin/workflow.php
  htdocs/contrat/class/contrat.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/class/html.formcategory.class.php
  htdocs/core/modules/modTicket.class.php
  htdocs/core/modules/modWorkflow.class.php
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/langs/en_US/interventions.lang
  htdocs/langs/en_US/ticket.lang
  htdocs/langs/en_US/workflow.lang
  htdocs/societe/class/societe.class.php
  htdocs/ticket/card.php
Labels: PR to fix or conflict to solve

#19788 FIX user actions rights when multi-company transverse mode is enabled
  htdocs/user/card.php
Labels: Discussion

#20392 Fix: ticket/workflow: automatically create ficheinter
  htdocs/admin/workflow.php
  htdocs/core/modules/modWorkflow.class.php
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
  htdocs/fichinter/class/fichinter.class.php
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/langs/en_US/interventions.lang
  htdocs/langs/en_US/workflow.lang
  htdocs/ticket/card.php
Labels: PR to merge

#20249 New employee management improvement #18434
  htdocs/core/modules/modHRM.class.php
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/install/mysql/tables/llx_user.sql
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/companies.lang
  htdocs/user/bank.php
  htdocs/user/card.php
  htdocs/user/class/user.class.php
Labels: PR to merge

#20164 NEW dol_uncompress() supports extensions (.gz, .bz2, .zstd). Only .zip was supported before.
  htdocs/core/lib/files.lib.php
Labels: PR to merge (after fix suggested)

#20541 fix: Bad dirthday displayed date (d-1) in the Bithday Widget
  htdocs/core/boxes/box_birthdays.php
  htdocs/user/card.php
  htdocs/user/class/user.class.php
Labels: Discussion

#20536 add class name on tds expensereport rule card
  htdocs/admin/expensereport_rules.php
Labels: Discussion

#20534 avoid fetch_objectlinked for each page of the document
  htdocs/core/class/commonobject.class.php
Labels: PR to fix or conflict to solve

#19997 Add options in function pdf_pagefoot of pdf.lib.php
  htdocs/core/lib/pdf.lib.php
Labels: Discussion

#19555 FIX can modify tag in thirdparty card if const enabled
  htdocs/societe/card.php
Labels: PR to merge, PR postponed

#19459 can merge products
  htdocs/bom/class/bom.class.php
  htdocs/comm/action/class/actioncomm.class.php
  htdocs/comm/propal/class/propal.class.php
  htdocs/commande/class/commande.class.php
  htdocs/compta/bank/class/account.class.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/contrat/class/contrat.class.php
  htdocs/core/class/commonobject.class.php
  htdocs/delivery/class/delivery.class.php
  htdocs/fichinter/class/fichinterrec.class.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/fourn/class/fournisseur.product.class.php
  htdocs/langs/en_US/products.lang
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/reception/class/reception.class.php
  htdocs/supplier_proposal/class/supplier_proposal.class.php
Labels: PR postponed

#17966 quickadd menu like bookmarks
  htdocs/core/class/hookmanager.class.php
  htdocs/main.inc.php
  htdocs/theme/eldy/dropdown.inc.php
Labels: PR postponed

#20523 NEW 16.0 - proposal for a prefix-based consistency mechanism for trigger names
  htdocs/core/class/commonobject.class.php
Labels: Discussion, PR to fix or conflict to solve

#19417 FIX : Supplier order stats
  htdocs/commande/stats/index.php
Labels: Discussion

#19362 NEW stripe element with more gateways
  htdocs/public/payment/newpayment.php
Labels: Discussion, PR postponed

#20564 NEW : Reverse movement product consumption
  htdocs/langs/en_US/mrp.lang
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_production.php
Labels: Discussion

#20532 FIX - Fix the adding of lines in the create invoice functions
  htdocs/compta/facture/class/facture.class.php
Labels: Discussion

#19393 New/addline with position choice develop
  htdocs/comm/propal/card.php
  htdocs/comm/propal/class/propal.class.php
  htdocs/commande/card.php
  htdocs/commande/class/commande.class.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/core/tpl/objectline_create.tpl.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
  htdocs/langs/en_US/main.lang
  htdocs/supplier_proposal/card.php
  htdocs/supplier_proposal/class/supplier_proposal.class.php
Labels: PR postponed, PR to fix or conflict to solve

#20587 FIX: holiday/leave requests: write status change emails in HTML
  htdocs/holiday/card.php
Labels: Discussion

#19518 NEW Mass action close shipment
  htdocs/expedition/list.php
Labels: PR to merge, PR postponed

#19677 NEW : Import with select boxes
  htdocs/imports/import.php
  htdocs/langs/en_US/exports.lang
  htdocs/langs/fr_FR/exports.lang
Labels: PR postponed

#20608 Fix: Direct download don't work with multicompany
  htdocs/document.php
Labels: Discussion

#20612 NEW: ModuileBuilder - Add tabs view in module builder
  htdocs/langs/en_US/modulebuilder.lang
  htdocs/modulebuilder/index.php
Labels: PR to fix or conflict to solve

#20135 New hidden conf to manage pmp on inventory
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/install/mysql/tables/llx_inventorydet-stock.sql
  htdocs/langs/en_US/products.lang
  htdocs/product/inventory/class/inventory.class.php
  htdocs/product/inventory/inventory.php
Labels: Discussion

#20483 FIX avoid warning for missing cookie samesite params (and more secure)
  htdocs/main.inc.php
Labels: Discussion

#19424 FIX: user employee tab: offset in open days messes up holiday length calculation
  htdocs/user/bank.php
Labels: Discussion

#19425 FIX: project timesheet: public holidays offset by 1 day
  htdocs/projet/activity/perday.php
  htdocs/projet/activity/perweek.php
Labels: Discussion

#20713 Fix #20712 - No more empty wrong line added in bookkeeping confirme_create
  htdocs/accountancy/bookkeeping/card.php
Labels: PR to merge

#19603 NEW : Add constant to show only the products in stock in TakePos
  htdocs/takepos/ajax/ajax.php
Labels: PR to merge, PR postponed, PR to merge (after fix suggested)
