Repository Dolibarr/dolibarr, pull requests merged in 2022-12, with the labels that each got.

#23047 Fix(scrutinizer) Info
  htdocs/loan/info.php
Labels: PR to fix or conflict to solve

#23049 Fix(scrutinizer) Contact
  htdocs/resource/contact.php
Labels: PR to fix or conflict to solve

#23042 fix issue #23027
  htdocs/install/mysql/migration/16.0.0-17.0.0.sql
  htdocs/install/mysql/tables/llx_opensurvey_user_studs-opensurvey.sql
  htdocs/opensurvey/wizard/choix_date.php
Labels: PR to fix or conflict to solve

#23043 Fix #22494 Bad error message and trans missing (radio button)
  htdocs/core/class/extrafields.class.php
Labels: PR to fix or conflict to solve

#22819 FIX: GetNextValue() adding regexsql() function
  htdocs/core/db/DoliDB.class.php
  htdocs/core/db/pgsql.class.php
  htdocs/core/lib/functions2.lib.php
Labels: PR to fix or conflict to solve

#23132 FIX|Fix[#23117]
  htdocs/core/actions_massactions.inc.php
Labels: Discussion

#23133 FIX|Fix[#23117]
  htdocs/core/actions_massactions.inc.php
Labels: Discussion

#23145 fix(scrutinizer)
  htdocs/reception/stats/month.php
Labels: PR to fix or conflict to solve

#23123 Fix : ficheinter cards and stat
  htdocs/fichinter/card-rec.php
  htdocs/fichinter/card.php
  htdocs/fichinter/class/fichinterrec.class.php
  htdocs/fichinter/stats/index.php
Labels: PR to fix or conflict to solve

#23242 NEW - Invoice - Show Category of operations
  htdocs/admin/facture.php
  htdocs/admin/pdf.php
  htdocs/admin/pdf_other.php
  htdocs/core/lib/pdf.lib.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/bills.lang
  htdocs/master.inc.php
Labels: Priority - High / Blocking

#23198 Update llx_20_c_departements.sql
  htdocs/install/mysql/data/llx_20_c_departements.sql
Labels: Discussion

#23166 Delete MO : object's links must be deleted
  htdocs/core/class/commonobject.class.php
Labels: PR to fix or conflict to solve

#23157 NEW Mode View for list of Stocks
  htdocs/product/stock/class/entrepot.class.php
  htdocs/product/stock/list.php
Labels: PR postponed

#23155 NEW use more recent model by default
  htdocs/core/modules/modFacture.class.php
  htdocs/core/modules/modPropale.class.php
Labels: PR postponed

#23098 NEW Captcha for public member's subscription form
  htdocs/public/members/new.php
Labels: PR postponed

#23070 NEW substitute date now in email collector
  htdocs/emailcollector/class/emailcollector.class.php
Labels: PR postponed

#23065 NEW: Notification for Sign or Refused Propal from Online Page
  htdocs/core/ajax/onlineSign.php
  htdocs/core/class/notify.class.php
  htdocs/install/mysql/data/llx_c_action_trigger.sql
  htdocs/install/mysql/migration/16.0.0-17.0.0.sql
  htdocs/langs/en_US/other.lang
  htdocs/langs/fr_FR/other.lang
  htdocs/public/onlinesign/newonlinesign.php
Labels: PR postponed

#23109 FIX data too long in ticket message
  htdocs/ticket/class/ticket.class.php
Labels: Discussion

#22912 add hook in productlot tooltip
  htdocs/product/stock/class/productlot.class.php
Labels: Discussion

#23307 Fix v17 White bg-color for chart and badge in darkmode
  htdocs/core/class/dolgraph.class.php
  htdocs/theme/eldy/badges.inc.php
Labels: PR needs feedback

#23237 FIX : "read" right of hrm evaluations must allow to see only user eva…
  htdocs/core/modules/modHRM.class.php
  htdocs/hrm/class/evaluation.class.php
  htdocs/hrm/evaluation_card.php
  htdocs/hrm/evaluation_list.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: PR to fix or conflict to solve

#23151 NEW|New view mode for List of Orders
  htdocs/commande/list.php
  htdocs/core/class/commonorder.class.php
  htdocs/theme/eldy/info-box.inc.php
Labels: PR postponed, PR to fix or conflict to solve

#23277 New mode view Kanban for list expeditions
  htdocs/core/class/commonobjectline.class.php
  htdocs/expedition/list.php
Labels: PR to fix or conflict to solve

#23272 New mode view for contact adress list
  htdocs/contact/class/contact.class.php
  htdocs/contact/list.php
Labels: PR to fix - Continuous Integration Test failed

#23084 NEW|New Add Kanban mode for listing of userGroup
  htdocs/user/class/usergroup.class.php
  htdocs/user/group/list.php
Labels: PR postponed

#23018 FIX #22837
  htdocs/core/class/html.formticket.class.php
  htdocs/ticket/card.php
Labels: PR to merge, PR postponed, DevCamp 2022 Nantes

#22873 NEW presend mass action in contact list
  htdocs/contact/list.php
  htdocs/core/actions_massactions.inc.php
  htdocs/core/tpl/massactions_pre.tpl.php
Labels: PR postponed

#22867 NEW triggers on mailing
  htdocs/comm/mailing/class/mailing.class.php
Labels: PR postponed

#22841 NEW Add abbility of ODT support to supplier invoices
  htdocs/admin/supplier_invoice.php
  htdocs/core/actions_setmoduleoptions.inc.php
  htdocs/core/lib/files.lib.php
  htdocs/core/modules/modFournisseur.class.php
  htdocs/core/modules/supplier_invoice/doc/doc_generic_supplier_invoice_odt.modules.php
  htdocs/install/doctemplates/supplier_invoices/index.html
  htdocs/install/doctemplates/supplier_invoices/template_supplier_invoices.odt
Labels: Discussion, Priority - Medium

#22144 FIX theorical stock when stock calculate on bill
  htdocs/product/class/product.class.php
Labels: PR to fix or conflict to solve
