Repository Dolibarr/dolibarr, pull requests merged in 2022-10, with the labels that each got.

#22470 Correction bug #22469 Especes is only written with plurial
  htdocs/langs/fr_FR/bills.lang
Labels: PR not qualified

#22428 FIXME sql error
  htdocs/accountancy/class/accountingjournal.class.php
  htdocs/accountancy/journal/variousjournal.php
Labels: Discussion

#22403 update code toward php8 compliance
  htdocs/accountancy/admin/fiscalyear.php
  htdocs/accountancy/admin/fiscalyear_card.php
  htdocs/accountancy/admin/fiscalyear_info.php
  htdocs/accountancy/admin/productaccount.php
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/accountancy/bookkeeping/card.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/closure/index.php
  htdocs/accountancy/customer/card.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/lines.php
  htdocs/accountancy/customer/list.php
Labels: PR to fix or conflict to solve

#22491 NEW date delivery planned on orders linked to company
  htdocs/societe/consumption.php
Labels: Discussion

#22136 Update productcustomerprice.class.php
  htdocs/product/class/productcustomerprice.class.php
Labels: Discussion

#22085 NEW #22048 Added notes (public/private) to productlot module
  htdocs/core/lib/product.lib.php
  htdocs/install/mysql/migration/16.0.0-17.0.0.sql
  htdocs/install/mysql/tables/llx_product_lot.sql
  htdocs/product/stock/class/productlot.class.php
  htdocs/product/stock/productlot_note.php
Labels: PR to fix or conflict to solve

#22278 FIX Accountancy - Review reconcile function (separate manuel & auto reconcile)
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/class/lettering.class.php
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR to merge

#22525 NEW: Manage Position (Rank) on Contract Lines
  htdocs/contrat/card.php
  htdocs/contrat/class/api_contracts.class.php
  htdocs/contrat/class/contrat.class.php
  htdocs/core/ajax/row.php
  htdocs/install/doctemplates/websites/website_template-stellar/containers/page23.tpl.php
  htdocs/install/upgrade2.php
  htdocs/langs/en_US/install.lang
  htdocs/modulebuilder/template/class/myobject.class.php
  htdocs/modulebuilder/template/myobject_card.php
Labels: PR to merge

#22518 FIX remove db object for avoid error with postgresql
  htdocs/variants/ajax/get_attribute_values.php
  htdocs/variants/class/ProductAttribute.class.php
  htdocs/variants/class/ProductAttributeValue.class.php
  htdocs/variants/combinations.php
Labels: Discussion

#22499 fix: display correct id of thirdparty in Error of sendEmailsRemindersOnInvoiceDueDate
  htdocs/compta/facture/class/facture.class.php
Labels: PR to merge

#22496 new: on CronJob, sendEmailsRemindersOnInvoiceDueDate use billing contact email if exists
  htdocs/compta/facture/class/facture.class.php
Labels: Discussion

#22522 FIX 16.0 - computed extrafields are not displayed if the object has no classic extrafields
  htdocs/core/class/commonobject.class.php
Labels: Bug

#22589 FIX: Fix the function get_origin() on MouvementStock class for general case
  htdocs/product/stock/class/mouvementstock.class.php
Labels: Discussion

#22670 FIX can not set prospect status "Do not contact"
  htdocs/societe/class/societe.class.php
Labels: Discussion
