Repository Dolibarr/dolibarr, pull requests merged in 2022-05, with the labels that each got.

#20737 CLOSE #20736 Allow extrafields SQL filters on REST API product lookup
  htdocs/product/class/api_products.class.php
Labels: PR to merge (after fix suggested)

#20669 FIX and NEW i18n for creating tickets via the mail collector
  htdocs/admin/emailcollector_list.php
  htdocs/admin/ticket.php
  htdocs/core/modules/modEmailCollector.class.php
  htdocs/core/modules/modTicket.class.php
  htdocs/emailcollector/class/emailcollector.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/ticket.lang
  htdocs/langs/fr_FR/ticket.lang
Labels: Discussion

#20656 NEW: Add column template invoice in invoice list
  htdocs/compta/facture/list.php
  htdocs/core/class/html.form.class.php
Labels: Discussion

#20730 New : module webhook database structure
  htdocs/install/mysql/tables/llx_webhook_target-webhook.key.sql
  htdocs/install/mysql/tables/llx_webhook_target-webhook.sql
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#20686 NEW Option MAIL_MASS_ACTION_ADD_LAST_IF_MAIN_DOC_NOT_FOUND to send last document in mass mailing action
  htdocs/core/actions_massactions.inc.php
  htdocs/core/class/html.formmail.class.php
  htdocs/langs/en_US/main.lang
  htdocs/langs/fr_FR/main.lang
Labels: PR to merge

#20679 NEW : TakePos - add hooks complete product display
  htdocs/takepos/index.php
Labels: PR to fix or conflict to solve

#20655 Move checkbox column as first column on modulebuilder
  htdocs/modulebuilder/template/myobject_list.php
Labels: Discussion

#18163 NEW: Separate read-only and adding time on projects
  htdocs/core/modules/modProjet.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
  htdocs/projet/tasks/time.php
Labels: Discussion, PR to fix or conflict to solve

#19525 NEW : Add constant to show category description in TakePos
  htdocs/takepos/index.php
Labels: PR postponed

#18853 NEW: payment conditions enabling semi-automatic deposit creation (Issue #18439)
  htdocs/admin/dict.php
  htdocs/comm/card.php
  htdocs/comm/propal/card.php
  htdocs/comm/propal/class/propal.class.php
  htdocs/comm/propal/list.php
  htdocs/commande/card.php
  htdocs/commande/class/commande.class.php
  htdocs/commande/list.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/fourn/card.php
  htdocs/fourn/facture/list.php
  htdocs/install/mysql/data/llx_c_payment_term.sql
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/install/mysql/tables/llx_c_payment_term.sql
  htdocs/install/mysql/tables/llx_commande.sql
  htdocs/install/mysql/tables/llx_propal.sql
  htdocs/install/mysql/tables/llx_societe.sql
  htdocs/langs/en_US/bills.lang
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#20797 add hook for takepos addline
  htdocs/takepos/invoice.php
Labels: PR to fix or conflict to solve

#20650 NEW - Move checkbox column as first column on Thirdparty list
  htdocs/core/class/html.form.class.php
  htdocs/societe/list.php
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/md/style.css.php
Labels: Discussion

#20798 FIX : Trigger on commonObject setProject
  htdocs/core/class/commonobject.class.php
  htdocs/ticket/class/ticket.class.php
Labels: PR to fix or conflict to solve

#20684 fix: Ticket extrafields were not kept during triggers on TICKET_CREAT…
  htdocs/ticket/class/ticket.class.php
Labels: Discussion, PR to fix or conflict to solve

#20134 Fix : fix bug in modulebuilder and fix php8.0 warnings in modulebuilder
  htdocs/core/lib/modulebuilder.lib.php
  htdocs/modulebuilder/index.php
Labels: PR to merge (after fix suggested)

#20573 Avoid duplicate 3rd partires
  htdocs/core/ajax/ajaxcompanies.php
  htdocs/societe/card.php
Labels: Discussion

#20951 missing MULTI CURRENCY on recurrent invoices #20664
  htdocs/compta/facture/class/facture-rec.class.php
Labels: DevCamp 2022 Valence

#20954 FIX #20487 missing letter D in constant THIRDPARTIES_DISABLE_RELATED_…
  htdocs/core/lib/company.lib.php
Labels: DevCamp 2022 Valence

#20953 FIX missing morecss for multiselectarray
  htdocs/core/class/commonobject.class.php
Labels: DevCamp 2022 Valence

#20950 Fix backport for 16 and ADD color, default value ,
  htdocs/core/class/html.formsetup.class.php
  htdocs/modulebuilder/index.php
  htdocs/modulebuilder/template/admin/setup.php
Labels: DevCamp 2022 Valence

#20947 Fix : php warning 8 / backup
  htdocs/admin/tools/dolibarr_export.php
Labels: DevCamp 2022 Valence

#20945 Fix default value boolean
  htdocs/core/class/commonobject.class.php
Labels: DevCamp 2022 Valence

#20949 Fix : Missing description field in function dol_dir_list_in_database
  htdocs/core/lib/files.lib.php
Labels: DevCamp 2022 Valence

#20946 field ref_customer in llx_expedition is not varchar(255) #20629
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
Labels: DevCamp 2022 Valence

#20959 Fix : php 8.0 warnings
  htdocs/core/class/commonobject.class.php
  htdocs/fourn/facture/card.php
  htdocs/projet/card.php
  htdocs/projet/tasks.php
  htdocs/user/list.php
Labels: DevCamp 2022 Valence

#20956 FIX php8 compatibility
  htdocs/compta/facture/card.php
  htdocs/compta/facture/contact.php
  htdocs/compta/facture/info.php
  htdocs/compta/facture/list.php
  htdocs/compta/facture/note.php
  htdocs/core/class/html.form.class.php
Labels: DevCamp 2022 Valence

#20955 Fix : bug of upgrade when install not finished
  htdocs/install/check.php
Labels: DevCamp 2022 Valence

#20957 fix : The property chid does not seem to exist on PaymentSocialContri…
  htdocs/compta/paiement_charge.php
  htdocs/compta/sociales/class/chargesociales.class.php
  htdocs/compta/sociales/class/paymentsocialcontribution.class.php
Labels: PR to fix or conflict to solve, DevCamp 2022 Valence

#20948 FIX#20886 : manage durations in list_print_total.tpl.php
  htdocs/core/tpl/list_print_total.tpl.php
  htdocs/fichinter/list.php
Labels: DevCamp 2022 Valence

#20962 Fix : facture fourn type not init in radio
  htdocs/fourn/facture/card.php
Labels: DevCamp 2022 Valence

#20958 FIX: warning Php 8
  htdocs/core/class/html.formfile.class.php
Labels: PR to fix - Continuous Integration Test failed, DevCamp 2022 Valence

#20964 fix : The property chid does not seem to exist on PaymentVAT
  htdocs/compta/paiement_vat.php
  htdocs/compta/tva/class/paymentvat.class.php
  htdocs/compta/tva/class/tva.class.php
Labels: DevCamp 2022 Valence

#20967 New branch 21 05 2022 02
  htdocs/compta/paiement/class/paiement.class.php
  htdocs/fourn/class/paiementfourn.class.php
  htdocs/societe/class/societe.class.php
Labels: DevCamp 2022 Valence

#20975 Fix no document available on job candidature
  htdocs/core/modules/modRecruitment.class.php
  htdocs/recruitment/core/modules/recruitment/modules_recruitmentcandidature.php
Labels: DevCamp 2022 Valence

#20971 Fix PDF watermark over PDF text
  htdocs/core/lib/pdf.lib.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/expedition/doc/pdf_espadon.modules.php
  htdocs/core/modules/expedition/doc/pdf_rouget.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/fichinter/doc/pdf_soleil.modules.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/core/modules/reception/doc/pdf_squille.modules.php
  htdocs/core/modules/supplier_proposal/doc/pdf_aurore.modules.php
Labels: DevCamp 2022 Valence

#20969 FIX php8.1 warning
  htdocs/admin/dict.php
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/user/perms.php
Labels: DevCamp 2022 Valence

#20910 NEW #20905 add hooks for accountancy export
  htdocs/accountancy/admin/export.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/class/accountancyexport.class.php
Labels: PR postponed

#20973 fix : number cheque receipt list_bank entries #5366
  htdocs/compta/bank/bankentries_list.php
Labels: DevCamp 2022 Valence

#20983 Fix delete customer payment
  htdocs/compta/paiement/card.php
  htdocs/core/lib/security.lib.php
Labels: DevCamp 2022 Valence

#20980 Fix scrutinizer and remove unused functions
  htdocs/compta/index.php
  htdocs/core/lib/invoice.lib.php
  htdocs/expedition/class/expedition.class.php
  htdocs/expensereport/class/expensereport.class.php
  htdocs/fourn/class/fournisseur.commande.dispatch.class.php
  htdocs/reception/card.php
  htdocs/reception/class/reception.class.php
Labels: DevCamp 2022 Valence

#20495 FIX : regression select extrafield search + fix function name
  htdocs/api/class/api.class.php
  htdocs/categories/class/categorie.class.php
  htdocs/comm/propal/class/api_proposals.class.php
  htdocs/commande/class/api_orders.class.php
  htdocs/compta/bank/class/api_bankaccounts.class.php
  htdocs/compta/facture/class/api_invoices.class.php
  htdocs/compta/facture/list.php
  htdocs/contrat/class/api_contracts.class.php
  htdocs/core/class/extrafields.class.php
  htdocs/core/lib/functions.lib.php
  htdocs/core/tpl/extrafields_list_search_sql.tpl.php
  htdocs/expedition/class/api_shipments.class.php
  htdocs/expensereport/class/api_expensereports.class.php
  htdocs/exports/class/export.class.php
  htdocs/fourn/class/api_supplier_invoices.class.php
  htdocs/knowledgemanagement/class/api_knowledgemanagement.class.php
  htdocs/modulebuilder/template/class/api_mymodule.class.php
  htdocs/product/class/api_products.class.php
  htdocs/projet/class/api_projects.class.php
  htdocs/projet/class/api_tasks.class.php
  htdocs/recruitment/class/api_recruitment.class.php
Labels: PR to merge

#20098 Create MO Child
  htdocs/bom/bom_card.php
  htdocs/bom/lib/bom.lib.php
  htdocs/core/actions_addupdatedelete.inc.php
  htdocs/core/class/html.form.class.php
  htdocs/langs/en_US/mrp.lang
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_card.php
  htdocs/mrp/mo_list.php
  htdocs/mrp/tpl/linkedobjectblock.tpl.php
  htdocs/mrp/tpl/originproductline.tpl.php
Labels: Discussion

#19099 New: receipt beep alternative and current date/time
  htdocs/core/class/dolreceiptprinter.class.php
  htdocs/langs/en_US/receiptprinter.lang
  htdocs/langs/it_IT/receiptprinter.lang
Labels: PR needs feedback

#20968 New : function dol_move_dir in htdocs/core/lib/files.lib.php
  htdocs/core/lib/files.lib.php
  test/phpunit/FilesLibTest.php
Labels: PR to merge (after fix suggested), DevCamp 2022 Valence
