Repository Dolibarr/dolibarr, pull requests merged in 2022-01, with the labels that each got.

#19644 FIX: manage multientity in ticket public page by querystring (#Evarisk)
  htdocs/public/ticket/create_ticket.php
  htdocs/public/ticket/index.php
  htdocs/public/ticket/list.php
  htdocs/public/ticket/view.php
  htdocs/ticket/class/actions_ticket.class.php
Labels: PR postponed

#19729 Fix: correctly display the products of a warehouse in the pdf
  htdocs/core/modules/stock/doc/pdf_standard.modules.php
Labels: Discussion

#19759 NEW: add product ref into BOM tooltips
  htdocs/bom/class/bom.class.php
  htdocs/mrp/index.php
  htdocs/product/stats/bom.php
Labels: PR postponed

#19623 NEW : Add constant to change price HT in TakePos
  htdocs/takepos/invoice.php
Labels: PR to fix or conflict to solve

#19557 Unaccent
  htdocs/core/lib/functions.lib.php
Labels: PR to merge

#19402 FIX : reorder all lines when delete document line everywhere (4 documents were missing)
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
Labels: Discussion

#17577 add thirdparty customer code to substitutionarray
  htdocs/comm/mailing/card.php
  htdocs/core/class/html.formmail.class.php
Labels: PR to merge

#19834 Update extrafields.class.php
  htdocs/core/class/extrafields.class.php
Labels: Discussion

#19758 NEW: Display product ref in "Object link" product tab for BOM
  htdocs/product/stats/bom.php
Labels: PR postponed

#19647 NEW add entity filter in exports
  htdocs/core/modules/modCommande.class.php
  htdocs/core/modules/modFacture.class.php
  htdocs/core/modules/modPropale.class.php
  htdocs/core/modules/modSociete.class.php
Labels: PR postponed

#19645 NEW: add WordPress OAuth
  htdocs/includes/OAuth/OAuth2/Service/WordPress.php
Labels: PR postponed

#19618 Add Hooks for takepos ajax search
  htdocs/takepos/ajax/ajax.php
Labels: PR postponed

#19527 NEW : Add constant to hide categories in TakePos
  htdocs/takepos/index.php
Labels: PR postponed

#19521 NEW : Show product reference in Takepos
  htdocs/takepos/index.php
  htdocs/takepos/invoice.php
Labels: PR postponed

#19897 fix docker build setup
  build/docker/Dockerfile
  build/docker/docker-compose.yml
  htdocs/install/default.css
Labels: Discussion

#10997 NEW : use subproducts costprice and pmp if empty on father
  htdocs/fourn/ajax/getSupplierPrices.php
Labels: Discussion, PR to fix or conflict to solve

#19764 NEW: #19763 DB change only - Can invoice task time per different services
  htdocs/includes/OAuth/OAuth2/Service/WordPress.php
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/install/mysql/tables/llx_projet_task_time.sql
Labels: PR postponed

#19866 FIX : rankorder + vacant positions
  htdocs/hrm/class/position.class.php
  htdocs/hrm/skill_card.php
  htdocs/install/mysql/migration/14.0.0-15.0.0.sql
  htdocs/install/mysql/tables/llx_hrm_job_user-hrm.sql
Labels: Discussion

#19857 getTasksArray() fetch_optionals to populate ExtraFields
  htdocs/projet/class/task.class.php
Labels: PR to fix or conflict to solve

#19733 NEW: Project contact tab
  htdocs/contact/project.php
  htdocs/core/lib/contact.lib.php
  htdocs/langs/en_US/projects.lang
  htdocs/langs/fr_FR/projects.lang
Labels: PR postponed

#19737 NEW Add possibility with constant MAIN_LOGIN_BADCHARUNAUTHORIZED to define bad character unauthorized into login name
  htdocs/user/class/user.class.php
Labels: PR postponed

#19746 NEW : Contact filter project list
  htdocs/core/class/html.form.class.php
  htdocs/langs/en_US/projects.lang
  htdocs/langs/fr_FR/projects.lang
  htdocs/projet/list.php
Labels: PR postponed

#19772 FIX #19760 Uniformize labels
  htdocs/admin/dict.php
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/install/mysql/tables/llx_c_actioncomm.sql
  htdocs/install/mysql/tables/llx_c_availability.sql
  htdocs/install/mysql/tables/llx_c_barcode_type.sql
  htdocs/install/mysql/tables/llx_c_chargesociales.sql
  htdocs/install/mysql/tables/llx_c_civility.sql
  htdocs/install/mysql/tables/llx_c_country.sql
  htdocs/install/mysql/tables/llx_c_currencies.sql
  htdocs/install/mysql/tables/llx_c_effectif.sql
  htdocs/install/mysql/tables/llx_c_exp_tax_cat.sql
  htdocs/install/mysql/tables/llx_c_hrm_department.sql
  htdocs/install/mysql/tables/llx_c_hrm_function.sql
  htdocs/install/mysql/tables/llx_c_input_method.sql
  htdocs/install/mysql/tables/llx_c_input_reason.sql
  htdocs/install/mysql/tables/llx_c_lead_status.sql
  htdocs/install/mysql/tables/llx_c_paiement.sql
  htdocs/install/mysql/tables/llx_c_paper_format.sql
  htdocs/install/mysql/tables/llx_c_partnership_type.sql
  htdocs/install/mysql/tables/llx_c_product_nature.sql
  htdocs/install/mysql/tables/llx_c_productbatch_qcstatus.sql
  htdocs/install/mysql/tables/llx_c_propalst.sql
  htdocs/install/mysql/tables/llx_c_prospectcontactlevel.sql
  htdocs/install/mysql/tables/llx_c_prospectlevel.sql
  htdocs/install/mysql/tables/llx_c_recruitment_origin.sql
  htdocs/install/mysql/tables/llx_c_shipment_mode.sql
  htdocs/install/mysql/tables/llx_c_shipment_package_type.sql
  htdocs/install/mysql/tables/llx_c_stcomm.sql
  htdocs/install/mysql/tables/llx_c_stcommcontact.sql
  htdocs/install/mysql/tables/llx_c_type_contact.sql
  htdocs/install/mysql/tables/llx_c_type_container.sql
  htdocs/install/mysql/tables/llx_c_type_fees.sql
  htdocs/install/mysql/tables/llx_c_type_resource.sql
  htdocs/install/mysql/tables/llx_c_typent.sql
  htdocs/install/mysql/tables/llx_c_units.sql
Labels: Discussion

#19932 FIX : Replace restricthtml to nohtml in export .
  htdocs/exports/export.php
Labels: Discussion

#19655 use any available fontawesome icon in picto
  htdocs/core/lib/functions.lib.php
Labels: PR postponed

#19923 NEW - Add param color button action
  htdocs/admin/ihm.php
  htdocs/core/lib/usergroups.lib.php
  htdocs/langs/en_US/admin.lang
  htdocs/theme/eldy/btn.inc.php
  htdocs/theme/eldy/style.css.php
  htdocs/theme/eldy/theme_vars.inc.php
  htdocs/theme/md/btn.inc.php
  htdocs/theme/md/style.css.php
  htdocs/theme/md/theme_vars.inc.php
Labels: PR to fix or conflict to solve

#19962 FIX pay value in TakePOS
  htdocs/takepos/invoice.php
Labels: Discussion

#19609 FIX supplier_proposal when line update price U.P change 0
  htdocs/supplier_proposal/class/supplier_proposal.class.php
Labels: Discussion

#19919 NEW stock filter in reassort lists
  htdocs/product/reassort.php
  htdocs/product/reassortlot.php
Labels: Discussion

#18081 fix: #19428 ticket substitution
  htdocs/core/lib/functions.lib.php
  htdocs/ticket/card.php
Labels: PR to fix or conflict to solve
