Repository Dolibarr/dolibarr, pull requests merged in 2022-03, with the labels that each got.

#20196 FIX - Add last_main_doc in table societe
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/install/mysql/tables/llx_societe.sql
Labels: Discussion

#20186 FIX : Add ID into formproject method
  htdocs/core/class/html.form.class.php
Labels: PR to fix or conflict to solve

#19989 add target attribute on getNomUrl
  htdocs/commande/class/commande.class.php
Labels: PR to merge

#19990 add attribute target on getNomurl()
  htdocs/societe/class/societe.class.php
Labels: PR to merge

#20268 fix: #20267 #Evarisk same required field displayed on edit or new card
  htdocs/comm/action/card.php
Labels: Discussion

#20256 FIX: project creation prevented if PROJECTLEADER contact role renamed, de-activated or deleted
  htdocs/langs/en_US/projects.lang
  htdocs/projet/card.php
Labels: Discussion

#20365 Fix : keep row order into invoices created from massactions
  htdocs/core/actions_massactions.inc.php
  htdocs/fourn/commande/dispatch.php
  htdocs/reception/class/reception.class.php
  htdocs/reception/list.php
Labels: Discussion

#20356 NEW Accountancy - Add subledger account when we generate a transaction with a deposit invoice
  htdocs/accountancy/journal/sellsjournal.php
Labels: PR to merge

#20374 NEW clean values and amount in FEC import
  htdocs/accountancy/class/accountancyimport.class.php
  htdocs/core/modules/import/import_csv.modules.php
  htdocs/core/modules/import/import_xlsx.modules.php
  htdocs/core/modules/modAccounting.class.php
Labels: PR to merge

#20307 NEW - Record count badge in custom modules tab
  htdocs/core/lib/functions.lib.php
Labels: PR to fix or conflict to solve

#20421 FIX: replacing to dolGetButtonAction on Delivery card
  htdocs/delivery/card.php
Labels: PR to fix or conflict to solve

#20302 FIX: better error management at product selling price update
  htdocs/product/class/product.class.php
  htdocs/product/price.php
  htdocs/variants/class/ProductCombination.class.php
Labels: Discussion

#20308 Fix do not modify entity on group edit
  htdocs/user/group/card.php
Labels: Discussion

#20293 NEW Availibility dictionnary new column unit and number
  htdocs/admin/dict.php
  htdocs/install/mysql/data/llx_c_availability.sql
  htdocs/install/mysql/migration/15.0.0-16.0.0.sql
  htdocs/install/mysql/tables/llx_c_availability.sql
Labels: PR to fix or conflict to solve

#20458 FIX search bracode rule and avoid undefined quantity on search in tak…
  htdocs/takepos/ajax/ajax.php
  htdocs/takepos/index.php
Labels: Discussion

#20274 FIX: Mass action ship orders
  htdocs/commande/list.php
  htdocs/langs/en_US/orders.lang
  htdocs/langs/fr_FR/orders.lang
Labels: Discussion

#20456 FIX multicompany sharings compatibility
  htdocs/core/class/commonobject.class.php
  htdocs/product/class/product.class.php
  htdocs/projet/class/task.class.php
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve

#20389 NEW/fix GRH extrafields and more stuff
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/hrm/admin/evaluation_extrafields.php
  htdocs/hrm/admin/job_extrafields.php
  htdocs/hrm/admin/skill_extrafields.php
  htdocs/hrm/evaluation_card.php
  htdocs/hrm/evaluation_list.php
  htdocs/hrm/job_list.php
  htdocs/hrm/lib/hrm.lib.php
  htdocs/hrm/lib/hrm_evaluation.lib.php
  htdocs/hrm/position.php
  htdocs/hrm/position_list.php
  htdocs/hrm/skill_card.php
  htdocs/hrm/skill_list.php
  htdocs/hrm/skill_tab.php
  htdocs/langs/en_US/hrm.lang
Labels: PR to fix or conflict to solve

#20299 FIX check mandatory thirdparty fields for mass action
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/langs/en_US/errors.lang
Labels: PR to merge

#20348 Fix #20263 Accountancy setup displayed with right
  htdocs/accountancy/index.php
Labels: Discussion

#20247 NEW: check invoice date
  htdocs/admin/facture.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/core/actions_massactions.inc.php
  htdocs/core/modules/modFacture.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/bills.lang
Labels: Discussion

#20315 Fix: Facture dolGetButtonAction
  htdocs/compta/facture/card.php
Labels: Discussion, PR to fix or conflict to solve

#20324 NEW - Add Hook fo Notif
  htdocs/admin/notification.php
  htdocs/core/class/notify.class.php
  htdocs/core/triggers/interface_50_modNotification_Notification.class.php
Labels: Discussion

#20485 FIX : ref_client doesn't exists on supplier invoice, then ref_fourn needs to have a default value when we want to bill several supplier orders
  htdocs/fourn/commande/list.php
Labels: PR to fix or conflict to solve

#19703 Fix #19662 : mysql8 user creation in 2 steps
  htdocs/core/db/mysqli.class.php
Labels: Discussion
