Repository Dolibarr/dolibarr, pull requests merged in 2022-06, with the labels that each got.

#21044 php V8 warning ($conf->c part 1
  htdocs/comm/action/card.php
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/bank/card.php
  htdocs/compta/facture/card.php
  htdocs/core/class/html.formmail.class.php
Labels: PR to fix or conflict to solve

#20999 NEW : add coefficient on unit ht line in expenseReport card
  htdocs/expensereport/ajax/ajaxik.php
  htdocs/expensereport/card.php
  htdocs/expensereport/class/expensereport.class.php
  htdocs/expensereport/class/expensereport_ik.class.php
  htdocs/langs/en_US/expensereports.lang
Labels: PR to fix or conflict to solve

#19940 NEW - Add option pdf global thirdparty alias
  htdocs/admin/pdf.php
  htdocs/core/lib/pdf.lib.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix or conflict to solve

#19426 NEW: make unicity for user assigned(responsible) on ticket from anyways
  htdocs/ticket/card.php
  htdocs/ticket/contact.php
Labels: Discussion

#21176 add var_dump check
  .travis.yml
Labels: Discussion

#21200 Save usermodid to updatePercent
  htdocs/comm/action/class/actioncomm.class.php
Labels: PR to fix or conflict to solve

#21141 NEW: Send Notification Without File when E-mail Template doesn't attach file
  htdocs/core/class/notify.class.php
Labels: PR to fix or conflict to solve

#21222 Fix php8 compatibility
  htdocs/user/bank.php
Labels: PR to fix or conflict to solve

#21251 BUG FIX : Increasing the scope of the variable
  htdocs/core/boxes/box_project.php
Labels: PR to fix or conflict to solve

#21234 BUG FIX 'The property socid does not seem to exist on Recruitm…
  htdocs/recruitment/recruitmentcandidature_list.php
Labels: PR to merge

#21276 FIX bug :The properties product_tosell & product_tobuy do not exist on OrderLine
  htdocs/commande/class/commande.class.php
  htdocs/core/class/commonorder.class.php
Labels: PR to fix or conflict to solve

#21264 BUG FIX Attribute datee doesn't exist on class Task
  htdocs/projet/class/task.class.php
Labels: PR to fix or conflict to solve

#21263 BUG FIX FetchLines does not exist on class emailcollector action but FetchLinesComon does
  htdocs/emailcollector/class/emailcollectoraction.class.php
Labels: PR to fix or conflict to solve

#21261 BUG FIX : changing function name to the exisiting one (3)
  htdocs/core/class/stats.class.php
Labels: Discussion

#21247 BUG FIX: evaluate() doesn't cover the case where $expr is empty
  htdocs/core/class/evalmath.class.php
  test/phpunit/EvalMathTest.php
Labels: PR to fix or conflict to solve

#21181 Fix #20500
  htdocs/user/class/user.class.php
  test/phpunit/UserTest.php
Labels: PR to fix or conflict to solve

#21096 Fix deposit management on accountancy supplier index
  htdocs/accountancy/supplier/index.php
Labels: PR to fix or conflict to solve

#21194 Fix supplier deposit can not be used to pay supplier invoice
  htdocs/core/class/commoninvoice.class.php
Labels: Discussion

#21172 Look & Feel - Align amount to right on card
  htdocs/compta/facture/card.php
  htdocs/fourn/facture/card.php
Labels: PR to merge (after fix suggested)

#21209 Fix PHP 8.1
  htdocs/accountancy/admin/account.php
  htdocs/accountancy/admin/defaultaccounts.php
  htdocs/accountancy/admin/export.php
  htdocs/accountancy/admin/index.php
  htdocs/accountancy/admin/journals_list.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/customer/list.php
  htdocs/accountancy/expensereport/list.php
  htdocs/accountancy/supplier/lines.php
  htdocs/accountancy/supplier/list.php
  htdocs/core/boxes/box_scheduled_jobs.php
  htdocs/core/class/html.formaccounting.class.php
  htdocs/debugbar/class/DebugBar.php
Labels: PR to merge

#21348 FIX: 15 fix graph ficheinter status
  htdocs/fichinter/index.php
Labels: Discussion

#21389 FIX - php V8 expedition card
  htdocs/core/class/commonobject.class.php
  htdocs/expedition/card.php
  htdocs/expedition/class/expedition.class.php
Labels: PR to fix or conflict to solve

#21260 BUG FIX : changing function name to existing one (2)
  htdocs/core/class/stats.class.php
Labels: Discussion, PR to fix or conflict to solve

#21245 BUG FIX : Changing type of the parameter
  htdocs/core/class/evalmath.class.php
Labels: PR to fix or conflict to solve
