Repository Dolibarr/dolibarr, pull requests merged in 2022-08, with the labels that each got.

#21646 New : Add DoS security on GETPOST with img Yogosha report 11963
  htdocs/admin/security_other.php
  htdocs/core/lib/functions.lib.php
  htdocs/install/mysql/migration/16.0.0-17.0.0.sql
  htdocs/langs/en_US/admin.lang
Labels: Discussion

#21621 FIX - php V8 index
  htdocs/index.php
Labels: PR to fix or conflict to solve

#21588 NEW : TAKEPOS - setup terminal name
  htdocs/core/lib/takepos.lib.php
  htdocs/langs/en_US/cashdesk.lang
  htdocs/takepos/admin/terminal.php
  htdocs/takepos/index.php
Labels: PR to fix or conflict to solve

#21665 Fix layout of Incomes-Expenses + Claims-Debts accounting tables
  htdocs/compta/resultat/clientfourn.php
Labels: PR to fix or conflict to solve

#21601 Module Tickets - modification select
  htdocs/core/class/html.formticket.class.php
  htdocs/custom/README.md
  htdocs/ticket/card.php
Labels: PR to merge (after fix suggested)

#21492 FIX dol_compress_dir names files on archives
  htdocs/core/lib/files.lib.php
Labels: Discussion

#21749 CLOSE 21748 Maillage sur ErrorProductAlreadyExists en créant produit
  htdocs/product/card.php
Labels: PR to fix or conflict to solve

#21750 NEW: Added "Get lines and Post lines from BOM" at the REST Service
  htdocs/bom/class/api_boms.class.php
  htdocs/bom/class/bom.class.php
Labels: PR to fix or conflict to solve

#21184 FIX #21094
  htdocs/product/class/product.class.php
Labels: PR to fix or conflict to solve

#21808 Fix: Parameter "backtopage" on AddEvent Button
  htdocs/mrp/mo_agenda.php
Labels: PR to fix or conflict to solve

#21718 NEW: add oldcopy to Ticket for modules intercepting TICKET_MODIFY
  htdocs/ticket/class/ticket.class.php
Labels: PR to fix or conflict to solve

#21726 keep batch info when correcting stock
  htdocs/product/stock/tpl/stockcorrection.tpl.php
Labels: Discussion

#21722 NEW show SellBy/EatBy dates for each batch product in shipment card
  htdocs/expedition/card.php
Labels: Discussion

#21673 Fix - Form Setup yesno
  htdocs/core/class/html.formsetup.class.php
Labels: Discussion

#21638 FIX : Datepicker year interval
  htdocs/core/class/html.form.class.php
Labels: Discussion

#21811 PHP8 Warnings
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/compta/accounting-files.php
  htdocs/compta/resultat/result.php
  htdocs/compta/stats/byratecountry.php
  htdocs/compta/stats/cabyprodserv.php
  htdocs/compta/stats/cabyuser.php
  htdocs/compta/stats/casoc.php
Labels: PR to merge

#21821 NEW Accountancy - Manage supplier deposit with specific account
  htdocs/accountancy/admin/defaultaccounts.php
  htdocs/accountancy/class/accountingaccount.class.php
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR to merge

#18284 fix actionbuttons on editline or presend
  htdocs/contrat/card.php
  htdocs/fourn/commande/card.php
Labels: Discussion

#21809 public partnership request
  htdocs/public/partnership/new.php
Labels: PR to fix or conflict to solve

#21846 php V8 warning, import max size not used
  htdocs/imports/import.php
Labels: Discussion

#21869 Imap by oauth2 attachments
  htdocs/emailcollector/class/emailcollector.class.php
  htdocs/includes/webklex/php-imap/deleted.txt
  htdocs/includes/webklex/php-imap/vendor/composer/autoload_static.php
Labels: PR to fix or conflict to solve

#21796 Recruitment improvements
  htdocs/core/modules/modRecruitment.class.php
  htdocs/core/tpl/card_presend.tpl.php
  htdocs/langs/en_US/recruitment.lang
  htdocs/recruitment/class/recruitmentcandidature.class.php
  htdocs/recruitment/index.php
  htdocs/recruitment/lib/recruitment_recruitmentcandidature.lib.php
  htdocs/recruitment/lib/recruitment_recruitmentjobposition.lib.php
  htdocs/recruitment/recruitmentcandidature_agenda.php
  htdocs/recruitment/recruitmentcandidature_card.php
  htdocs/recruitment/recruitmentcandidature_document.php
  htdocs/recruitment/recruitmentcandidature_list.php
  htdocs/recruitment/recruitmentcandidature_note.php
  htdocs/recruitment/recruitmentjobposition_agenda.php
  htdocs/recruitment/recruitmentjobposition_card.php
  htdocs/recruitment/recruitmentjobposition_document.php
  htdocs/recruitment/recruitmentjobposition_note.php
Labels: PR to fix or conflict to solve

#21929 Update modSociete.class.php
  htdocs/core/modules/modSociete.class.php
Labels: Discussion

#21909 TakePos - Use isModEnabled
  htdocs/core/lib/takepos.lib.php
  htdocs/takepos/admin/other.php
  htdocs/takepos/admin/receipt.php
  htdocs/takepos/admin/setup.php
  htdocs/takepos/admin/terminal.php
  htdocs/takepos/ajax/ajax.php
  htdocs/takepos/index.php
  htdocs/takepos/invoice.php
  htdocs/takepos/pay.php
  htdocs/takepos/receipt.php
Labels: PR to merge
