Repository Dolibarr/dolibarr, pull requests merged in 2022-07, with the labels that each got.

#20927 dangerous overwritting
  htdocs/core/class/commonobject.class.php
Labels: DevCamp 2022 Valence

#21433 NEW : add thirdparty column to time list (projet/tasks/time.php)
  htdocs/projet/tasks/time.php
Labels: PR postponed

#21415 NEW Project - Add author on list
  htdocs/projet/list.php
Labels: PR postponed

#21414 NEW invoice export : add accounting affectation
  htdocs/core/modules/modFacture.class.php
Labels: PR postponed

#21406 NEW API for module reception
  htdocs/reception/class/api_receptions.class.php
Labels: PR to fix or conflict to solve

#21401 NEW hook "changeHelpURL" to modify target of the help button
  htdocs/main.inc.php
Labels: PR to fix or conflict to solve

#21351 NEW #19680 Add option PRODUCT_ALLOW_EXTERNAL_DOWNLOAD
  htdocs/core/class/commonobject.class.php
  htdocs/core/lib/files.lib.php
Labels: PR postponed

#21382 NEW #20650 Checkbox column on left for lists
  htdocs/adherents/list.php
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/facture/list.php
  htdocs/contact/list.php
  htdocs/core/class/html.form.class.php
  htdocs/expedition/list.php
  htdocs/product/list.php
  htdocs/product/stock/list.php
  htdocs/projet/list.php
  htdocs/projet/tasks/list.php
  htdocs/reception/list.php
Labels: PR postponed

#21297 NEW add attached file in presend email form of thirdparty card
  htdocs/core/tpl/card_presend.tpl.php
Labels: PR to merge

#21156 New/collective group leave request
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/holiday/card_group.php
  htdocs/holiday/class/holiday.class.php
  htdocs/langs/en_US/holiday.lang
Labels: PR postponed

#20615 NEW product categories filter on inventory list
  htdocs/product/inventory/list.php
Labels: PR to merge

#19765 NEW: Can invoice task time per different services
  htdocs/compta/facture/class/facture.class.php
  htdocs/langs/en_US/projects.lang
  htdocs/product/class/product.class.php
  htdocs/projet/class/task.class.php
  htdocs/projet/tasks/time.php
Labels: PR to merge

#21461 FIX : We must remove empty values from $features array in fetchByProduc…
  htdocs/variants/class/ProductCombination.class.php
Labels: Discussion

#21321 NEW : Create llx_element_categorie.sql
  htdocs/install/mysql/tables/llx_element_categorie.key.sql
  htdocs/install/mysql/tables/llx_element_categorie.sql
Labels: PR to fix or conflict to solve

#21344 NEW Can set start and end dates and comment on button Activate all services
  htdocs/contrat/card.php
  htdocs/contrat/class/contrat.class.php
Labels: Discussion

#21227 NEW support of Stripe Terminal with Takepos
  htdocs/stripe/admin/stripe.php
  htdocs/stripe/ajax/ajax.php
  htdocs/stripe/class/stripe.class.php
  htdocs/takepos/admin/terminal.php
  htdocs/takepos/pay.php
Labels: PR to fix or conflict to solve

#21352 New #19511
  htdocs/core/lib/functions.lib.php
Labels: PR postponed

#21198 NEW: Add new hook for show virtual stock details on product stock card
  htdocs/product/stock/product.php
Labels: PR postponed

#21175 NEW : TAKEPOS-Add setup parameters
  htdocs/langs/en_US/cashdesk.lang
  htdocs/langs/fr_FR/cashdesk.lang
  htdocs/takepos/admin/appearance.php
Labels: PR postponed

#20468 FIX - Case of invoice situation at 100% with a credit note
  htdocs/compta/facture/class/facture.class.php
Labels: PR to merge

#21412 Membership rework
  htdocs/adherents/card.php
  htdocs/adherents/class/adherent_type.class.php
  htdocs/adherents/type.php
  htdocs/core/lib/payments.lib.php
  htdocs/core/triggers/interface_50_modAgenda_ActionsAuto.class.php
  htdocs/install/mysql/migration/16.0.0-17.0.0.sql
  htdocs/langs/en_US/agenda.lang
  htdocs/langs/en_US/install.lang
  htdocs/langs/en_US/members.lang
  htdocs/langs/en_US/paypal.lang
  htdocs/langs/fr_FR/members.lang
  htdocs/public/members/new.php
  htdocs/public/payment/newpayment.php
  htdocs/public/payment/paymentok.php
Labels: PR to merge

#21499 FIX load product stock in inventory lines
  htdocs/product/inventory/inventory.php
Labels: Discussion

#21334 clone button on tasks
  htdocs/projet/tasks/task.php
Labels: PR to fix or conflict to solve

#21522 NEW: hook to modify supplier product html select
  htdocs/core/class/html.form.class.php
Labels: Discussion

#21514 Add search on member nature morphy
  htdocs/adherents/list.php
Labels: Discussion

#21476 FIX permissions création d'absence
  htdocs/holiday/card.php
Labels: PR to fix or conflict to solve

#21567 FIX #21518
  htdocs/societe/card.php
Labels: PR to fix or conflict to solve

#21502 NEW hook formConfirm on action comm card
  htdocs/comm/action/card.php
Labels: Discussion

#21450 NEW substitue project title in mail template
  htdocs/core/lib/functions.lib.php
Labels: Discussion

#21232 php V8 warning
  htdocs/admin/modulehelp.php
Labels: Discussion

#20625 NEW Can use products categories to make inventory
  htdocs/core/actions_addupdatedelete.inc.php
  htdocs/core/class/commonobject.class.php
  htdocs/install/mysql/migration/16.0.0-17.0.0.sql
  htdocs/install/mysql/tables/llx_inventory-stock.sql
  htdocs/langs/en_US/products.lang
  htdocs/langs/fr_FR/products.lang
  htdocs/product/inventory/class/inventory.class.php
Labels: PR to merge

#21570 FIX : Yogosha report 11874 js injection in stockmovement.php
  htdocs/product/stock/massstockmove.php
Labels: PR to merge (after fix suggested)

#21363 adding dropdown menu in case of a lot of buttons in project
  htdocs/core/lib/functions.lib.php
  htdocs/projet/card.php
Labels: PR to fix or conflict to solve

#21431 NEW : Recurrent events on agenda v1
  htdocs/comm/action/card.php
  htdocs/langs/en_US/agenda.lang
  htdocs/langs/fr_FR/agenda.lang
Labels: PR to fix or conflict to solve

#21615 NEW - FTP lib
  htdocs/core/lib/ftp.lib.php
  htdocs/ftp/index.php
  htdocs/langs/en_US/companies.lang
  htdocs/langs/en_US/other.lang
  htdocs/langs/fr_FR/companies.lang
Labels: PR to fix or conflict to solve
