Repository Dolibarr/dolibarr, pull requests merged in 2023-11, with the labels that each got.

#26394 Fix list agenda
  htdocs/comm/action/list.php
  htdocs/compta/bank/treso.php
  htdocs/hrm/skill_card.php
  htdocs/product/stock/stockatdate.php
Labels: PR to fix or conflict to solve

#25931 [modulebuilder] FIX handling of the $filter parameter in fetchAll() method
  htdocs/core/class/conf.class.php
  htdocs/modulebuilder/template/class/myobject.class.php
Labels: Bug, Code enhancement, PR to fix or conflict to solve

#26456 Fix #26050 #26225 and fiscal year report
  htdocs/compta/resultat/clientfourn.php
Labels: PR needs feedback

#26462 Fix Bad Behaviour using custom constant STOCK_UPDATE_AWP_EVEN_WHEN_ENTRY_PRICE_IS_NULL
  htdocs/product/stock/class/mouvementstock.class.php
Labels: PR to fix or conflict to solve

#26120 Unit Management for MO lines
  htdocs/bom/bom_card.php
  htdocs/bom/class/bom.class.php
  htdocs/bom/tpl/objectline_edit.tpl.php
  htdocs/bom/tpl/objectline_view.tpl.php
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
  htdocs/install/mysql/tables/llx_mrp_production.sql
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_production.php
  htdocs/mrp/tpl/originproductline.tpl.php
Labels: PR to fix or conflict to solve

#26466 Fix some warnings -technical debt-
  htdocs/commande/class/commande.class.php
  htdocs/compta/bank/class/account.class.php
  htdocs/compta/bank/class/paymentvarious.class.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/prelevement.php
  htdocs/compta/localtax/class/localtax.class.php
  htdocs/compta/prelevement/create.php
  htdocs/core/class/commoninvoice.class.php
Labels: PR to fix or conflict to solve

#26078 NEW functionality for request_transfer
  htdocs/compta/paymentbybanktransfer/index.php
  htdocs/compta/prelevement/card.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/create.php
  htdocs/compta/prelevement/demandes.php
  htdocs/compta/prelevement/factures.php
  htdocs/core/lib/prelevement.lib.php
  htdocs/core/lib/salaries.lib.php
  htdocs/langs/en_US/bills.lang
  htdocs/langs/en_US/main.lang
  htdocs/langs/en_US/salaries.lang
  htdocs/langs/en_US/withdrawals.lang
  htdocs/langs/fr_FR/bills.lang
  htdocs/langs/fr_FR/main.lang
  htdocs/langs/fr_FR/salaries.lang
  htdocs/langs/fr_FR/withdrawals.lang
  htdocs/salaries/card.php
  htdocs/salaries/class/salary.class.php
  htdocs/salaries/virement_request.php
Labels: Priority - High / Blocking, PR OK to merge (but suggested fix required)

#26426 NEW TakePOS compatibility with lots and serials
  htdocs/takepos/admin/terminal.php
  htdocs/takepos/invoice.php
Labels: Priority - High / Blocking, PR to fix or conflict to solve

#26486 NEW order by batch number in product batch find all method
  htdocs/product/class/productbatch.class.php
Labels: Discussion

#26626 Fix SQL migration 18-19
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
Labels: DevCamp 2023 Lyon

#26627 Fix : missing getEntity for hrm public holiday
  htdocs/core/lib/date.lib.php
Labels: DevCamp 2023 Lyon

#26658 FIX broken feature to show 0 value
  htdocs/admin/const.php
Labels: DevCamp 2023 Lyon

#26630 FIX avoid error during install
  htdocs/install/mysql/data/llx_c_type_container-website.sql
Labels: DevCamp 2023 Lyon

#26662 NEW #26660 [Task] add hook on getNomUrl
  htdocs/projet/class/task.class.php
Labels: DevCamp 2023 Lyon

#26675 Fix : on supplier order, vat for all lines wasn't working with 0 value
  htdocs/fourn/commande/card.php
Labels: DevCamp 2023 Lyon

#26672 Fix tasklist extrafields
  htdocs/core/lib/project.lib.php
  htdocs/projet/class/task.class.php
  htdocs/projet/tasks.php
Labels: DevCamp 2023 Lyon

#26669 NEW #26668 [SQL] add SPL in dict form_juridique
  htdocs/install/mysql/data/llx_c_forme_juridique.sql
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
Labels: DevCamp 2023 Lyon

#26701 Fix strpos inversion for expedition and receipt in files.lib
  htdocs/core/lib/files.lib.php
Labels: DevCamp 2023 Lyon

#26695 undefined fk_parent_line
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: DevCamp 2023 Lyon

#26699 fix:project Class Categerie not found on list project when module categorie is not enabled
  htdocs/projet/list.php
Labels: DevCamp 2023 Lyon

#26700 fix: update setcost_price in htdocs/product/fournisseurs.php
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/fournisseurs.php
Labels: DevCamp 2023 Lyon

#26677 New : option to have the search box in the top menu - manage merge conflict
  htdocs/admin/ihm.php
  htdocs/langs/en_US/admin.lang
  htdocs/main.inc.php
Labels: DevCamp 2023 Lyon

#26696 Fix search dropdown accessibility
  htdocs/main.inc.php
Labels: DevCamp 2023 Lyon

#25859 NEW Accountancy - Added management of tax period closures #FPC21
  htdocs/accountancy/admin/closure.php
  htdocs/accountancy/class/bookkeeping.class.php
  htdocs/accountancy/closure/index.php
  htdocs/accountancy/journal/bankjournal.php
  htdocs/core/menus/init_menu_auguria.sql
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/langs/en_US/accountancy.lang
Labels: Discussion, PR needs feedback, PR to merge

#26712 FIX avoid php8.2 warning : undefined variable
  htdocs/compta/facture/card.php
Labels: DevCamp 2023 Lyon

#26713 Fix: php stan
  htdocs/accountancy/class/accountancyexport.class.php
  htdocs/admin/tools/listevents.php
  htdocs/core/class/CSMSFile.class.php
Labels: DevCamp 2023 Lyon

#26711 FIX sql syntax error
  htdocs/install/mysql/data/llx_c_tva.sql
Labels: DevCamp 2023 Lyon

#26710 New : Authorize credit note to 0
  htdocs/compta/facture/card.php
Labels: DevCamp 2023 Lyon

#26709 Add offset in reserved words for extrafields
  htdocs/core/actions_extrafields.inc.php
Labels: DevCamp 2023 Lyon

#26705 Fix : we can't use the reserved word offset
  htdocs/expensereport/class/expensereport.class.php
Labels: DevCamp 2023 Lyon

#26698 [#26692] Fixed : undefined var on accountacyexport.class.php && factu…
  htdocs/accountancy/class/accountancyexport.class.php
  htdocs/compta/facture/class/facture.class.php
Labels: DevCamp 2023 Lyon

#26694 FIX#25399
  htdocs/mailmanspip/class/mailmanspip.class.php
Labels: DevCamp 2023 Lyon

#26689 FIX : property fichinter
  htdocs/fichinter/class/fichinter.class.php
Labels: DevCamp 2023 Lyon

#26688 Paymentsalary datepayment datep
  htdocs/salaries/card.php
  htdocs/salaries/class/paymentsalary.class.php
  htdocs/salaries/paiement_salary.php
Labels: DevCamp 2023 Lyon

#26690 undef chid from PaymentSalary -> id + deprecated doc
  htdocs/salaries/card.php
  htdocs/salaries/class/paymentsalary.class.php
  htdocs/salaries/paiement_salary.php
Labels: DevCamp 2023 Lyon

#26685 FIX : property author id
  htdocs/delivery/class/delivery.class.php
Labels: DevCamp 2023 Lyon

#26687 Fix : translated product desc was overwriting desc even if text was added after
  htdocs/core/lib/pdf.lib.php
Labels: DevCamp 2023 Lyon

#26679 fix: add /build/phpstan/phpstan/phpstan/vendor/bin and custom bootstrap.php in gitingnore and review README
  .gitignore
  build/phpstan/README
Labels: DevCamp 2023 Lyon

#26636 Fix paymentsalary undef
  htdocs/salaries/class/paymentsalary.class.php
Labels: DevCamp 2023 Lyon

#26723 Dev phpstan
  htdocs/core/class/commonobject.class.php
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: DevCamp 2023 Lyon

#26738 Fix : cost calculation on a bom using workstation
  htdocs/bom/class/bom.class.php
  htdocs/langs/en_US/mrp.lang
  htdocs/mrp/class/mo.class.php
Labels: DevCamp 2023 Lyon

#26737 FIX unused method
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: DevCamp 2023 Lyon

#26686 Fix : right to show suppliers count on thirdparty index
  htdocs/societe/index.php
Labels: Discussion, DevCamp 2023 Lyon

#26721 fix: phpstan
  htdocs/core/class/commoninvoice.class.php
  htdocs/core/class/commonobject.class.php
Labels: DevCamp 2023 Lyon

#26646 fix undef line and action
  htdocs/mrp/class/mo.class.php
Labels: PR to fix or conflict to solve, DevCamp 2023 Lyon

#26720 FIX avoid php8.2 warnings
  htdocs/compta/facture/card.php
  htdocs/core/class/dolgraph.class.php
  htdocs/core/lib/barcode.lib.php
Labels: DevCamp 2023 Lyon

#26683 Finishing auto TakePOS setup with default account
  htdocs/core/modules/modTakePos.class.php
Labels: PR to fix or conflict to solve

#26678 NEW #26676 [MassAction] add missing substitution variables
  htdocs/core/tpl/massactions_pre.tpl.php
Labels: DevCamp 2023 Lyon

#26637 FIX MAIN_LANG_DEFAULT was no longer saved during installation
  htdocs/install/step5.php
Labels: DevCamp 2023 Lyon

#26609 NEW Suggest root path configurations in conf.php.example
  htdocs/conf/conf.php.example
Labels: Discussion

#26736 Replace hook ll header
  ChangeLog
  htdocs/main.inc.php
Labels: DevCamp 2023 Lyon

#26702 fix: comment translation into English
  htdocs/core/modules/project/task/modules_task.php
Labels: PR to fix or conflict to solve, DevCamp 2023 Lyon

#26717 Fix PHP STAN ERROR ON fournisseur commande class
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: PR to fix or conflict to solve, DevCamp 2023 Lyon

#26747 fix some php stan errors
  htdocs/core/class/lessc.class.php
  htdocs/core/class/stats.class.php
  htdocs/core/modules/dons/html_generic.modules.php
  htdocs/core/modules/expedition/doc/pdf_espadon.modules.php
  htdocs/main.inc.php
Labels: PR to fix or conflict to solve, DevCamp 2023 Lyon

#26745 Fix : doxygen : Offset non-falsy-string on array{} in empty() does not exist.
  htdocs/core/class/CMailFile.class.php
Labels: DevCamp 2023 Lyon

#26789 NEW add tpl for delivery
  htdocs/core/lib/functions.lib.php
  htdocs/delivery/class/delivery.class.php
  htdocs/delivery/tpl/linkedobjectblock.tpl.php
Labels: PR postponed

#26826 FIX warning param $lineID getSpecialCode is negatif
  htdocs/core/lib/pdf.lib.php
Labels: PR to fix or conflict to solve

#26825 FIX warning addLine Facture fk_prev_id and situation_percent
  htdocs/compta/facture/card.php
Labels: PR to fix or conflict to solve

#26771 fix fetch vat details not working for some use cases
  htdocs/societe/card.php
  htdocs/societe/checkvat/checkVatGr.php
Labels: PR to fix or conflict to solve

#26742 Closure period - Add information on index & warning on each journal pages
  htdocs/accountancy/index.php
  htdocs/accountancy/journal/bankjournal.php
  htdocs/accountancy/journal/expensereportsjournal.php
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/accountancy/journal/variousjournal.php
  htdocs/langs/en_US/accountancy.lang
Labels: Priority - High / Blocking

#26748 fix: phpstan
  htdocs/fourn/class/fournisseur.facture-rec.class.php
  htdocs/fourn/facture/card-rec.php
  htdocs/fourn/facture/card.php
Labels: PR to fix or conflict to solve, DevCamp 2023 Lyon

#26873 FIX linked files when change ref issue #26844
  htdocs/compta/bank/line.php
  htdocs/langs/en_US/errors.lang
Labels: PR to fix or conflict to solve
