Repository Dolibarr/dolibarr, pull requests merged in 2023-10, with the labels that each got.

#26083 FIX #25127
  htdocs/core/lib/functions.lib.php
Labels: PR to merge (after fix suggested)

#26036 add extrafields and defaulttpldir for hook parameters
  htdocs/core/class/commonobject.class.php
Labels: PR to fix or conflict to solve

#25871 NEW: Retrieve vat details from the Greek Ministry of Finance GSIS SOAP web service and autocomplete third party fields
  htdocs/admin/company.php
  htdocs/langs/en_US/companies.lang
  htdocs/societe/card.php
  htdocs/societe/checkvat/checkVatGr.php
Labels: PR to fix or conflict to solve

#26105 fix #26104 : remove global object
  htdocs/core/lib/signature.lib.php
Labels: PR to fix or conflict to solve

#22573 Close #22571 : order by could be set
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/extrafields.class.php
  htdocs/modulebuilder/template/class/myobject.class.php
Labels: Discussion

#22475 FIX : Propal's negative quantities
  htdocs/comm/propal/card.php
Labels: Discussion

#22502 fix #22501
  htdocs/core/lib/functions.lib.php
Labels: Discussion

#22707 NEW #22626 date filter thirdparties contracts projects
  htdocs/contrat/list.php
  htdocs/projet/list.php
  htdocs/societe/list.php
Labels: PR to fix or conflict to solve

#26160 FIX - Search label or description on list det order
  htdocs/commande/list_det.php
Labels: PR to fix - Continuous Integration Test failed

#26149 [FIX] Warnings in ModuleBuilder Configuration Page
  htdocs/modulebuilder/admin/setup.php
Labels: PR to fix or conflict to solve

#26126 New Add js scanner expedition repartition
  htdocs/core/class/html.formother.class.php
  htdocs/expedition/ajax/searchfrombarcode.php
  htdocs/expedition/dispatch.php
  htdocs/expedition/js/lib_dispatch.js.php
Labels: PR to fix or conflict to solve

#24972 Add events doActions, printFieldListTitle, printFieldListValue to the hookmanager
  htdocs/compta/paiement/card.php
Labels: PR postponed

#26180 FIX: modification of complementary attributes in invoices
  htdocs/compta/facture/card.php
Labels: Discussion

#26177 NEW - Row in list higher height
  htdocs/admin/ihm.php
  htdocs/core/lib/usergroups.lib.php
  htdocs/langs/en_US/admin.lang
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/eldy/style.css.php
  htdocs/theme/eldy/theme_vars.inc.php
  htdocs/theme/md/style.css.php
  htdocs/theme/md/theme_vars.inc.php
Labels: PR needs feedback

#26193 Show product description
  htdocs/product/class/product.class.php
  htdocs/product/list.php
Labels: Discussion

#25375 New | Add AGENDA_SORT_EVENT_TYPE_BY_POSITION_FIRST hidden conf to change sort method of actions
  htdocs/comm/action/class/cactioncomm.class.php
Labels: Works for me / Can't reproduce

#25266 NEW Add more company informations (ProfId7 to 10)
  htdocs/admin/company.php
  htdocs/core/lib/pdf.lib.php
  htdocs/langs/en_US/companies.lang
Labels: Discussion

#25036 NEW Add LANG to ask to create cash account if there is no cash account in TakePOS
  htdocs/langs/en_US/cashdesk.lang
Labels: DevCamp 2023 Bordeaux

#25035 NEW : Library including math and financial functions
  COPYRIGHT
  htdocs/includes/markrogoyski/math-php/CHANGELOG.md
  htdocs/includes/markrogoyski/math-php/LICENSE.txt
  htdocs/includes/markrogoyski/math-php/README.md
  htdocs/includes/markrogoyski/math-php/composer.json
  htdocs/includes/markrogoyski/math-php/src/Exception/BadDataException.php
  htdocs/includes/markrogoyski/math-php/src/Exception/OutOfBoundsException.php
  htdocs/includes/markrogoyski/math-php/src/Finance.php
  htdocs/includes/markrogoyski/math-php/src/NumericalAnalysis/RootFinding/NewtonsMethod.php
  htdocs/includes/markrogoyski/math-php/src/NumericalAnalysis/RootFinding/Validation.php
Labels: DevCamp 2023 Bordeaux

#24971 doActions,printFieldListTitle,printFieldListValue to hookmanager
  htdocs/compta/paiement/card.php
Labels: PR postponed

#24807 NEW : TakePOS - add constant to choose contact instead of customer
  htdocs/contact/list.php
  htdocs/takepos/index.php
  htdocs/takepos/invoice.php
Labels: Discussion

#25220 FIX check tva_tx before comparing price_min_ttc
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
  htdocs/langs/en_US/products.lang
  htdocs/langs/fr_FR/products.lang
Labels: PR OK to merge (but suggested fix required)

#26222 FIX #26195 - Various payment - List of project excluded those assigned to third parties
  htdocs/compta/bank/various_payment/card.php
Labels: Discussion

#23642 NEW: use account address in sepa mandate
  htdocs/core/modules/bank/doc/pdf_sepamandate.modules.php
Labels: Discussion

#26209 NEW show VAT free amount on payment input close #26208
  htdocs/compta/paiement.php
Labels: PR to fix or conflict to solve

#26233 NEW: Invoice subtypes for customers and vendors
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/list.php
  htdocs/core/class/commoninvoice.class.php
  htdocs/core/class/html.form.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/fourn/facture/card.php
  htdocs/fourn/facture/list.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/bills.lang
  htdocs/langs/en_US/main.lang
Labels: PR OK to merge (but suggested fix required)

#26223 FIX #26100 - Ticket - On edit, list of closed project must be excluded
  htdocs/ticket/card.php
Labels: Discussion

#26253 FIX : export separator config with multientity
  htdocs/admin/export.php
Labels: PR to fix or conflict to solve

#25233 FIX #25143 Using default_values for extrafields by replacing GETPOSTISSET by GETPOST
  htdocs/core/class/extrafields.class.php
Labels: PR to fix or conflict to solve

#24856 CLOSE #23331 Add support for parent projects
  htdocs/projet/card.php
  htdocs/projet/class/project.class.php
Labels: PR postponed

#26285 NEW resource improvements - data structure
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
  htdocs/install/mysql/tables/llx_resource.sql
Labels: Discussion

#21691 NEW Can switch product batch management to no management.
  htdocs/langs/en_US/products.lang
  htdocs/langs/en_US/stocks.lang
  htdocs/langs/fr_FR/stocks.lang
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: PR OK to merge (but suggested fix required)

#26298 FIX - param in order list det
  htdocs/commande/list_det.php
Labels: Discussion

#26335 fix: if field is boolean in fileds array, it must be boolean as datatype for PgSQL
  htdocs/install/mysql/tables/llx_asset-asset.sql
  htdocs/install/mysql/tables/llx_asset_depreciation_options_economic-asset.sql
Labels: PR to fix or conflict to solve

#26334 NEW : Add custom Text on footer total
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
Labels: PR to fix or conflict to solve

#26168 FIX - Search product category on list det order
  htdocs/commande/list_det.php
Labels: Discussion

#26263 FIX - Auto fill the field end of period with end of month when cloning a salary
  htdocs/langs/en_US/salaries.lang
  htdocs/langs/fr_FR/salaries.lang
  htdocs/salaries/card.php
Labels: PR to fix or conflict to solve

#26122 NEW - Add edit line on MO
  htdocs/mrp/mo_production.php
Labels: PR to fix or conflict to solve

#24809 FIX : TakePOS - fix option TAKEPOS_PRODUCT_IN_STOCK must read on the POS warehouse
  htdocs/takepos/ajax/ajax.php
Labels: PR to fix or conflict to solve

#25031 NEW Default customer, category and product when enable TakePOS
  htdocs/core/modules/modTakePos.class.php
  htdocs/langs/en_US/cashdesk.lang
Labels: PR OK to merge (but suggested fix required), DevCamp 2023 Bordeaux

#26345 New: Adding the PDF option displaying the product's barcode number
  htdocs/admin/pdf.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/core/lib/pdf.lib.php
  htdocs/expedition/class/expedition.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: PR OK to merge (but suggested fix required)

#26347 Qual cleaner code for InterfaceLogevents
  htdocs/admin/tools/listevents.php
  htdocs/core/class/events.class.php
  htdocs/core/triggers/interface_20_all_Logevents.class.php
  htdocs/langs/en_US/users.lang
Labels: PR to fix or conflict to solve

#23002 FIX: update product with stock to lot or serial type.
  htdocs/expedition/card.php
  htdocs/langs/en_US/productbatch.lang
  htdocs/product/class/product.class.php
  htdocs/product/reassortlot.php
  htdocs/product/stock/product.php
Labels: PR to fix or conflict to solve, DevCamp 2022 Nantes, DevCamp 2023 Germany

#26181 FIX : HTML in ODT templates
  htdocs/includes/odtphp/odf.php
Labels: PR to fix or conflict to solve

#26102 NEW add recursive deletion option for child m os
  htdocs/langs/en_US/mrp.lang
  htdocs/langs/fr_FR/mrp.lang
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_card.php
Labels: PR to fix or conflict to solve
