Repository Dolibarr/dolibarr, pull requests merged in 2023-04, with the labels that each got.

#22940 NEW: Add Customer Order delivered (ORDER_CLOSE) in module Notification
  htdocs/core/class/notify.class.php
  htdocs/langs/en_US/other.lang
  htdocs/langs/fr_FR/other.lang
Labels: PR to merge

#19642 NEW : add margin in paiement/card.php
  htdocs/compta/paiement/card.php
Labels: PR postponed

#22583 new: add information of line detail origin and source into stock mouvement
  htdocs/expedition/class/expedition.class.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: Discussion

#24246 FIX : Fix case when the value of a extrafields of the type 'boolean', 'select' or other have an option with a value equal to '0'.
  htdocs/core/tpl/extrafields_list_search_input.tpl.php
Labels: Discussion

#19929 Of consumption select batch and warehouse
  htdocs/mrp/ajax/interface.php
  htdocs/mrp/mo_production.php
  htdocs/product/class/html.formproduct.class.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#18173 Warehouse tags in reassortlot
  htdocs/product/reassortlot.php
Labels: Discussion

#22892 FIX: Set extrafield value of multiselect type
  htdocs/core/class/commonobject.class.php
Labels: PR to fix or conflict to solve

#22741 NEW #22740 Add OpenID Connect impl
  htdocs/core/login/functions_openid_connect.php
Labels: Pending analysis of PR

#24361 FIX : No usage of the function updateProduction in the update function
  htdocs/mrp/class/mo.class.php
  htdocs/mrp/mo_card.php
Labels: Discussion, PR to fix - Continuous Integration Test failed

#24582 PHP8 compatibility
  htdocs/core/lib/bank.lib.php
  htdocs/core/tpl/objectline_view.tpl.php
  htdocs/margin/agentMargins.php
Labels: PR to fix or conflict to solve

#24483 The deposit and replacement invoice types are not allowed in Greece.
  htdocs/master.inc.php
Labels: Discussion

#24583 Prevent PHP Warning in error log file, when the generated doc file does not exists.
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#24595 fix warning PHP8.1
  htdocs/core/lib/company.lib.php
Labels: Discussion
