Repository Dolibarr/dolibarr, pull requests merged in 2023-01, with the labels that each got.

#22945 NEW - add hook 'llxFooter'
  htdocs/core/class/hookmanager.class.php
  htdocs/main.inc.php
Labels: PR to merge, PR postponed

#23335 FIX #23334 Price equivalent for minimum price check
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
Labels: Discussion

#23256 NEW category of operation for crabe PDF model
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
Labels: Priority - High / Blocking

#23416 Fix: #23415 REST BOM API - It's able to have a wrong value on the 'ref' Field
  htdocs/bom/class/api_boms.class.php
Labels: PR to fix or conflict to solve

#23440 NEW Accountancy - Add an option to disable autolettering when transferring to accounting
  htdocs/accountancy/admin/index.php
  htdocs/accountancy/journal/bankjournal.php
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR to merge

#23417 correction bug sur le filtre des langues pour l'ajout aux liste d'ema…
  htdocs/core/modules/mailings/contacts1.modules.php
Labels: PR to fix or conflict to solve

#22913 NEW : Now we can edit amount on vat and salaries clone action
  htdocs/compta/tva/card.php
  htdocs/salaries/card.php
Labels: PR postponed, PR to fix or conflict to solve

#22869 NEW hook printFieldListFrom in contact list
  htdocs/contact/list.php
Labels: PR postponed

#22756 FIX: Reload page on supplier change and keeping the values
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
Labels: PR postponed

#21596 NEW - List product in orders
  htdocs/commande/list_det.php
  htdocs/core/menus/init_menu_auguria.sql
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/langs/en_US/orders.lang
Labels: PR to merge, PR postponed

#21196 NEW Accountancy - Manage customer retained warranty FPC21+
  htdocs/accountancy/admin/defaultaccounts.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/langs/en_US/accountancy.lang
Labels: Discussion, PR postponed

#23254 NEW Kanban view for list of adherents
  htdocs/adherents/class/adherent.class.php
  htdocs/adherents/list.php
Labels: PR to fix or conflict to solve

#21528 FIX contacts disabled are not returned on create invoice
  htdocs/contact/class/contact.class.php
Labels: PR to fix or conflict to solve

#23217 16.0 FIX Bom Calculate Price
  htdocs/bom/class/bom.class.php
  htdocs/bom/tpl/objectline_view.tpl.php
Labels: PR to fix or conflict to solve

#23143 NEW|New [Bulk delete Project tasks]
  htdocs/core/actions_massactions.inc.php
  htdocs/core/lib/project.lib.php
  htdocs/core/tpl/massactions_pre.tpl.php
  htdocs/langs/en_US/main.lang
  htdocs/langs/en_US/projects.lang
  htdocs/projet/tasks.php
Labels: Discussion

#23071 NEW operation type in email collector to load or create contact
  htdocs/admin/emailcollector_card.php
  htdocs/emailcollector/class/emailcollector.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: PR postponed

#23500 fix properties
  htdocs/core/class/html.formticket.class.php
Labels: Discussion

#23125 New mode kaban for products list
  htdocs/product/class/product.class.php
  htdocs/product/list.php
  htdocs/theme/eldy/info-box.inc.php
Labels: PR postponed

#23554 Fix modify style for checkbox #23547
  htdocs/hrm/class/job.class.php
  htdocs/theme/eldy/info-box.inc.php
Labels: PR to merge (after fix suggested)

#23550 NEW kanban for post employees list
  htdocs/hrm/class/position.class.php
  htdocs/hrm/position_list.php
Labels: PR to fix or conflict to solve

#23296 FIX : Product list in setup.php in new Module
  htdocs/core/class/html.formsetup.class.php
  htdocs/modulebuilder/template/admin/setup.php
Labels: Discussion

#23085 NEW Add date due and labels into customer comm card
  htdocs/comm/card.php
Labels: PR postponed

#23670 Encase database name in backticks
  htdocs/core/db/mysqli.class.php
Labels: Discussion
