Repository Dolibarr/dolibarr, pull requests merged in 2023-08, with the labels that each got.

#25531 FIX - database last_main_doc for user
  htdocs/install/mysql/migration/16.0.0-17.0.0.sql
  htdocs/install/mysql/tables/llx_user.sql
Labels: PR to fix or conflict to solve

#25180 NEW added barcode as a filter inside the export
  htdocs/core/modules/modStock.class.php
Labels: PR postponed

#25052 NEW 24318 Add Rotate_Image_Button in Preview
  htdocs/core/js/lib_head.js.php
  htdocs/langs/en_US/main.lang
  htdocs/langs/fr_FR/main.lang
Labels: PR postponed, DevCamp 2023 Bordeaux

#24915 NEW: Add hooks on import, step 5 - 6
  htdocs/imports/import.php
Labels: PR postponed

#25080 NEW: Add get_substitutionarray_other() on shipping odt
  htdocs/core/modules/expedition/doc/doc_generic_shipment_odt.modules.php
Labels: PR postponed

#25592 Add new dictionary for modulebuilder
  htdocs/core/lib/modulebuilder.lib.php
  htdocs/langs/en_US/errors.lang
  htdocs/langs/en_US/modulebuilder.lang
  htdocs/langs/fr_FR/errors.lang
  htdocs/langs/fr_FR/modulebuilder.lang
  htdocs/modulebuilder/index.php
Labels: PR to fix or conflict to solve

#25503 Update interface_20_all_Logevents.class.php
  htdocs/core/triggers/interface_20_all_Logevents.class.php
Labels: Discussion

#25537 FIX_reload_linked_objects_on_propal_closeas
  htdocs/comm/propal/card.php
Labels: Discussion

#25588 NEW no need to create invoice supplier object on supplier card for standalone credit note
  htdocs/fourn/facture/card.php
Labels: Discussion

#25577 NEW add Ticket tab on contract
  htdocs/contrat/class/contrat.class.php
  htdocs/contrat/ticket.php
  htdocs/core/class/html.formticket.class.php
  htdocs/core/lib/contract.lib.php
  htdocs/ticket/card.php
  htdocs/ticket/class/ticket.class.php
  htdocs/ticket/list.php
Labels: PR to merge (after fix suggested)

#25509 NEW add and list external contributors on ticket public interface
  htdocs/langs/en_US/ticket.lang
  htdocs/langs/fr_FR/ticket.lang
  htdocs/public/ticket/view.php
Labels: PR to merge (after fix suggested)

#25492 Fix count cronjoblist
  htdocs/cron/list.php
Labels: PR to fix or conflict to solve

#25398 NEW Upgrade in module builder in menu section
  htdocs/core/lib/modulebuilder.lib.php
  htdocs/modulebuilder/index.php
  htdocs/theme/eldy/global.inc.php
Labels: PR to fix or conflict to solve, PR to merge (after fix suggested)

#20144 NEW : Include sub warehouse in inventory
  htdocs/core/actions_addupdatedelete.inc.php
  htdocs/langs/en_US/stocks.lang
  htdocs/langs/fr_FR/stocks.lang
  htdocs/product/inventory/card.php
  htdocs/product/inventory/class/inventory.class.php
  htdocs/product/inventory/inventory.php
Labels: PR to merge

#20676 NEW : add parent product column on list
  htdocs/product/list.php
Labels: Discussion

#25644 NEW #25379 Add a public page to contact company (record a prospect)
  htdocs/langs/en_US/companies.lang
  htdocs/public/company/new.php
Labels: PR to fix or conflict to solve

#25084 NEW Add possibility to choose separator #21426
  htdocs/core/class/html.form.class.php
  htdocs/core/class/html.formfile.class.php
  htdocs/core/modules/export/modules_export.php
  htdocs/exports/class/export.class.php
  htdocs/exports/export.php
Labels: PR to fix or conflict to solve

#25681 FIX: review quality managment on product lot
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
  htdocs/install/mysql/tables/llx_product_lot.sql
  htdocs/product/stock/class/productlot.class.php
  htdocs/product/stock/productlot_card.php
  htdocs/product/stock/stats/commande_fournisseur.php
  htdocs/product/stock/stats/expedition.php
  htdocs/product/stock/stats/reception.php
Labels: PR to fix or conflict to solve, PR mixing structure and code change
