Repository Dolibarr/dolibarr, pull requests merged in 2023-06, with the labels that each got.

#24931 NEW: add field 'ref' (of supplier product) for import supplier PO lines
  htdocs/core/modules/modFournisseur.class.php
Labels: PR to merge (after fix suggested)

#24934 FIX : Add/Update required modules for thirdparties (by categ) & partnership
  htdocs/core/modules/mailings/partnership.modules.php
Labels: PR to fix or conflict to solve

#24909 Filter child projects out of project list.
  htdocs/projet/list.php
Labels: PR to fix or conflict to solve

#25009 Fix mails template list colspan when no records
  htdocs/admin/mails_templates.php
Labels: DevCamp 2023 Bordeaux

#23745 FIX: Homogenise handling of null extrafield value in create/update
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#25004 Fix : webhook object creation
  htdocs/webhook/class/target.class.php
Labels: DevCamp 2023 Bordeaux

#25003 FIX Donation - Missing Language key
  htdocs/langs/en_US/donations.lang
Labels: DevCamp 2023 Bordeaux

#25001 FIX #24985 Societe - Function thirdparty merging not working with module whose tables are not deployed by default
  htdocs/societe/card.php
Labels: DevCamp 2023 Bordeaux

#24993 Fix #24953 : Call to udefined pages in hrm.lib.php
  htdocs/core/lib/hrm.lib.php
Labels: DevCamp 2023 Bordeaux

#24938 fix: display budget field on load project
  htdocs/projet/card.php
Labels: Discussion

#25016 FIX #24695
  htdocs/langs/en_US/ticket.lang
Labels: DevCamp 2023 Bordeaux

#25034 FIX: Bump length of llx_reception.ref_supplier to 255
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/install/mysql/tables/llx_reception.sql
Labels: DevCamp 2023 Bordeaux

#24996 FIX #24756 Total sum on annual report bank
  htdocs/compta/bank/annuel.php
Labels: DevCamp 2023 Bordeaux

#25045 Fix : user pages on empty $id
  htdocs/user/agenda_extsites.php
  htdocs/user/document.php
  htdocs/user/info.php
  htdocs/user/note.php
  htdocs/user/notify/card.php
  htdocs/user/param_ihm.php
Labels: DevCamp 2023 Bordeaux

#25055 FIX #24631 Filter on categories of warehouses faulty
  htdocs/product/stock/list.php
Labels: DevCamp 2023 Bordeaux

#25054 fix: css declaration
  htdocs/theme/eldy/global.inc.php
Labels: DevCamp 2023 Bordeaux

#25072 fix: missing key 1 warning
  htdocs/core/actions_extrafields.inc.php
Labels: DevCamp 2023 Bordeaux

#25071 Fix #23740 ticket stats can't show amounts
  htdocs/ticket/stats/index.php
Labels: DevCamp 2023 Bordeaux

#25061 Fix : qodana script errors
  .gitignore
  scripts/bank/export-bank-receipts.php
  scripts/invoices/email_unpaid_invoices_to_representatives.php
  scripts/invoices/rebuild_merge_pdf.php
  scripts/members/sync_members_ldap2dolibarr.php
Labels: DevCamp 2023 Bordeaux

#25059 FIX: ModuleBuilder admin setup numbering rules
  htdocs/modulebuilder/template/admin/setup.php
Labels: DevCamp 2023 Bordeaux

#25070 Fix #23806 use dictionary position to display contact type list
  htdocs/projet/activity/perday.php
  htdocs/projet/activity/permonth.php
  htdocs/projet/activity/perweek.php
  htdocs/projet/tasks/contact.php
Labels: DevCamp 2023 Bordeaux

#25058 Fix #23822 virtualstock calculation with credit note
  htdocs/product/class/product.class.php
Labels: DevCamp 2023 Bordeaux

#25057 FIX Accountancy - Closure - Button is hidden...
  htdocs/accountancy/closure/index.php
  htdocs/langs/en_US/accountancy.lang
Labels: DevCamp 2023 Bordeaux

#25056 FIX #24569 filters on stockadate page
  htdocs/product/stock/stockatdate.php
Labels: DevCamp 2023 Bordeaux

#25032 FIX: Duplicate reference in llx_commande_fournisseur
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/install/mysql/tables/llx_commande_fournisseur.key.sql
  htdocs/install/repair.php
Labels: DevCamp 2023 Bordeaux

#24959 fixing the total ttc in the multicurrency section
  htdocs/fourn/commande/card.php
Labels: Discussion

#25206 FIX : Can update extrafield of expedition det with lot
  htdocs/expedition/card.php
Labels: Discussion
