Repository Dolibarr/dolibarr, pull requests merged in 2023-07, with the labels that each got.

#25228 add call_trigger variable
  htdocs/contact/class/contact.class.php
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve

#25161 Edit the status prospect
  htdocs/core/ajax/ajaxstatusprospect.php
  htdocs/core/class/html.formcompany.class.php
Labels: PR to fix or conflict to solve

#25232 Fix : some dolibarr log warnings
  htdocs/expensereport/payment/list.php
  htdocs/fourn/facture/list.php
  htdocs/fourn/paiement/list.php
Labels: PR to fix or conflict to solve

#25203 NEW do not add default value in list
  htdocs/core/class/html.form.class.php
Labels: Discussion

#25270 NEW #24085 Add the Project filter
  htdocs/product/stock/movement_list.php
Labels: PR postponed

#25247 NEW add contract link on ticket
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
  htdocs/install/mysql/tables/llx_ticket-ticket.sql
Labels: PR postponed

#25135 Fix:warehouses table name is entrepot which does not hold an fk_soc field, so _checkAccessToResource returns always false and must be disabled before fix.
  htdocs/product/stock/class/api_warehouses.class.php
Labels: PR to fix or conflict to solve

#25326 Fix : bookcal database structure
  htdocs/bookcal/class/booking.class.php
  htdocs/install/mysql/tables/llx_bookcal_booking-bookcal.sql
Labels: Discussion

#25332 qodana fix 3 : missing returns
  htdocs/admin/sms.php
  htdocs/comm/action/class/cactioncomm.class.php
  htdocs/comm/mailing/class/advtargetemailing.class.php
  htdocs/core/class/CSMSFile.class.php
  htdocs/core/class/html.formcontract.class.php
  htdocs/core/class/html.formexpensereport.class.php
  htdocs/core/class/html.formfile.class.php
  htdocs/core/class/rssparser.class.php
  htdocs/core/class/translate.class.php
  htdocs/core/lib/functions2.lib.php
  htdocs/core/lib/functionsnumtoword.lib.php
  htdocs/core/lib/security.lib.php
  htdocs/hrm/class/skill.class.php
Labels: PR to fix or conflict to solve

#24557 FIX display project tasks list columns
  htdocs/core/lib/project.lib.php
Labels: PR to fix or conflict to solve

#25443 16.0 urgent fix societe class
  htdocs/societe/class/societe.class.php
Labels: Priority - High / Blocking

#25396 FIX: Update mouvementstock.class.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: PR to fix or conflict to solve

#25347 qodana fix 5 : missing returns
  htdocs/accountancy/class/accountingjournal.class.php
  htdocs/contrat/class/contrat.class.php
  htdocs/emailcollector/class/emailcollectoraction.class.php
  htdocs/emailcollector/class/emailcollectorfilter.class.php
  htdocs/projet/class/task.class.php
Labels: PR to fix or conflict to solve

#25461 NEW Add more information to holiday mailings
  htdocs/holiday/card.php
  htdocs/holiday/card_group.php
Labels: PR to fix or conflict to solve

#25334 qodana fix 4: missing returns
  htdocs/asset/class/assetaccountancycodes.class.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/prelevement/class/ligneprelevement.class.php
  htdocs/compta/sociales/class/cchargesociales.class.php
  htdocs/compta/sociales/class/chargesociales.class.php
  htdocs/core/lib/functionsnumtoword.lib.php
  htdocs/core/modules/action/rapport.class.php
  htdocs/core/modules/bank/doc/pdf_ban.modules.php
  htdocs/core/modules/expensereport/doc/pdf_standard.modules.php
  htdocs/core/modules/facture/mod_facture_mars.php
  htdocs/core/modules/mailings/advthirdparties.modules.php
  htdocs/core/modules/supplier_invoice/doc/pdf_canelle.modules.php
  htdocs/core/modules/supplier_payment/doc/pdf_standard.modules.php
  htdocs/core/modules/takepos/mod_takepos_ref_simple.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.commande.dispatch.class.php
Labels: PR to fix or conflict to solve

#25384 FIX Fatal Error PHP 8 : division by 0
  htdocs/bom/tpl/objectline_view.tpl.php
Labels: Discussion

#18600 New : add a dashboard showing number of orders to bill #17963
  htdocs/commande/class/commande.class.php
  htdocs/commande/list.php
  htdocs/index.php
Labels: Discussion, PR postponed
