Repository Dolibarr/dolibarr, pull requests merged in 2024-02, with the labels that each got.

#27940 Qual ldap class phpcs
  ChangeLog
  htdocs/adherents/ldap.php
  htdocs/adherents/type_ldap.php
  htdocs/admin/ldap.php
  htdocs/admin/ldap_contacts.php
  htdocs/admin/ldap_groups.php
  htdocs/admin/ldap_members.php
  htdocs/admin/ldap_members_types.php
  htdocs/admin/ldap_users.php
  htdocs/contact/ldap.php
  htdocs/core/class/ldap.class.php
  htdocs/core/login/functions_ldap.php
  htdocs/core/triggers/interface_50_modLdap_Ldapsynchro.class.php
  htdocs/user/card.php
  htdocs/user/group/ldap.php
  htdocs/user/ldap.php
  scripts/company/sync_contacts_dolibarr2ldap.php
  scripts/members/sync_members_dolibarr2ldap.php
  scripts/members/sync_members_ldap2dolibarr.php
  scripts/members/sync_members_types_dolibarr2ldap.php
  scripts/members/sync_members_types_ldap2dolibarr.php
  scripts/user/sync_groups_dolibarr2ldap.php
  scripts/user/sync_groups_ldap2dolibarr.php
  scripts/user/sync_users_dolibarr2ldap.php
  scripts/user/sync_users_ldap2dolibarr.php
Labels: PR to fix or conflict to solve

#26756 New add Messages Tab on Contract View
  htdocs/contrat/agenda.php
  htdocs/contrat/card.php
  htdocs/contrat/messaging.php
Labels: PR to fix or conflict to solve

#26982 NEW Asset Module - make asset model creation in a single step
  htdocs/asset/accountancy_codes.php
  htdocs/asset/class/asset.class.php
  htdocs/asset/class/assetaccountancycodes.class.php
  htdocs/asset/class/assetdepreciationoptions.class.php
  htdocs/asset/class/assetmodel.class.php
  htdocs/asset/depreciation_options.php
  htdocs/asset/model/accountancy_codes.php
  htdocs/asset/model/agenda.php
  htdocs/asset/model/card.php
  htdocs/asset/model/depreciation_options.php
  htdocs/asset/model/note.php
  htdocs/asset/tpl/accountancy_codes_edit.tpl.php
  htdocs/asset/tpl/accountancy_codes_view.tpl.php
  htdocs/asset/tpl/depreciation_options_edit.tpl.php
  htdocs/asset/tpl/depreciation_options_view.tpl.php
  htdocs/core/lib/asset.lib.php
Labels: PR to fix - Continuous Integration Test failed

#27947 Close #27774 new contact in project
  htdocs/core/tpl/contacts.tpl.php
  htdocs/langs/en_US/errors.lang
  htdocs/projet/contact.php
Labels: Discussion

#27943 NEW api_thirdparties add and delete representatives
  htdocs/societe/class/api_thirdparties.class.php
Labels: Discussion

#27861 Close #27777 : new massaction subscription creation
  htdocs/adherents/list.php
  htdocs/langs/en_US/members.lang
Labels: PR to fix or conflict to solve

#27856 New intervention signed status data structure
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_fichinter.sql
Labels: PR to fix or conflict to solve

#27855 NEW supplier order submit method message
  htdocs/core/triggers/interface_50_modAgenda_ActionsAuto.class.php
  htdocs/langs/en_US/orders.lang
Labels: Discussion

#27884 Fix some phpstan warnings
  htdocs/adherents/class/subscription.class.php
  htdocs/api/class/api_access.class.php
  htdocs/bom/class/bom.class.php
  htdocs/bom/tpl/objectline_view.tpl.php
  htdocs/bookmarks/class/bookmark.class.php
Labels: Discussion

#27997 Update dbtable dump
  htdocs/admin/system/dbtable.php
Labels: PR to fix or conflict to solve

#27927 Simpler version of getRootURLFromURL
  htdocs/core/lib/geturl.lib.php
Labels: Discussion

#28040 New make replyto as origin_email email collector ticket part
  htdocs/core/class/html.formticket.class.php
  htdocs/emailcollector/class/emailcollector.class.php
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_ticket-ticket.sql
  htdocs/ticket/class/ticket.class.php
Labels: PR to fix or conflict to solve

#27668 Replenish : Calcul virtual stock by warehouse
  htdocs/product/class/product.class.php
  htdocs/product/stock/replenish.php
Labels: PR OK to merge (but suggested fix required)

#27184 New import actioncomm and add fields to export
  htdocs/core/modules/import/import_csv.modules.php
  htdocs/core/modules/modAgenda.class.php
  htdocs/langs/en_US/agenda.lang
  htdocs/langs/en_US/main.lang
Labels: PR to fix - Continuous Integration Test failed

#28012 fix: auto generated user login 'undefined' appears on login input)[fi…
  htdocs/user/card.php
Labels: PR to fix or conflict to solve

#28091 Fix MAIN_MAIL_FORCE_NOT_SENDING_TO_REPLACE send protection
  htdocs/core/class/CMailFile.class.php
Labels: Discussion

#28079 Qual: ci: Run pre-commit/php-cs with cache
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  dev/setup/codesniffer/ruleset.xml
Labels: Discussion

#27066 FIX default value for radio extrafield (v17+)
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#28117 qual: phpstan for htdocs/holiday/class/holiday.class.php
  htdocs/holiday/class/holiday.class.php
Labels: PR to fix or conflict to solve

#24681 New: add hooks to apply cash discount agreements
  htdocs/compta/facture/class/api_invoices.class.php
  htdocs/compta/facture/list.php
  htdocs/compta/facture/prelevement.php
  htdocs/fourn/class/api_supplier_invoices.class.php
  htdocs/fourn/facture/list.php
Labels: Discussion

#27247 NEW #24031 add option MAIN_GRANDTOTAL_LIST_SHOW to always show grand total to lists
  htdocs/admin/ihm.php
  htdocs/core/tpl/list_print_total.tpl.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/main.lang
  htdocs/langs/fr_FR/admin.lang
  htdocs/langs/fr_FR/main.lang
Labels: PR to fix or conflict to solve

#27240 NEW: Automatically fill matching extra fields of object on line creation.
  htdocs/core/tpl/objectline_create.tpl.php
Labels: Pending analysis of PR

#27049 CLOSE #27048 add form to globally set "VARIANT_ALLOW_STOCK_MOVEMENT_ON_VARIANT_PARENT" variable
  htdocs/langs/en_US/products.lang
  htdocs/variants/admin/admin.php
Labels: PR OK to merge

#28132 outputlangs must not be a string as default value like others generat…
  htdocs/delivery/class/delivery.class.php
  htdocs/product/stock/class/entrepot.class.php
  htdocs/product/stock/class/mouvementstock.class.php
Labels: PR to fix or conflict to solve

#28119 qual: phpstan for htdocs/loan/class/loanschedule.class.php
  htdocs/loan/class/loanschedule.class.php
Labels: Discussion

#27864 Qual clean dolresource
  htdocs/resource/class/dolresource.class.php
Labels: Discussion

#27930 FIX #26920 replace fk_statut by status
  htdocs/projet/activity/index.php
  htdocs/projet/class/task.class.php
  htdocs/projet/tasks/list.php
Labels: PR to fix or conflict to solve

#28236 Qual: Improve rendering of phpstan technical debt table in apstats.
  dev/tools/apstats.php
Labels: PR to fix or conflict to solve

#28143 Fix: PhanParamSignatureMismatch
  .pre-commit-config.yaml
  htdocs/core/modules/member/doc/doc_generic_member_odt.class.php
  htdocs/core/modules/project/doc/doc_generic_project_odt.modules.php
  htdocs/core/modules/project/task/doc/doc_generic_task_odt.modules.php
  htdocs/core/modules/ticket/doc/doc_generic_ticket_odt.modules.php
  htdocs/core/modules/user/doc/doc_generic_user_odt.modules.php
Labels: Discussion

#27968 Qual clean dolibarrtriggers
  ChangeLog
  htdocs/core/triggers/dolibarrtriggers.class.php
  htdocs/core/triggers/interface_20_all_Logevents.class.php
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
  htdocs/core/triggers/interface_50_modAgenda_ActionsAuto.class.php
  htdocs/core/triggers/interface_50_modBlockedlog_ActionsBlockedLog.class.php
  htdocs/core/triggers/interface_50_modEventOrganization_EventOrganization.class.php
  htdocs/core/triggers/interface_50_modLdap_Ldapsynchro.class.php
  htdocs/core/triggers/interface_50_modMailmanspip_Mailmanspipsynchro.class.php
  htdocs/core/triggers/interface_50_modNotification_Notification.class.php
  htdocs/core/triggers/interface_50_modTicket_TicketEmail.class.php
  htdocs/core/triggers/interface_80_modStripe_Stripe.class.php
  htdocs/core/triggers/interface_90_modSociete_ContactRoles.class.php
  htdocs/core/triggers/interface_95_modWebhook_WebhookTriggers.class.php
  htdocs/core/triggers/interface_95_modZapier_ZapierTriggers.class.php
  htdocs/modulebuilder/template/core/triggers/interface_99_modMyModule_MyModuleTriggers.class.php
Labels: Discussion

#26854 New POS admin setting to disable sales to the default customer
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/cashdesk.lang
  htdocs/takepos/admin/terminal.php
  htdocs/takepos/index.php
Labels: PR postponed

#25126 NEW: API Add some api endpoints
  htdocs/compta/bank/class/account.class.php
  htdocs/compta/bank/class/api_bankaccounts.class.php
  htdocs/core/lib/functions2.lib.php
  htdocs/expensereport/class/api_paymentexpensereports.class.php
  htdocs/salaries/class/api_paymentsalaries.class.php
  htdocs/salaries/class/api_salaries.class.php
Labels: PR to fix or conflict to solve

#28291 qual: phpstan for htdocs/salaries/class/paymentsalary.class.php
  htdocs/salaries/class/paymentsalary.class.php
Labels: Discussion

#28307 Update phpunit.bat sample script and setup_conf.sh
  dev/setup/phpunit/PHPUNIT.BAT
  dev/setup/phpunit/setup_conf.sh
  dev/tools/codespell/codespell-lines-ignore.txt
Labels: Discussion

#28308 Qual clean dolresource class
  htdocs/core/class/commonpeople.class.php
  htdocs/resource/class/dolresource.class.php
Labels: Discussion

#28297 Fix: Allow new & old names to check if module is loaded.
  htdocs/core/lib/functions.lib.php
Labels: Discussion

#26077 NEW contact type on auto add contributor
  htdocs/core/class/conf.class.php
  htdocs/public/ticket/create_ticket.php
  htdocs/ticket/class/ticket.class.php
Labels: PR to fix or conflict to solve

#27211 fix aperçu/dl fichier quand il est dans {userid}/temp
  htdocs/core/lib/files.lib.php
  htdocs/document.php
Labels: PR needs feedback

#28361 qual: phpstan for CommonObject->origin
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#28314 New method for calcule spent time in week passed
  htdocs/projet/class/project.class.php
Labels: PR to fix - Continuous Integration Test failed

#28305 Fix tva_tx on deposit invoice
  htdocs/compta/facture/card.php
Labels: PR to fix or conflict to solve

#28373 Qual: Fix/complete/refactor ModuleTest case.
  test/phpunit/CodingPhpTest.php
  test/phpunit/CommonClassTest.class.php
  test/phpunit/ModulesTest.php
Labels: Discussion

#28039 Fix show desact projects in os card using small penci
  htdocs/fourn/commande/card.php
Labels: Discussion

#27042 NEW Allow to set a default project for POS sales
  htdocs/langs/en_US/admin.lang
  htdocs/takepos/admin/terminal.php
  htdocs/takepos/invoice.php
Labels: PR to fix or conflict to solve

#28388 Qual: Refactor CodingPhpTest / CommonClassTest - less verbosity, but better when error
  test/phpunit/CodingPhpTest.php
  test/phpunit/CommonClassTest.class.php
Labels: Discussion

#28385 Qual: Review pre-commit configure - re-enable no-commit-to-branch
  .pre-commit-config.yaml
  dev/tools/codespell/codespell-lines-ignore.txt
  pyproject.toml
Labels: Discussion

#28226 Fix: Fix var_dump checker
  test/phpunit/CodingPhpTest.php
Labels: Discussion

#28428 add arrayfields in parameters for hook printFieldPreListTitle
  htdocs/adherents/list.php
Labels: Pending analysis of PR

#28470 Use the date pre-fill function also in edit mode
  htdocs/core/tpl/objectline_edit.tpl.php
Labels: PR to fix or conflict to solve

#28451 NEW Dolibarr can now re-open ticket upon customer reply on the same ticket via email#28303
  htdocs/emailcollector/class/emailcollector.class.php
  htdocs/ticket/card.php
Labels: PR to fix - Continuous Integration Test failed

#26869 php V8 Warning (empty value)
  htdocs/comm/propal/list.php
Labels: PR to fix or conflict to solve
