Repository Dolibarr/dolibarr, pull requests merged in 2024-08, with the labels that each got.

#22291 FIX : Display the real_PMP on inventory when its value is equal to 0
  htdocs/product/inventory/inventory.php
Labels: PR to fix or conflict to solve

#30331 FIX: Always re-instantiate object when doing mass PDF generation
  htdocs/core/actions_massactions.inc.php
Labels: Discussion, Bug

#30582 NEW Add caldav on fichinter
  htdocs/admin/fichinter_xcal.php
  htdocs/core/lib/fichinter.lib.php
  htdocs/public/fichinter/agendaexport.php
Labels: PR to fix or conflict to solve

#30548 NEW(ticket, admin): Add options entries
  htdocs/admin/ticket.php
  htdocs/langs/en_US/ticket.lang
Labels: PR to fix or conflict to solve

#30595 NEW translation with action triggers API
  htdocs/api/class/api_setup.class.php
Labels: PR to fix or conflict to solve

#30567 NEW more complete stock product API call
  htdocs/product/class/api_products.class.php
Labels: Discussion

#30604 Qual: Phan fixes (mainly Initial type cannot be inferred) in popular changed classes
  dev/tools/phan/baseline.txt
  htdocs/adherents/admin/member.php
  htdocs/categories/class/categorie.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/class/rejetprelevement.class.php
  htdocs/compta/prelevement/line.php
  htdocs/core/class/commondocgenerator.class.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/commonorder.class.php
  htdocs/core/class/extrafields.class.php
  htdocs/core/modules/asset/doc/pdf_standard_asset.modules.php
  htdocs/core/modules/barcode/mod_barcode_product_standard.php
  htdocs/core/modules/barcode/mod_barcode_thirdparty_standard.php
  htdocs/core/modules/barcode/modules_barcode.class.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/facture/doc/pdf_octopus.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/facture/mod_facture_mars.php
  htdocs/core/modules/facture/mod_facture_mercure.php
  htdocs/core/modules/facture/modules_facture.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/core/modules/societe/mod_codeclient_elephant.php
  htdocs/core/modules/societe/mod_codeclient_leopard.php
  htdocs/core/modules/societe/mod_codeclient_monkey.php
  htdocs/core/modules/societe/modules_societe.class.php
  htdocs/core/modules/takepos/mod_takepos_ref_universal.php
  htdocs/core/tpl/formlayoutai.tpl.php
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/fourn/class/fournisseur.product.class.php
  htdocs/fourn/facture/card-rec.php
  htdocs/modulebuilder/template/core/modules/mymodule/doc/pdf_standard_myobject.modules.php
  htdocs/product/class/api_products.class.php
  htdocs/product/class/product.class.php
  htdocs/product/stock/product.php
  htdocs/product/stock/replenish.php
  htdocs/recruitment/core/modules/recruitment/doc/pdf_standard_recruitmentjobposition.modules.php
  htdocs/societe/class/api_thirdparties.class.php
  htdocs/societe/class/societe.class.php
  htdocs/takepos/invoice.php
  htdocs/ticket/class/ticket.class.php
  htdocs/webportal/class/webportalinvoice.class.php
Labels: Discussion

#30621 Align and padding in ref column
  htdocs/core/modules/mrp/doc/pdf_vinci.modules.php
Labels: Discussion

#30638 NEW autogenerate project reference in API
  htdocs/projet/class/api_projects.class.php
Labels: PR to fix - Continuous Integration Test failed

#30444 NEW Can set the contact type for the autoassigned user that creates a project
  htdocs/langs/en_US/projects.lang
  htdocs/projet/card.php
Labels: Discussion

#30590 NEW API call to re-generate a users password.
  htdocs/user/class/api_users.class.php
Labels: PR to fix or conflict to solve

#30534 # FIX truncate mail server error message to fit to database (mailling module)
  htdocs/comm/mailing/card.php
Labels: Bug, PR to fix or conflict to solve

#30689 Fix : SQL order on extrafields type chkbxlst (multiselectarray)
  htdocs/core/class/extrafields.class.php
Labels: Bug

#30522 fix: catch error extrafields delete
  htdocs/core/class/extrafields.class.php
Labels: Pending analysis of PR (maintenance team)

#30696 fix cast
  htdocs/core/tpl/extrafields_list_print_fields.tpl.php
Labels: Discussion

#30725 LDAP fixes for php8.1+
  htdocs/core/class/ldap.class.php
  htdocs/core/login/functions_ldap.php
Labels: PR to fix or conflict to solve

#30697 Fix #30695
  htdocs/admin/system/security.php
Labels: Discussion

#30629 NEW intervention signed status update
  htdocs/core/ajax/onlineSign.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/notify.class.php
  htdocs/fichinter/card.php
  htdocs/fichinter/class/fichinter.class.php
  htdocs/fichinter/list.php
  htdocs/langs/en_US/commercial.lang
  htdocs/langs/en_US/interventions.lang
  htdocs/langs/en_US/other.lang
Labels: Discussion

#30747 Qual: Fix phan issues related to getNextValue() notices
  dev/tools/phan/baseline.txt
  htdocs/admin/pdf.php
  htdocs/comm/propal/class/propal.class.php
  htdocs/commande/class/commande.class.php
  htdocs/compta/paiement/class/paiement.class.php
  htdocs/core/lib/pdf.lib.php
  htdocs/core/modules/bom/mod_bom_advanced.php
  htdocs/core/modules/bom/mod_bom_standard.php
  htdocs/core/modules/bom/modules_bom.php
  htdocs/core/modules/facture/mod_facture_mars.php
  htdocs/core/modules/facture/mod_facture_mercure.php
  htdocs/core/modules/facture/mod_facture_terre.php
  htdocs/core/modules/facture/modules_facture.php
  htdocs/core/tpl/massactions_pre.tpl.php
  htdocs/projet/class/task.class.php
  htdocs/projet/contact.php
Labels: Discussion
