Repository Dolibarr/dolibarr, pull requests merged in 2024-04, with the labels that each got.

#29078 Update fournisseur.facture.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
Labels: Discussion, Bug

#29208 Add recurring invoice triggers in module builder template
  htdocs/modulebuilder/template/core/triggers/interface_99_modMyModule_MyModuleTriggers.class.php
Labels: PR to fix or conflict to solve

#29126 FIX: $conf must reflect enabled/disabled state of modules
  htdocs/core/modules/DolibarrModules.class.php
Labels: PR to fix - Continuous Integration Test failed

#29010 MAIN_SUPPORT_SHARED_CONTACT_BETWEEN_THIRDPARTIES error
  htdocs/core/lib/company.lib.php
  htdocs/langs/en_US/companies.lang
Labels: PR to fix - Continuous Integration Test failed

#29016 FIX Add CSV download link to stock at date table
  htdocs/product/stock/stockatdate.php
Labels: PR to fix or conflict to solve

#24992 NEW: Hooks tab in debugbar
  htdocs/core/class/hookmanager.class.php
  htdocs/debugbar/class/DataCollector/DolHooksCollector.php
  htdocs/debugbar/class/DataCollector/DolibarrCollector.php
  htdocs/debugbar/class/DebugBar.php
  htdocs/debugbar/css/widgets.css
  htdocs/debugbar/js/widgets.js
Labels: PR postponed

#29273 NEW: API setup update extrafields from name, elementtype and json
  htdocs/api/class/api_setup.class.php
  htdocs/core/class/extrafields.class.php
Labels: PR to fix or conflict to solve

#29270 NEW: API can create, get and update extrafields #29249
  htdocs/api/class/api_setup.class.php
Labels: PR to fix or conflict to solve

#29211 FIX round capital societe
  htdocs/core/class/commondocgenerator.class.php
Labels: PR to fix or conflict to solve

#29327 FIX : Scale for the "second" unit
  htdocs/install/mysql/data/llx_c_units.sql
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
Labels: PR to fix - Continuous Integration Test failed

#29303 FIX #28347 FIX #28962 FIX #29224 FIX #29035
  htdocs/fourn/commande/card.php
Labels: PR to fix or conflict to solve

#26706 NEW Accountancy - Expense report - Add an option to use end period for transfer
  htdocs/accountancy/admin/index.php
  htdocs/accountancy/journal/expensereportsjournal.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR postponed

#26959 NEW : Added a configuration in workflows
  htdocs/core/modules/modWorkflow.class.php
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
  htdocs/langs/fr_FR/workflow.lang
Labels: Discussion, PR postponed

#29344 Qual: Fix or ignore functions.lib.php phan notices
  dev/tools/phan/baseline.txt
  htdocs/core/lib/functions.lib.php
  htdocs/core/modules/syslog/logHandler.php
  htdocs/core/modules/syslog/logHandlerInterface.php
  htdocs/core/modules/syslog/mod_syslog_file.php
  htdocs/core/modules/syslog/mod_syslog_syslog.php
  htdocs/debugbar/class/DebugBar.php
  htdocs/imports/import.php
  htdocs/main.inc.php
Labels: Discussion

#29307 17.0 Backport autocomplete in dialog box
  htdocs/theme/eldy/global.inc.php
Labels: Discussion

#29271 Cleanaccount
  htdocs/compta/bank/bankentries_list.php
  htdocs/compta/bank/card.php
  htdocs/compta/bank/class/account.class.php
  htdocs/compta/bank/class/api_bankaccounts.class.php
  htdocs/compta/bank/line.php
  htdocs/compta/bank/transfer.php
  htdocs/core/lib/bank.lib.php
  htdocs/core/lib/pdf.lib.php
  htdocs/core/modules/cheque/doc/pdf_blochet.class.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/modTakePos.class.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/core/modules/stocktransfer/doc/pdf_eagle_proforma.modules.php
  htdocs/core/modules/supplier_proposal/doc/pdf_aurore.modules.php
  htdocs/societe/class/companybankaccount.class.php
  htdocs/societe/paymentmodes.php
  htdocs/user/bank.php
  htdocs/user/class/userbankaccount.class.php
Labels: Discussion

#29408 NEW Option to transfer only reconciliated lines from bank
  htdocs/accountancy/admin/index.php
  htdocs/accountancy/journal/bankjournal.php
  htdocs/core/lib/accounting.lib.php
  htdocs/langs/en_US/accountancy.lang
  htdocs/langs/en_US/banks.lang
Labels: PR to fix or conflict to solve

#29384 New Add hook show actions load fiche titre
  htdocs/core/class/html.formactions.class.php
Labels: PR to fix - Continuous Integration Test failed

#29341 Fix API GET extrafield returns 404 when not found. In general better (error) descriptions.
  htdocs/api/class/api_setup.class.php
Labels: PR to fix or conflict to solve

#29377 FIX : No decimals in result.php
  htdocs/compta/resultat/result.php
Labels: PR postponed, PR to fix or conflict to solve

#29393 Fix emailcollector ticket tracking
  htdocs/emailcollector/class/emailcollector.class.php
Labels: Discussion

#29431 fix phpstan
  ChangeLog
  dev/tools/phan/config_extended.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/admin/pdf_other.php
  htdocs/compta/facture/prelevement.php
  htdocs/compta/prelevement/create.php
  htdocs/compta/stats/cabyprodserv.php
  htdocs/core/ajax/onlineSign.php
  htdocs/core/class/commoninvoice.class.php
  htdocs/core/modules/export/export_csviso.modules.php
  htdocs/core/modules/export/export_csvutf8.modules.php
  htdocs/core/modules/export/export_excel2007.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/propale/doc/doc_generic_proposal_odt.modules.php
  htdocs/expedition/class/expedition.class.php
  htdocs/product/stats/expedition.php
  htdocs/product/stock/class/entrepot.class.php
  htdocs/public/onlinesign/newonlinesign.php
  htdocs/reception/class/receptionlinebatch.class.php
  htdocs/salaries/class/salary.class.php
  htdocs/societe/class/api_thirdparties.class.php
  htdocs/societe/class/companybankaccount.class.php
  htdocs/societe/class/societe.class.php
  htdocs/societe/paymentmodes.php
Labels: PR to fix or conflict to solve

#29462 fix: when invoice is created by WORKFLOW_ORDER_AUTOCREATE_INVOICE on ORDER_CLOSE, the invoice must have the default bank account of the thirdparty is it's empty on order
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
Labels: Discussion

#29491 NEW Update expense report card.php to allow pdf preview even without thumbnail
  htdocs/expensereport/card.php
Labels: PR to fix or conflict to solve

#29374 FIX - Search user in where propal and order
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
  htdocs/compta/facture/list.php
Labels: PR to fix or conflict to solve

#29305 NEW: Param to show main menu logo in color look and feel
  ChangeLog
  htdocs/core/lib/usergroups.lib.php
  htdocs/langs/en_US/admin.lang
  htdocs/theme/eldy/main_menu_fa_icons.inc.php
  htdocs/theme/md/main_menu_fa_icons.inc.php
Labels: Discussion

#29329 NEW add relation type on element_element
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_element_element.sql
Labels: PR to fix or conflict to solve, PR OK to merge (but suggested fix required)

#29533 FIX display massaction for bank entries list
  htdocs/compta/bank/bankentries_list.php
Labels: PR to fix or conflict to solve
