Repository Dolibarr/dolibarr, pull requests merged in 2024-11, with the labels that each got.

#24846 NEW - Add terms of sale on documents
  htdocs/admin/pdf_other.php
  htdocs/core/modules/commande/doc/pdf_einstein.modules.php
  htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php
  htdocs/core/modules/facture/doc/pdf_crabe.modules.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix - Conflict or CI error to solve

#24702 Fix:Bad holidays menus order
  htdocs/core/menus/init_menu_auguria.sql
Labels: PR to fix - See feedback in comments

#25868 FIX #25853 Thirdparty Massaction
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/fourn/facture/card.php
Labels: Discussion

#30993 fix ecmfile tooltip
  dev/translation/ignore_translation_keys.lst
  htdocs/comm/propal/class/propal.class.php
  htdocs/commande/class/commande.class.php
  htdocs/core/class/html.formfile.class.php
  htdocs/core/lib/functions.lib.php
  htdocs/ecm/class/ecmdirectory.class.php
  htdocs/ecm/class/ecmfiles.class.php
  htdocs/langs/en_US/ecm.lang
Labels: PR to fix - See feedback in comments

#30533 Fix const INVOICE_USE_RETAINED_WARRANTY
  htdocs/admin/invoice_situation.php
  htdocs/install/mysql/migration/repair.sql
Labels: PR to fix - See feedback in comments

#31676 NEW Accountancy - Add general account on thirdparty - Code user part
  htdocs/accountancy/journal/bankjournal.php
  htdocs/langs/en_US/compta.lang
  htdocs/user/bank.php
  htdocs/user/card.php
  htdocs/user/class/user.class.php
Labels: PR OK to merge

#31627 NEW VAT by state (SQL)
  htdocs/install/mysql/migration/20.0.0-21.0.0.sql
  htdocs/install/mysql/tables/llx_c_tva.key.sql
  htdocs/install/mysql/tables/llx_c_tva.sql
Labels: Discussion

#31682 fix trim null value on invoice creation
  htdocs/compta/facture/class/facture.class.php
Labels: Pending analysis of PR (maintenance team)

#31698 Develop new facture rec field societe rib management
  htdocs/compta/facture/card-rec.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/facture/prelevement.php
  htdocs/core/class/html.form.class.php
  htdocs/install/mysql/migration/20.0.0-21.0.0.sql
  htdocs/install/mysql/tables/llx_facture_rec.sql
  htdocs/langs/en_US/bills.lang
  htdocs/societe/class/societe.class.php
Labels: Discussion

#31628 NEW VAT by state
  htdocs/admin/dict.php
  htdocs/core/lib/functions.lib.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/companies.lang
Labels: PR not qualified

#25707 Update workstation_list.php
  htdocs/workstation/workstation_list.php
Labels: PR to fix - See feedback in comments

#25709 Update /datapolicy/admin/setup.php
  htdocs/datapolicy/admin/setup.php
Labels: PR to fix - Conflict or CI error to solve

#31693 Backport Fix PHP 8.2 warnings by casting trim() argument to string
  htdocs/societe/class/societe.class.php
Labels: Pending analysis of PR (maintenance team)

#31796 ODF : fix : escape specials chars in IF ELSE ENDIF $key
  htdocs/includes/odtphp/Segment.php
  htdocs/includes/odtphp/odf.php
Labels: PR to fix - See feedback in comments

#29773 NEW funclionality to Clone user with permissions and categories
  htdocs/langs/en_US/errors.lang
  htdocs/langs/en_US/users.lang
  htdocs/user/card.php
  htdocs/user/class/user.class.php
Labels: PR postponed

#29110 NEW multiselect search_sale in list societe
  htdocs/core/class/html.form.class.php
  htdocs/societe/list.php
Labels: PR to fix - See feedback in comments, PR to fix - Conflict or CI error to solve

#31805 fix phpstan
  build/phpstan/phpstan-baseline.neon
  htdocs/accountancy/bookkeeping/export.php
  htdocs/adherents/list.php
  htdocs/compta/paiement/rapport.php
  htdocs/core/modules/contract/doc/pdf_strato.modules.php
Labels: Discussion

#31234 NEW : add fichinter category - define new table
  htdocs/install/mysql/migration/20.0.0-21.0.0.sql
  htdocs/install/mysql/tables/llx_categorie_fichinter-fichinter.key.sql
  htdocs/install/mysql/tables/llx_categorie_fichinter-fichinter.sql
Labels: PR to fix - See feedback in comments

#30585 Fix Preview present even when there is no corresponding file
  htdocs/comm/card.php
Labels: Discussion

#30142 NEW Reminder Mail by Adherent Type
  htdocs/adherents/class/adherent.class.php
Labels: Feature request

#29884 NEW hook beforeRunCronJob and afterRunCronJob
  scripts/cron/cron_run_jobs.php
Labels: PR postponed, Event: DevCamp 2024 Montpellier

#29391 fix #24780 change default isolation method in dol_clone
  htdocs/core/lib/functions.lib.php
Labels: PR postponed

#29859 fix/feat: ProductLot document folder have to be the rowid
  htdocs/install/upgrade2.php
  htdocs/langs/en_US/install.lang
  htdocs/product/stock/productlot_card.php
  htdocs/product/stock/productlot_document.php
  htdocs/takepos/receipt.php
Labels: Discussion, Event: DevCamp 2024 Montpellier

#27063 make field date_start accessable for GETPOST in proposal
  htdocs/comm/propal/card.php
Labels: Discussion

#31701 NEW: use Expedition::$date_shipping property in card and list
  htdocs/expedition/card.php
  htdocs/expedition/class/expedition.class.php
  htdocs/expedition/list.php
  htdocs/langs/en_US/deliveries.lang
  htdocs/langs/en_US/sendings.lang
  htdocs/langs/fr_FR/deliveries.lang
  htdocs/langs/fr_FR/sendings.lang
Labels: PR to fix - See feedback in comments

#31755 fix calculate costs bom
  htdocs/bom/class/bom.class.php
  htdocs/core/class/cunits.class.php
Labels: Discussion

#31843 fix php warning in action class
  htdocs/comm/action/class/actioncomm.class.php
Labels: Event: Devcamp 2024 Nancy

#31852 FIX #31269 Bad use of GETPOSTINT
  htdocs/fichinter/card.php
Labels: Event: Devcamp 2024 Nancy

#31846 FIX serial number in create shipment
  htdocs/expedition/class/expeditionlinebatch.class.php
Labels: Event: Devcamp 2024 Nancy

#31845 FIX : contact type from custom module not showing
  htdocs/core/class/commonobject.class.php
Labels: Event: Devcamp 2024 Nancy

#31907 fix php warning in infobox class
  htdocs/core/class/infobox.class.php
Labels: Event: Devcamp 2024 Nancy

#31899 Tracking conf->module->enabled 2
  htdocs/comm/propal/class/propal.class.php
  htdocs/core/bookmarks_page.php
  htdocs/core/class/html.formfile.class.php
  htdocs/core/lib/contact.lib.php
  htdocs/core/lib/member.lib.php
  htdocs/core/lib/usergroups.lib.php
  htdocs/core/login/functions_ldap.php
Labels: Event: Devcamp 2024 Nancy

#31895 Tracking conf->module->enabled 1
  dev/initdemo/mysqldump_dolibarr_3.5.0.sql
  htdocs/comm/propal/class/propal.class.php
  htdocs/core/bookmarks_page.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/commande/dispatch.php
Labels: Event: Devcamp 2024 Nancy

#31891 Fix Include for Website Pages Of Library Type
  htdocs/core/lib/website.lib.php
Labels: Event: Devcamp 2024 Nancy

#31917 Fix societe price warnings
  htdocs/societe/price.php
Labels: Event: Devcamp 2024 Nancy

#31901 FIX help on PDF condition of sales
  htdocs/admin/pdf_other.php
  htdocs/langs/en_US/admin.lang
Labels: Event: Devcamp 2024 Nancy

#31893 fix warnings for tocktransfer/stocktransfer_agenda.php
  htdocs/product/stock/stocktransfer/stocktransfer_agenda.php
Labels: Event: Devcamp 2024 Nancy

#31911 fix php warning in dolGraph class
  htdocs/core/class/dolgraph.class.php
Labels: Event: Devcamp 2024 Nancy

#31913 Fix #31884 display of stars extrafields on pdf
  htdocs/core/class/commondocgenerator.class.php
Labels: Event: Devcamp 2024 Nancy

#31906 fix php warning modCaptchaStandard class
  htdocs/core/modules/security/captcha/modCaptchaStandard.class.php
Labels: Event: Devcamp 2024 Nancy

#31896 fix #27534
  htdocs/product/stock/stocktransfer/stocktransfer_list.php
Labels: Event: Devcamp 2024 Nancy

#31914 FIX issue #28222 Edit date extrafield diplayed on all on lines
  htdocs/core/class/commonobject.class.php
Labels: Event: Devcamp 2024 Nancy

#31912 Backported default ticket type fix (v18)
  htdocs/core/class/html.formticket.class.php
Labels: Event: Devcamp 2024 Nancy

#31908 Backported default ticket severity fix (v18)
  htdocs/core/class/html.formticket.class.php
Labels: Event: Devcamp 2024 Nancy

#31897 fix usf filters
  htdocs/eventorganization/conferenceorbooth_card.php
  htdocs/eventorganization/conferenceorbooth_contact.php
  htdocs/eventorganization/conferenceorbooth_document.php
  htdocs/eventorganization/conferenceorbooth_list.php
  htdocs/eventorganization/conferenceorboothattendee_card.php
  htdocs/eventorganization/conferenceorboothattendee_list.php
  htdocs/product/canvas/product/actions_card_product.class.php
  htdocs/product/canvas/service/actions_card_service.class.php
  htdocs/projet/agenda.php
  htdocs/projet/card.php
  htdocs/projet/comment.php
  htdocs/projet/contact.php
  htdocs/projet/document.php
  htdocs/projet/element.php
  htdocs/projet/ganttview.php
  htdocs/projet/messaging.php
  htdocs/projet/note.php
  htdocs/projet/tasks.php
  htdocs/projet/tasks/comment.php
  htdocs/projet/tasks/contact.php
  htdocs/projet/tasks/document.php
  htdocs/projet/tasks/note.php
  htdocs/projet/tasks/task.php
  htdocs/projet/tasks/time.php
  htdocs/societe/class/client.class.php
  htdocs/ticket/card.php
  htdocs/ticket/list.php
Labels: Event: Devcamp 2024 Nancy

#31882 Fix signature box when rounded param is set
  htdocs/core/modules/bank/doc/pdf_sepamandate.modules.php
  htdocs/core/modules/propale/doc/pdf_azur.modules.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
Labels: Event: Devcamp 2024 Nancy

#31888 FIX : Update on a sold line of bank entrie set the type to empty, now it's fixed
  htdocs/compta/bank/line.php
Labels: Event: Devcamp 2024 Nancy

#31915 FIX: Takepos: set the country of the default customer
  htdocs/core/modules/modTakePos.class.php
Labels: Event: Devcamp 2024 Nancy

#31886 fix null vaue in stocktransfer_card for sortfield and sortorder
  htdocs/product/stock/stocktransfer/stocktransfer_card.php
Labels: Event: Devcamp 2024 Nancy

#31881 FIX #29424 API GET member categories
  htdocs/adherents/class/api_members.class.php
  htdocs/categories/class/categorie.class.php
Labels: Event: Devcamp 2024 Nancy

#31885 FIX #31724
  htdocs/takepos/pay.php
Labels: Event: Devcamp 2024 Nancy

#31878 FIX mod_facture_fournisseur_tulip::getExample & get_next_value if no object
  htdocs/core/modules/supplier_invoice/mod_facture_fournisseur_tulip.php
Labels: Event: Devcamp 2024 Nancy

#31927 Fix show payment URL in massaction context when not one email per recipient
  htdocs/core/actions_massactions.inc.php
  htdocs/core/class/html.formmail.class.php
Labels: Event: Devcamp 2024 Nancy

#31872 fix php warning supplier proposal class
  htdocs/supplier_proposal/class/supplier_proposal.class.php
Labels: Event: Devcamp 2024 Nancy

#31874 FIX #31661
  htdocs/comm/propal/card.php
Labels: Event: Devcamp 2024 Nancy

#31868 fix select unit
  htdocs/product/class/html.formproduct.class.php
Labels: Event: Devcamp 2024 Nancy

#31865 fix warning for action message display
  htdocs/core/lib/functions.lib.php
Labels: Event: Devcamp 2024 Nancy

#31926 clean phpstan baseline
  build/phpstan/phpstan-baseline.neon
  htdocs/product/stats/mo.php
  htdocs/product/stock/productlot_list.php
  htdocs/product/stock/stats/commande_fournisseur.php
  htdocs/product/stock/stats/expedition.php
  htdocs/product/stock/stats/mo.php
  htdocs/product/stock/stats/reception.php
Labels: Event: Devcamp 2024 Nancy

#31909 FIX #29449 Products not allowed on contracts
  htdocs/contrat/card.php
Labels: Event: Devcamp 2024 Nancy

#31873 FIX : Default values feature is broken on units field on product create
  htdocs/product/card.php
Labels: Event: Devcamp 2024 Nancy

#31867 Fix Specimen warning in supplier admin when database has no products
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: Event: Devcamp 2024 Nancy

#31860 fix warning in html form class
  htdocs/core/class/html.form.class.php
Labels: Event: Devcamp 2024 Nancy

#31858 FIX: assets: division by zero when trying to calculate depreciation on assets that don't have it
  htdocs/asset/class/asset.class.php
Labels: Event: Devcamp 2024 Nancy

#31854 fix undefined property in expensereportline class
  htdocs/expensereport/class/expensereportline.class.php
Labels: Event: Devcamp 2024 Nancy

#31683 FIX : parent status of company in card company
  htdocs/core/lib/company.lib.php
Labels: Pending analysis of PR (maintenance team)

#31849 Update viewcat.php
  htdocs/categories/viewcat.php
Labels: Discussion, Event: Devcamp 2024 Nancy

#31922 FIX Status not correct in public ticket list
  htdocs/public/ticket/list.php
Labels: Discussion, Event: Devcamp 2024 Nancy

#31889 Fix issue n° 30845 - Resources not saved on new event creation
  htdocs/comm/action/card.php
  htdocs/public/project/new.php
  htdocs/resource/class/dolresource.class.php
Labels: PR to fix - Conflict or CI error to solve, Event: Devcamp 2024 Nancy

#31877 FIX: All contacts were loaded even if no thirdparty was selected
  htdocs/comm/action/card.php
Labels: Event: Devcamp 2024 Nancy

#31870 FIX: asset: missing ref_ext field used in CommonObject::isExistingObject()
  htdocs/asset/class/assetmodel.class.php
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_asset_model-asset.sql
Labels: Event: Devcamp 2024 Nancy

#31898 New Add a workflow to let @lvessiller-opendsi and @rycks merge 18.0 PR by accepting reviews
  .github/workflows/pr-18.yaml
Labels: Event: Devcamp 2024 Nancy

#31928 FIX send email to assigned user on ticket create
  htdocs/core/triggers/interface_50_modTicket_TicketEmail.class.php
Labels: Discussion, Event: Devcamp 2024 Nancy

#31916 FIX Takepos barcode rule with float qty
  htdocs/takepos/ajax/ajax.php
  htdocs/takepos/index.php
  htdocs/takepos/invoice.php
Labels: Discussion, Event: Devcamp 2024 Nancy

#31876 Fix #30766 Extra field Can Always Be Edited
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/extrafields.class.php
Labels: PR to fix - See feedback in comments, Event: Devcamp 2024 Nancy

#32008 FIX #32007 missing parameter on function multiSelectArrayWithCheckbox
  htdocs/projet/tasks.php
Labels: Bug

#31857 FIX TakePos barcode rule
  htdocs/takepos/ajax/ajax.php
  htdocs/takepos/index.php
Labels: Event: Devcamp 2024 Nancy

#32019 set object entity at create
  htdocs/adherents/class/adherent.class.php
  htdocs/comm/propal/class/propal.class.php
  htdocs/commande/class/commande.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/contact/class/contact.class.php
  htdocs/contrat/class/contrat.class.php
  htdocs/expedition/class/expedition.class.php
  htdocs/fichinter/class/fichinter.class.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
  htdocs/societe/class/societe.class.php
Labels: Discussion

#32028 fix: buyer and sellers in supplier invoice and supplier order list are not corectly defined
  htdocs/fourn/commande/list.php
Labels: Discussion

#32012 FIX : hook formconfirm in invoice supplier card
  htdocs/fourn/facture/card.php
Labels: PR to fix - Conflict or CI error to solve

#32118 FIX Linked elements not up to date
  htdocs/core/actions_dellink.inc.php
Labels: Discussion

#32080 fix sql ticket list
  build/phpstan/phpstan-baseline.neon
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/commande/class/commande.class.php
  htdocs/core/actions_massactions.inc.php
  htdocs/core/class/commonobject.class.php
  htdocs/expedition/class/expedition.class.php
  htdocs/projet/list.php
  htdocs/reception/class/reception.class.php
  htdocs/salaries/payments.php
  htdocs/societe/class/companybankaccount.class.php
  htdocs/societe/list.php
  htdocs/ticket/class/ticket.class.php
  htdocs/ticket/list.php
  htdocs/user/list.php
Labels: PR postponed

#32162 Fix #32145
  htdocs/ticket/card.php
Labels: Event: DevCamp 2024 Munich

#32152 FIX #31890 store empty line extrafields
  htdocs/core/class/extrafields.class.php
Labels: Event: DevCamp 2024 Munich

#32156 Fix #32155 - Error forging a SQL request on page eventorganization/conferenceorboothattendee_list.php
  htdocs/eventorganization/class/conferenceorboothattendee.class.php
Labels: Event: DevCamp 2024 Munich
