Repository Dolibarr/dolibarr, pull requests merged in 2024-12, with the labels that each got.

#32175 Fix missing linkedObjectsIds on order API
  htdocs/commande/class/api_orders.class.php
Labels: Event: DevCamp 2024 Munich

#32177 Fix #32176
  htdocs/eventorganization/conferenceorboothattendee_list.php
Labels: Event: DevCamp 2024 Munich

#32172 FIX #32171
  htdocs/fourn/facture/card.php
Labels: Event: DevCamp 2024 Munich

#32164 Update list.php
  htdocs/commande/list.php
Labels: Event: DevCamp 2024 Munich

#32165 Update list.php
  htdocs/comm/propal/list.php
Labels: Event: DevCamp 2024 Munich

#32150 FIX better error when api tempdir is not writeable
  htdocs/api/index.php
Labels: Event: DevCamp 2024 Munich

#32109 Fix handling of boolean extrafields in list filters
  htdocs/core/tpl/extrafields_list_search_input.tpl.php
  htdocs/core/tpl/extrafields_list_search_param.tpl.php
Labels: Discussion

#32173 Fix #27223 - Filter "is an answer" not working in languages other than English
  htdocs/emailcollector/class/emailcollector.class.php
Labels: Event: DevCamp 2024 Munich

#32151 Fix #29353
  htdocs/core/class/commonobject.class.php
Labels: Event: DevCamp 2024 Munich

#32159 Fix #32147
  htdocs/compta/facture/list.php
Labels: Event: DevCamp 2024 Munich

#32160 Fix #32158
  htdocs/comm/propal/card.php
Labels: PR to fix - Conflict or CI error to solve, Event: DevCamp 2024 Munich

#32170 Allow various format of dates on API paiement
  htdocs/compta/facture/class/api_invoices.class.php
Labels: Event: DevCamp 2024 Munich

#32163 Fix #32161 - Payment terms are not taken from thirdparty when proposal is created from project
  htdocs/comm/propal/card.php
Labels: PR to fix - Conflict or CI error to solve, Event: DevCamp 2024 Munich

#32190 throw RestException(500) if update of invoice fails #32134
  htdocs/compta/facture/class/api_invoices.class.php
Labels: PR to fix - See feedback in comments, Event: DevCamp 2024 Munich

#32240 NEW Enhance selectDate Function to Support Icon Customization
  htdocs/core/class/html.form.class.php
Labels: Discussion

#31048 Fix substitution variables in notification quote signed by customer
  htdocs/core/class/notify.class.php
Labels: PR to fix - See feedback in comments

#32081 fix updatelines of propal not updating object properties
  htdocs/comm/propal/card.php
  htdocs/core/class/html.formmargin.class.php
Labels: Discussion

#32087 Test: add test for AccountancySystem
  test/phpunit/AccountancySystemTest.php
  test/phpunit/AllTests.php
Labels: PR to fix - Conflict or CI error to solve

#32267 FIX(invoice): mutlicurrency_tx correct value
  htdocs/compta/facture/card.php
  htdocs/fourn/facture/card.php
Labels: PR to fix - See feedback in comments

#32194 FIX Accounting Closure Duplicates, Subledger accounts, Account Labels and more... Update bookkeeping.class.php
  htdocs/accountancy/class/bookkeeping.class.php
Labels: Discussion

#32351 FIX can not convert to reduc if draft status
  htdocs/fourn/facture/card.php
Labels: Discussion

#32382 FIX broken feature, wrong GETPOSTINT parameter
  htdocs/document.php
Labels: Discussion

#32383 Fix/130/remove dol syslog throws
  htdocs/core/lib/functions.lib.php
Labels: Discussion

#32102 FIX : Hidden dropdown download link in project
  htdocs/projet/element.php
Labels: Discussion, PR to fix - See feedback in comments

#32291 FIX: deleting a reception do not create reverse stock movements
  htdocs/reception/class/reception.class.php
Labels: Discussion

#32075 fix phpstan
  build/phpstan/phpstan-baseline.neon
  htdocs/adherents/class/adherent.class.php
  htdocs/adherents/list.php
  htdocs/adherents/messaging.php
  htdocs/adherents/subscription.php
  htdocs/adherents/subscription/list.php
Labels: Discussion

#32076 fix phpstan doc ui
  build/phpstan/phpstan-baseline.neon
  htdocs/admin/tools/ui/class/documentation.class.php
  htdocs/admin/tools/ui/components/badges.php
  htdocs/admin/tools/ui/components/buttons.php
  htdocs/admin/tools/ui/components/event-message.php
  htdocs/admin/tools/ui/components/index.php
  htdocs/admin/tools/ui/components/progress-bars.php
  htdocs/admin/tools/ui/components/test_arrays.php
  htdocs/admin/tools/ui/components/test_buttons.php
  htdocs/admin/tools/ui/components/test_forms.php
  htdocs/admin/tools/ui/content/tables.php
  htdocs/admin/tools/ui/index.php
  htdocs/core/class/doleditor.class.php
  phpstan.neon.dist
Labels: Discussion

#30915 Backport #yogosha18281
  htdocs/core/class/translate.class.php
  htdocs/core/js/lib_head.js.php
  htdocs/core/lib/functions.lib.php
Labels: Bug or PR need more information
