Repository Dolibarr/dolibarr, pull requests merged in 2024-09, with the labels that each got.

#30788 FIX contract online signature image position
  htdocs/core/ajax/onlineSign.php
Labels: Discussion, PR OK to merge

#30778 FIX - Substitution error in ticket emails in the subject
  htdocs/core/class/html.formticket.class.php
Labels: Discussion

#30694 FIX : attached file on first page load
  htdocs/core/modules/modTicket.class.php
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
  htdocs/ticket/card.php
Labels: Discussion

#30835 FIX: selection of parentholder for button dropdown
  htdocs/core/js/lib_head.js.php
Labels: Discussion

#30843 FIX : Wrong default PDF model when creating the second situation invoice
  htdocs/compta/facture/card.php
Labels: PR to fix or conflict to solve

#30841 FIX: Error message overwrited when a error occurs during update of product multilangs
  htdocs/product/class/product.class.php
Labels: Pending analysis of PR (maintenance team)

#30626 FIX avoid from re-initializing array result on nested hook getEntity
  htdocs/core/class/hookmanager.class.php
Labels: Pending analysis of PR (maintenance team)

#30877 Qual isolate ExpeditionLigne class to separate file
  htdocs/expedition/class/expedition.class.php
  htdocs/expedition/class/expeditionligne.class.php
Labels: PR to fix or conflict to solve

#30687 FIX late propal search option (v18+)
  htdocs/comm/propal/class/propal.class.php
  htdocs/comm/propal/list.php
Labels: Pending analysis of PR (maintenance team)

#30692 FIX late order search option (v18+)
  htdocs/commande/class/commande.class.php
  htdocs/commande/list.php
Labels: Pending analysis of PR (maintenance team)

#30933 FIX user experience : Extends dropdown behavior to all dropdown
  htdocs/core/js/lib_head.js.php
Labels: Discussion

#29755 NEW functionality : Clone company
  htdocs/langs/en_US/companies.lang
  htdocs/societe/card.php
Labels: PR postponed

#30332 NEW display when click on NEWS templateDrop down for model
  htdocs/core/ajax/getnews.php
  htdocs/core/ajax/mailtemplate.php
  htdocs/core/class/html.formmail.class.php
  htdocs/core/lib/website.lib.php
  htdocs/install/doctemplates/maillayout/news.html
  htdocs/theme/eldy/global.inc.php
Labels: PR to fix or conflict to solve

#30518 fix: add missing hook in propal and invoice (contact and document tabs)
  htdocs/comm/propal/contact.php
  htdocs/comm/propal/document.php
  htdocs/compta/facture/contact.php
  htdocs/compta/facture/document.php
Labels: Pending analysis of PR (maintenance team)

#30535 Retroport: FIX determine multi-currency price on object line create tpl (#28021)
  htdocs/core/class/html.form.class.php
  htdocs/core/lib/ajax.lib.php
  htdocs/core/tpl/objectline_create.tpl.php
Labels: Pending analysis of PR (maintenance team)

#31081 Qual: Fix getTooltipContentArray typing hints
  dev/tools/phan/baseline.txt
  htdocs/adherents/class/adherent.class.php
  htdocs/adherents/class/adherent_type.class.php
  htdocs/bom/class/bom.class.php
  htdocs/bookcal/class/calendar.class.php
  htdocs/categories/class/categorie.class.php
  htdocs/comm/mailing/class/mailing.class.php
  htdocs/comm/propal/class/propal.class.php
  htdocs/commande/class/commande.class.php
  htdocs/compta/bank/class/account.class.php
  htdocs/contact/class/contact.class.php
  htdocs/contrat/class/contrat.class.php
  htdocs/core/class/fiscalyear.class.php
  htdocs/core/class/timespent.class.php
  htdocs/cron/class/cronjob.class.php
  htdocs/delivery/class/delivery.class.php
  htdocs/expedition/class/expedition.class.php
  htdocs/expensereport/class/expensereport.class.php
  htdocs/fichinter/class/fichinter.class.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/holiday/class/holiday.class.php
  htdocs/knowledgemanagement/class/knowledgerecord.class.php
  htdocs/mrp/class/mo.class.php
  htdocs/opensurvey/class/opensurveysondage.class.php
  htdocs/partnership/class/partnership.class.php
  htdocs/product/stock/class/entrepot.class.php
  htdocs/product/stock/class/productlot.class.php
  htdocs/projet/class/project.class.php
  htdocs/projet/class/task.class.php
  htdocs/resource/class/dolresource.class.php
  htdocs/salaries/class/paymentsalary.class.php
  htdocs/salaries/class/salary.class.php
  htdocs/societe/class/societeaccount.class.php
  htdocs/supplier_proposal/class/supplier_proposal.class.php
  htdocs/ticket/class/ticket.class.php
  htdocs/user/class/user.class.php
  htdocs/user/class/usergroup.class.php
  htdocs/webportal/class/webportalinvoice.class.php
  htdocs/webportal/class/webportalmember.class.php
  htdocs/webportal/class/webportalorder.class.php
  htdocs/webportal/class/webportalpartnership.class.php
  htdocs/webportal/class/webportalpropal.class.php
  htdocs/workstation/class/workstation.class.php
Labels: PR to fix or conflict to solve

#30594 Backport Fix error on empty(NOLOGIN)
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
Labels: Pending analysis of PR (maintenance team)

#30948 FIX select list for contacts with very long third party names
  htdocs/core/tpl/contacts.tpl.php
Labels: Pending analysis of PR (maintenance team)

#31113 Qual: More specific ignoreErrors for phpstan
  .pre-commit-config.yaml
  dev/tools/phan/baseline.txt
  htdocs/admin/dict.php
  phpstan.neon.dist
Labels: PR to fix or conflict to solve

#31031 FIX : max product combo limit
  htdocs/product/admin/product.php
  htdocs/product/ajax/products.php
Labels: PR to fix or conflict to solve

#31138 FIX: when qty is not an integer, apply price()
  htdocs/compta/stats/cabyprodserv.php
Labels: Discussion

#31052 FIX : FATAL ERROR abusively triggered due to incomplete regex
  htdocs/core/db/DoliDB.class.php
Labels: Discussion

#31143 NEW hidden option MAIN_TE_PRIVATE_FIRST_AND_LASTNAME_TO_UPPER
  htdocs/core/class/commonpeople.class.php
Labels: PR to fix or conflict to solve

#30077 rename get_allprev_progress to getAllPrevProgress
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/compta/facture/class/factureligne.class.php
  htdocs/core/class/commoninvoice.class.php
  htdocs/core/tpl/objectline_edit.tpl.php
  htdocs/core/tpl/objectline_view.tpl.php
Labels: PR postponed

#31142 FIX : Wrong price for BOM with warkstation
  htdocs/bom/tpl/objectline_view.tpl.php
Labels: github_note

#31140 NEW #31103
  htdocs/ticket/card.php
Labels: PR to fix or conflict to solve

#30813 Add token oauth for social network
  htdocs/admin/fediverse.php
Labels: PR to fix or conflict to solve

#30855 NEW - Add an advanced permission to validate knowledge
  htdocs/core/modules/modKnowledgeManagement.class.php
  htdocs/knowledgemanagement/knowledgerecord_card.php
  htdocs/knowledgemanagement/knowledgerecord_list.php
Labels: PR to fix or conflict to solve

#30827 NEW: Add a new hook into CommonObject#commonReplaceThirdparty
  htdocs/core/class/commonobject.class.php
Labels: Code enhancement
