Repository Dolibarr/dolibarr, pull requests merged in 2024-03, with the labels that each got.

#28501 Fix return type when output is 1
  htdocs/core/class/html.formcontract.class.php
Labels: Discussion

#28499 Fix return type string instead of int
  htdocs/core/class/html.formintervention.class.php
Labels: PR to fix or conflict to solve

#28474 Fix type of variable in api_invoices
  htdocs/compta/facture/class/api_invoices.class.php
Labels: PR to fix or conflict to solve

#28496 Fix return type by adding string in select_comptes method
  htdocs/core/class/html.form.class.php
Labels: PR to fix or conflict to solve

#28471 FIX return method DeleteLine in api_boms file
  htdocs/bom/class/api_boms.class.php
Labels: PR to fix or conflict to solve

#28463 NEW : Statistic page donation
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/don/class/donstats.class.php
  htdocs/don/stats/index.php
  htdocs/langs/en_US/donations.lang
Labels: Discussion

#28601 Fix: Skip UtilsTest on windows where ls is not available
  test/phpunit/CommonClassTest.class.php
  test/phpunit/UtilsTest.php
Labels: Discussion

#28565 Fix: Script tests on Windows where PHP executable is not in path.
  test/phpunit/CommonClassTest.class.php
  test/phpunit/ScriptsTest.php
Labels: Discussion

#28646 Fix: Deposit lines are not created correctly
  htdocs/compta/facture/card.php
Labels: Discussion

#28318 NEW - See the documents of my subordinates
  htdocs/commande/list.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/lib/security.lib.php
Labels: PR to fix or conflict to solve

#28751 Fix some cases of PhanTypeSuspiciousStringExpression
  htdocs/accountancy/admin/productaccount.php
  htdocs/admin/system/xdebug.php
  htdocs/blockedlog/class/blockedlog.class.php
  htdocs/comm/action/class/actioncomm.class.php
  htdocs/comm/mailing/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/contrat/index.php
  htdocs/core/boxes/modules_boxes.php
  htdocs/core/class/menubase.class.php
  htdocs/core/menus/standard/auguria.lib.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/core/menus/standard/empty.php
  htdocs/core/modules/dons/html_cerfafr.modules.php
Labels: Discussion

#28618 FIX cloned supplier order creation date as now
  htdocs/fourn/class/fournisseur.commande.class.php
Labels: PR to fix or conflict to solve

#28750 Fix: Resolve several PhanPluginSuspiciousParamPosition cases
  dev/tools/phan/baseline.txt
  htdocs/admin/translation.php
  htdocs/comm/action/index.php
  htdocs/comm/mailing/card.php
  htdocs/comm/mailing/cibles.php
  htdocs/comm/mailing/info.php
  htdocs/compta/bank/various_payment/card.php
  htdocs/compta/bank/various_payment/document.php
  htdocs/compta/bank/various_payment/info.php
  htdocs/compta/facture/agenda-rec.php
  htdocs/compta/facture/card-rec.php
  htdocs/compta/prelevement/create.php
  htdocs/compta/sociales/document.php
  htdocs/compta/sociales/info.php
  htdocs/compta/sociales/note.php
  htdocs/compta/tva/document.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/filemanagerdol/connectors/php/connector.lib.php
  htdocs/core/modules/import/import_xlsx.modules.php
  htdocs/fourn/facture/card-rec.php
  htdocs/loan/card.php
  htdocs/loan/document.php
  htdocs/loan/info.php
  htdocs/loan/note.php
  htdocs/loan/payment/card.php
  htdocs/loan/schedule.php
  htdocs/product/card.php
Labels: PR to fix or conflict to solve

#28827 UPDATE: add a conf param to disable extrafields code autofill
  htdocs/core/tpl/admin_extrafields_add.tpl.php
Labels: PR to fix or conflict to solve

#28468 FIX column when update validation and verify date and time
  htdocs/bookcal/availabilities_card.php
  htdocs/bookcal/class/availabilities.class.php
  htdocs/langs/en_US/errors.lang
Labels: PR to fix or conflict to solve

#28874 NEW signed status CRUD to contract and fichinter
  htdocs/contrat/class/contrat.class.php
  htdocs/core/class/commonobject.class.php
  htdocs/fichinter/class/fichinter.class.php
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_contrat.sql
  htdocs/install/mysql/tables/llx_fichinter.sql
Labels: PR needs feedback

#28853 FIX variables in project class (PHPStan Warnings)
  htdocs/projet/class/project.class.php
Labels: PR to fix or conflict to solve

#28876 FIX number of properties for each object in modulebuilder
  htdocs/modulebuilder/index.php
Labels: PR OK to merge

#28831 NEW function for removing company contacts
  htdocs/core/lib/company.lib.php
  htdocs/langs/en_US/users.lang
  htdocs/societe/contact.php
Labels: PR OK to merge, PR to fix or conflict to solve

#28839 FIX PHPStan warnings
  htdocs/core/modules/member/doc/pdf_standard.class.php
Labels: PR OK to merge, PR to fix or conflict to solve

#28883 FIX problem for display content in editor
  htdocs/comm/mailing/card.php
  htdocs/core/class/html.formmail.class.php
Labels: PR OK to merge, PR to fix or conflict to solve

#28841 FIX variable by adding a type BOMLine (PHPStan warnings)
  htdocs/mrp/mo_card.php
Labels: PR OK to merge, PR to fix or conflict to solve

#28904 Fix use array instead of fileinfo
  htdocs/expensereport/tpl/expensereport_linktofile.tpl.php
Labels: Discussion

#28907 UPDATE: Doliwamp to PHP V7.4
  build/exe/doliwamp/Languages/MyCatalan.isl
  build/exe/doliwamp/Languages/MyEnglish.isl
  build/exe/doliwamp/Languages/MyFrench.isl
  build/exe/doliwamp/Languages/MyGerman.isl
  build/exe/doliwamp/Languages/MySpanish.isl
  build/exe/doliwamp/doliwamp.iss
  build/makepack-howto.txt
Labels: Discussion

#28026 QUAL fix lines' title height calculation
  htdocs/core/modules/supplier_order/doc/pdf_cornas.modules.php
Labels: PR needs feedback

#27528 [DATA_MODEL] rename commande_fournisseur_dispatch into receptiondet_batch
  htdocs/admin/receptiondet_batch_extrafields.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/lib/reception.lib.php
  htdocs/core/modules/modReception.class.php
  htdocs/expedition/dispatch.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.commande.dispatch.class.php
  htdocs/fourn/commande/dispatch.php
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_expeditiondet_batch.sql
  htdocs/install/mysql/tables/llx_receptiondet_batch.key.sql
  htdocs/install/mysql/tables/llx_receptiondet_batch.sql
  htdocs/install/mysql/tables/llx_receptiondet_batch_extrafields.key.sql
  htdocs/install/mysql/tables/llx_receptiondet_batch_extrafields.sql
  htdocs/install/pgsql/functions/functions.sql
  htdocs/install/repair.php
  htdocs/product/class/product.class.php
  htdocs/product/stock/class/productlot.class.php
  htdocs/product/stock/lib/replenishment.lib.php
  htdocs/product/stock/replenish.php
  htdocs/product/stock/stats/commande_fournisseur.php
  htdocs/product/stock/stats/reception.php
  htdocs/reception/card.php
  htdocs/reception/class/reception.class.php
  htdocs/reception/dispatch.php
Labels: PR OK to merge

#27030 Fix #27029
  htdocs/core/lib/security.lib.php
Labels: Discussion

#28890 Proposed function for records that can't be found
  htdocs/core/lib/functions.lib.php
  htdocs/societe/card.php
Labels: Discussion

#28737 Adding Hooks in bookkeeping card
  htdocs/accountancy/bookkeeping/card.php
Labels: PR to fix or conflict to solve

#28949 NEW functionality for salaries with massaction (bank-transfer)
  htdocs/salaries/class/salary.class.php
  htdocs/salaries/list.php
Labels: Discussion

#28924 Fix trailing whitespace + format code + minor spelling + enable checks
  dev/tools/phan/config.php
  dev/tools/phan/config_extended.php
  dev/tools/phan/config_fixer.php
  htdocs/public/error-401.php
  htdocs/theme/eldy/dropdown.inc.php
Labels: PR to fix or conflict to solve

#24822 NEW : TakePOS - add constant to show line subprices
  htdocs/takepos/invoice.php
Labels: PR to fix or conflict to solve

#24823 NEW : TakePOS - Option TAKEPOS_NO_GENERIC_THIRDPARTY to disallow payment if no specific thirdparty selected (generic not allowed)
  htdocs/langs/en_US/cashdesk.lang
  htdocs/langs/fr_FR/cashdesk.lang
  htdocs/takepos/index.php
Labels: PR to fix or conflict to solve

#28891 Fix & enable PhanTypeSuspiciousStringExpression
  dev/tools/phan/config.php
  dev/tools/phan/config_extended.php
  htdocs/admin/system/database.php
  htdocs/core/boxes/modules_boxes.php
  htdocs/core/class/CSMSFile.class.php
  htdocs/core/class/commonobject.class.php
  htdocs/core/class/html.formmail.class.php
  htdocs/core/class/interfaces.class.php
  htdocs/core/lib/bank.lib.php
  htdocs/core/lib/functions.lib.php
  htdocs/core/lib/modulebuilder.lib.php
  htdocs/core/lib/ws.lib.php
  htdocs/core/menus/standard/auguria.lib.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/core/menus/standard/empty.php
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
  htdocs/core/photos_resize.php
  htdocs/core/tpl/advtarget.tpl.php
  htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php
  htdocs/debugbar/class/DataCollector/DolibarrCollector.php
  htdocs/don/list.php
  htdocs/emailcollector/class/emailcollector.class.php
  htdocs/expedition/class/expedition.class.php
  htdocs/install/repair.php
  htdocs/install/step1.php
  htdocs/install/step2.php
  htdocs/install/upgrade.php
  htdocs/mrp/class/api_mos.class.php
  htdocs/mrp/mo_production.php
  htdocs/product/stock/class/mouvementstock.class.php
  htdocs/projet/class/project.class.php
  htdocs/projet/class/task.class.php
  htdocs/public/webportal/lib/webportal.lib.php
  htdocs/stripe/class/stripe.class.php
  htdocs/takepos/invoice.php
  htdocs/webservices/server_actioncomm.php
  htdocs/webservices/server_contact.php
  htdocs/webservices/server_invoice.php
  htdocs/webservices/server_order.php
  htdocs/webservices/server_thirdparty.php
  htdocs/website/class/website.class.php
Labels: Discussion

#27080 NEW : add constant TICKETS_NO_COMPANY_ON_FORM
  htdocs/core/class/html.formticket.class.php
  htdocs/ticket/class/ticket.class.php
Labels: PR postponed

#27081 FIX : correct display of html notes in lists
  htdocs/comm/propal/list.php
  htdocs/commande/list.php
Labels: PR to fix or conflict to solve

#28975 Create a shipment without documents
  htdocs/install/mysql/tables/llx_expeditiondet.sql
Labels: PR to fix or conflict to solve

#28968 Fix: Update typing for qty as float
  htdocs/bom/class/bom.class.php
Labels: PR to fix or conflict to solve

#27779 NEW: separation of expense report from salary accounting code
  htdocs/accountancy/admin/defaultaccounts.php
  htdocs/accountancy/journal/bankjournal.php
  htdocs/accountancy/journal/expensereportsjournal.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR to fix or conflict to solve

#29007 FIX : TakePOS | Add product / Delete line of existing invoice
  htdocs/takepos/index.php
Labels: Discussion

#28998 NEW preview exemple page in website when create page
  htdocs/core/class/html.formwebsite.class.php
  htdocs/langs/en_US/main.lang
  htdocs/langs/en_US/website.lang
  htdocs/website/index.php
Labels: PR OK to merge, PR to fix or conflict to solve

#28999 Fix return method deleteLine (PHPStan warnings
  htdocs/expedition/class/api_shipments.class.php
Labels: PR OK to merge, PR to fix or conflict to solve

#28767 update code and better compliance with php 8
  htdocs/core/modules/contract/doc/pdf_strato.modules.php
Labels: PR to fix or conflict to solve

#29009 Fix condition in createDictionary for modulebuilder
  htdocs/core/lib/modulebuilder.lib.php
  htdocs/modulebuilder/index.php
Labels: Discussion

#29072 FIX wrong shortcut key for macintosh
  htdocs/main.inc.php
Labels: Discussion

#29071 NEW Constant to select if typent helps define whether the thirdparty is a company
  htdocs/societe/class/societe.class.php
Labels: Discussion
