Repository Dolibarr/dolibarr, pull requests merged in 2024-05, with the labels that each got.

#29498 FIX: made invalid code shape error more user friendly
  htdocs/barcode/printsheet.php
  htdocs/langs/en_US/errors.lang
  htdocs/langs/fr_FR/errors.lang
Labels: Discussion

#29546 NEW : Add option position['find'] to DolEditor
  htdocs/core/class/doleditor.class.php
  htdocs/modulebuilder/index.php
  htdocs/modulebuilder/template/core/modules/modMyModule.class.php
Labels: Discussion

#29568 Repair function to calculate invoice total from line items
  htdocs/install/repair.php
Labels: PR to fix or conflict to solve

#29561 add column to expedition table
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_expedition.sql
Labels: PR to fix or conflict to solve

#29580 FIX: notification: error 500 in fixed emails due to a bad copy/paste
  htdocs/core/class/notify.class.php
Labels: Discussion

#29485 Prevents PHP Warnings on multicurrency_rate.php
  htdocs/multicurrency/multicurrency_rate.php
Labels: PR to fix or conflict to solve

#29590 Fix edit inline mode for the website module
  htdocs/core/ajax/editinline.php
  htdocs/website/index.php
Labels: PR to fix or conflict to solve

#29604 NEW Add option to open files in new tab
  htdocs/core/class/html.formfile.class.php
Labels: PR to fix or conflict to solve

#29616 New functionality for save 5 oldest versions of pages
  htdocs/core/lib/files.lib.php
  htdocs/core/lib/website2.lib.php
Labels: PR OK to merge, PR OK to merge (but suggested fix required)

#29473 FIX : Not qualified lines for reception
  htdocs/reception/class/reception.class.php
Labels: Discussion

#29645 NEW - Trigger for Knowledge
  htdocs/install/mysql/data/llx_c_action_trigger.sql
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/knowledgemanagement/knowledgerecord_card.php
Labels: Discussion

#29242 NEW : Add default User roles for Thirdparties
  htdocs/install/mysql/data/llx_c_type_contact.sql
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_societe_commerciaux.key.sql
  htdocs/install/mysql/tables/llx_societe_commerciaux.sql
Labels: Discussion

#29665 Add possibility to display public and private notes in expedition list
  htdocs/expedition/list.php
Labels: PR to fix or conflict to solve

#29689 init array_options in current object if we don't have record for it
  htdocs/core/class/commonobject.class.php
Labels: PR to fix - Continuous Integration Test failed

#29728 FIX: unitialised var
  htdocs/commande/card.php
Labels: Discussion

#29694 NEW Adds payment terms and procentual discount to the creation of an invoice from time entries in projects
  htdocs/projet/tasks/time.php
Labels: PR OK to merge (but suggested fix required)

#29614 New classify billed order without invoice
  ChangeLog
  htdocs/admin/invoice.php
  htdocs/admin/order.php
  htdocs/admin/supplier_order.php
  htdocs/commande/card.php
  htdocs/fourn/commande/card.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix or conflict to solve, PR OK to merge (but suggested fix required)

#29623 NEW functionality for display codebar on pdf files
  htdocs/admin/pdf_other.php
  htdocs/core/modules/expedition/doc/pdf_espadon.modules.php
  htdocs/core/modules/expedition/doc/pdf_rouget.modules.php
  htdocs/core/modules/stocktransfer/doc/pdf_eagle.modules.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix or conflict to solve

#29747 FIX :bad management right on holiday approval
  htdocs/holiday/card.php
Labels: PR OK to merge (but suggested fix required)

#29758 Update Ticket card.php Issue #29757
  htdocs/ticket/card.php
Labels: Discussion

#29348 NEW Add option to change all service dates at once
  htdocs/comm/propal/card.php
  htdocs/commande/card.php
  htdocs/compta/facture/card.php
  htdocs/core/tpl/objectline_title.tpl.php
  htdocs/fourn/commande/card.php
  htdocs/fourn/facture/card.php
Labels: PR to fix or conflict to solve

#26882 NEW Supplier Order canceled notification
  htdocs/core/class/notify.class.php
  htdocs/fourn/commande/card.php
  htdocs/langs/en_US/other.lang
Labels: PR postponed, PR to fix or conflict to solve
