Repository Dolibarr/dolibarr, pull requests merged in 2024-06, with the labels that each got.

#29790 CHANGE: add a notice in getRows() instead of returning false
  htdocs/core/db/DoliDB.class.php
Labels: Discussion

#29767 ADD : Const TAKEPOS_NO_SPLIT_SALE
  htdocs/takepos/index.php
Labels: Discussion

#29883 fix: travis CI
  htdocs/core/ajax/row.php
  htdocs/core/class/html.formsetup.class.php
Labels: DevCamp 2024 Montpellier

#29882 FIX : fix restrictedArea on selectobject for a third-party modules
  htdocs/core/ajax/selectobject.php
Labels: DevCamp 2024 Montpellier

#29879 Make more checks when creating new availabilities
  htdocs/bookcal/availabilities_card.php
  htdocs/langs/en_US/errors.lang
  htdocs/langs/fr_FR/errors.lang
Labels: DevCamp 2024 Montpellier

#29875 Add llxHeader body css for bom
  htdocs/bom/bom_agenda.php
  htdocs/bom/bom_card.php
  htdocs/bom/bom_document.php
  htdocs/bom/bom_net_needs.php
  htdocs/bom/bom_note.php
  htdocs/partnership/admin/partnership_extrafields.php
  htdocs/partnership/admin/setup.php
  htdocs/partnership/admin/website.php
  htdocs/partnership/partnership_agenda.php
  htdocs/partnership/partnership_card.php
  htdocs/partnership/partnership_contact.php
  htdocs/partnership/partnership_document.php
  htdocs/partnership/partnership_list.php
  htdocs/partnership/partnership_note.php
Labels: DevCamp 2024 Montpellier

#29889 Fix missing fichehalfleft div on productlot card
  htdocs/product/stock/productlot_card.php
Labels: DevCamp 2024 Montpellier

#29888 FIX #29887 preview translations on pictures
  htdocs/core/lib/functions.lib.php
Labels: DevCamp 2024 Montpellier

#29886 FIX date_echeance of supplier invoices not updated
  htdocs/fourn/facture/card.php
Labels: DevCamp 2024 Montpellier

#29898 fix: #29864 : do not allow more than 1 serial in mass stock transfert
  htdocs/product/stock/class/mouvementstock.class.php
  htdocs/product/stock/stocktransfer/stocktransfer_card.php
Labels: DevCamp 2024 Montpellier

#29894 New llx header body css product stats/stock
  htdocs/product/stats/bom.php
  htdocs/product/stats/card.php
  htdocs/product/stats/commande.php
  htdocs/product/stats/commande_fournisseur.php
  htdocs/product/stats/contrat.php
  htdocs/product/stats/expedition.php
  htdocs/product/stats/facture.php
  htdocs/product/stats/facture_fournisseur.php
  htdocs/product/stats/facturerec.php
  htdocs/product/stats/mo.php
  htdocs/product/stats/propal.php
  htdocs/product/stats/reception.php
  htdocs/product/stats/supplier_proposal.php
  htdocs/product/stock/card.php
  htdocs/product/stock/fiche-valo.php
  htdocs/product/stock/index.php
  htdocs/product/stock/info.php
  htdocs/product/stock/list.php
  htdocs/product/stock/massstockmove.php
  htdocs/product/stock/movement_card.php
  htdocs/product/stock/movement_list.php
  htdocs/product/stock/product.php
  htdocs/product/stock/productlot_card.php
  htdocs/product/stock/productlot_document.php
  htdocs/product/stock/productlot_list.php
  htdocs/product/stock/productlot_note.php
  htdocs/product/stock/replenish.php
  htdocs/product/stock/replenishorders.php
  htdocs/product/stock/stockatdate.php
  htdocs/product/stock/valo.php
Labels: DevCamp 2024 Montpellier

#29873 FIX : remove unuse var libelle actioncomm
  htdocs/comm/action/class/actioncomm.class.php
Labels: DevCamp 2024 Montpellier

#29880 Fix CSS class not used and deprecated in HTML 5
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/md/style.css.php
Labels: DevCamp 2024 Montpellier

#29904 Fix to avoid warning in website
  htdocs/core/lib/security.lib.php
Labels: DevCamp 2024 Montpellier

#29869 FIX Add price (and multicurrency price) in arrayfields
  htdocs/product/price_suppliers.php
Labels: DevCamp 2024 Montpellier

#29902 Fix : SQL error on stock transfer deletion
  htdocs/product/stock/stocktransfer/class/stocktransfer.class.php
Labels: DevCamp 2024 Montpellier

#29867 NEW : llxHeader body css for knowledgemanagement #27152
  htdocs/knowledgemanagement/knowledgemanagementindex.php
  htdocs/knowledgemanagement/knowledgerecord_agenda.php
  htdocs/knowledgemanagement/knowledgerecord_card.php
  htdocs/knowledgemanagement/knowledgerecord_contact.php
  htdocs/knowledgemanagement/knowledgerecord_document.php
  htdocs/knowledgemanagement/knowledgerecord_list.php
  htdocs/knowledgemanagement/knowledgerecord_note.php
Labels: DevCamp 2024 Montpellier

#29893 Fix type variable PHPStan
  htdocs/core/lib/modulebuilder.lib.php
Labels: DevCamp 2024 Montpellier

#29908 FIX Missing expense report picto in menu
  htdocs/core/menus/standard/eldy.lib.php
Labels: DevCamp 2024 Montpellier

#29906 Add clean conditions to show "create purchase order" button in sale order card
  htdocs/commande/card.php
  htdocs/core/class/commonorder.class.php
Labels: DevCamp 2024 Montpellier

#29923 fix inline images with swiftmailer
  htdocs/core/class/CMailFile.class.php
Labels: DevCamp 2024 Montpellier

#29921 FIX : create mrp table if enabled
  htdocs/core/modules/modMrp.class.php
Labels: DevCamp 2024 Montpellier

#29922 FIX: PHP 8 warning on output of successful cronjob
  htdocs/cron/class/cronjob.class.php
Labels: DevCamp 2024 Montpellier

#29919 remove deprecated handler no more needed
  htdocs/comm/action/class/actioncomm.class.php
Labels: DevCamp 2024 Montpellier

#29918 llxHeader : bodycsss product - others part
  htdocs/product/composition/card.php
  htdocs/product/dynamic_price/editor.php
  htdocs/product/inventory/card.php
  htdocs/product/inventory/inventory.php
  htdocs/product/stock/stats/commande_fournisseur.php
  htdocs/product/stock/stats/expedition.php
  htdocs/product/stock/stats/mo.php
  htdocs/product/stock/stats/reception.php
  htdocs/product/stock/stocktransfer/stocktransfer_agenda.php
  htdocs/product/stock/stocktransfer/stocktransfer_card.php
  htdocs/product/stock/stocktransfer/stocktransfer_document.php
  htdocs/product/stock/stocktransfer/stocktransfer_list.php
  htdocs/product/stock/stocktransfer/stocktransfer_note.php
Labels: DevCamp 2024 Montpellier

#29917 FIX Missing expense report picto in list
  htdocs/expensereport/list.php
Labels: DevCamp 2024 Montpellier

#29924 Add llxHeader body css for resource
  htdocs/resource/agenda.php
  htdocs/resource/card.php
  htdocs/resource/contact.php
  htdocs/resource/document.php
  htdocs/resource/element_resource.php
  htdocs/resource/list.php
  htdocs/resource/note.php
Labels: DevCamp 2024 Montpellier

#29920 Fix email colllector collection to add date in meta data description
  htdocs/emailcollector/class/emailcollector.class.php
Labels: DevCamp 2024 Montpellier

#29868 Clean expedition list code
  htdocs/expedition/list.php
Labels: DevCamp 2024 Montpellier

#29858 New user author modele fac rec
  htdocs/compta/facture/class/facture.class.php
Labels: DevCamp 2024 Montpellier

#29932 Add llxHeader to tickets
  htdocs/ticket/agenda.php
  htdocs/ticket/card.php
  htdocs/ticket/contact.php
  htdocs/ticket/document.php
  htdocs/ticket/index.php
  htdocs/ticket/list.php
  htdocs/ticket/messaging.php
  htdocs/ticket/stats/index.php
Labels: DevCamp 2024 Montpellier

#29931 Fix dol_escape_htmltag to prevent bad strip of char
  htdocs/core/lib/functions.lib.php
  test/phpunit/FunctionsLibTest.php
Labels: DevCamp 2024 Montpellier

#29928 fix phpstan Expression "'@phan-var string[] $prim%....
  htdocs/core/modules/dons/html_cerfafr.modules.php
Labels: DevCamp 2024 Montpellier

#29927 Update mails.lang fix pre-commit
  htdocs/langs/en_US/mails.lang
Labels: DevCamp 2024 Montpellier

#29926 llxHeader CSSBody - user
  htdocs/user/admin/group_extrafields.php
  htdocs/user/admin/user_extrafields.php
  htdocs/user/agenda.php
  htdocs/user/agenda_extsites.php
  htdocs/user/bank.php
  htdocs/user/card.php
  htdocs/user/clicktodial.php
  htdocs/user/document.php
  htdocs/user/group/card.php
  htdocs/user/group/ldap.php
  htdocs/user/group/list.php
  htdocs/user/group/perms.php
  htdocs/user/hierarchy.php
  htdocs/user/home.php
  htdocs/user/ldap.php
  htdocs/user/list.php
  htdocs/user/messaging.php
  htdocs/user/note.php
  htdocs/user/notify/card.php
  htdocs/user/param_ihm.php
  htdocs/user/perms.php
  htdocs/user/virtualcard.php
Labels: DevCamp 2024 Montpellier

#29929 Fix delete linked files when deleting ticket or Don
  htdocs/don/class/don.class.php
  htdocs/ticket/class/ticket.class.php
Labels: DevCamp 2024 Montpellier

#29910 fix: #29909
  htdocs/comm/propal/card.php
  htdocs/comm/propal/list.php
Labels: PR to fix or conflict to solve, DevCamp 2024 Montpellier

#29934 Allow tweaking of the index that MySQL use when searching products
  htdocs/core/class/html.form.class.php
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_product.key.sql
Labels: DevCamp 2024 Montpellier

#29899 Fix : product price by quantity was removing default price
  htdocs/product/price.php
Labels: DevCamp 2024 Montpellier

#29905 fix: Mass stock transfert display error message when something goes wrong
  htdocs/product/stock/class/mouvementstock.class.php
  htdocs/product/stock/stocktransfer/class/stocktransferline.class.php
  htdocs/product/stock/stocktransfer/stocktransfer_card.php
  htdocs/product/stock/stocktransfer/stocktransfer_list.php
Labels: Discussion, DevCamp 2024 Montpellier

#29849 Update tva for Greece
  htdocs/install/mysql/data/llx_c_tva.sql
  htdocs/install/mysql/migration/18.0.0-19.0.0.sql
Labels: Discussion, DevCamp 2024 Montpellier

#29848 Fix #29843 warning division by zero
  htdocs/compta/stats/index.php
Labels: Discussion, DevCamp 2024 Montpellier

#29953 llxHeader - BodyCss - webhook/webservice/workstation
  htdocs/webhook/target_card.php
  htdocs/webhook/target_list.php
  htdocs/webservices/admin/index.php
  htdocs/workstation/workstation_agenda.php
  htdocs/workstation/workstation_card.php
  htdocs/workstation/workstation_document.php
  htdocs/workstation/workstation_note.php
Labels: DevCamp 2024 Montpellier

#29950 llxHeader BodyCss - export part
  htdocs/exports/export.php
  htdocs/exports/index.php
Labels: DevCamp 2024 Montpellier

#29952 llxHeader BodyCss - takepos part
  htdocs/takepos/admin/appearance.php
  htdocs/takepos/admin/bar.php
  htdocs/takepos/admin/orderprinters.php
  htdocs/takepos/admin/other.php
  htdocs/takepos/admin/receipt.php
  htdocs/takepos/admin/setup.php
  htdocs/takepos/admin/terminal.php
Labels: DevCamp 2024 Montpellier

#29851 NEW : Execute doActions on statistics pages
  htdocs/comm/propal/stats/index.php
  htdocs/commande/stats/index.php
  htdocs/compta/facture/stats/index.php
Labels: DevCamp 2024 Montpellier

#29947 llxHeader CSSBody - commande
  htdocs/commande/customer.php
  htdocs/commande/index.php
  htdocs/commande/list_det.php
  htdocs/delivery/card.php
Labels: DevCamp 2024 Montpellier

#29945 llxHeader CSSBody - bookmark
  htdocs/bookmarks/admin/bookmark.php
  htdocs/bookmarks/card.php
  htdocs/bookmarks/list.php
Labels: DevCamp 2024 Montpellier

#29944 FIX : test on button and action must be the same
  htdocs/holiday/card.php
Labels: DevCamp 2024 Montpellier

#29896 Fix display of non html messages in ticket/messaging.php
  htdocs/core/lib/functions.lib.php
Labels: DevCamp 2024 Montpellier

#29994 Add llxHeader class to Accountancy customers and suppliers
  htdocs/accountancy/customer/card.php
  htdocs/accountancy/customer/index.php
  htdocs/accountancy/customer/lines.php
  htdocs/accountancy/customer/list.php
  htdocs/accountancy/index.php
  htdocs/accountancy/supplier/card.php
  htdocs/accountancy/supplier/index.php
  htdocs/accountancy/supplier/lines.php
  htdocs/accountancy/supplier/list.php
Labels: GIFF UI / UX 2024

#29855 add _multiselect on param for checkbox
  htdocs/core/tpl/extrafields_list_search_param.tpl.php
Labels: DevCamp 2024 Montpellier

#30028 Add llxHeader body css to Accountancy consultation
  htdocs/accountancy/bookkeeping/balance.php
  htdocs/accountancy/bookkeeping/card.php
  htdocs/accountancy/bookkeeping/export.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
Labels: GIFF UI / UX 2024

#30026 Add llxHeader body css to Accountancy generation + Help_url
  htdocs/accountancy/journal/bankjournal.php
  htdocs/accountancy/journal/expensereportsjournal.php
  htdocs/accountancy/journal/purchasesjournal.php
  htdocs/accountancy/journal/sellsjournal.php
  htdocs/accountancy/journal/variousjournal.php
Labels: GIFF UI / UX 2024

#30025 Add llxHeader body css to Accountancy ExpenseReport
  htdocs/accountancy/expensereport/card.php
  htdocs/accountancy/expensereport/index.php
  htdocs/accountancy/expensereport/lines.php
  htdocs/accountancy/expensereport/list.php
Labels: GIFF UI / UX 2024

#29912 Fix #29900 - Show option values when in array_options of object
  htdocs/core/tpl/extrafields_list_print_fields.tpl.php
Labels: Discussion, DevCamp 2024 Montpellier

#30061 NEW due date in accounting bookkeeping list and card
  htdocs/accountancy/bookkeeping/card.php
  htdocs/accountancy/bookkeeping/list.php
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/class/bookkeeping.class.php
Labels: PR to fix or conflict to solve

#30062 NEW : Sign propal from the web portal
  htdocs/webportal/class/html.formlistwebportal.class.php
  htdocs/webportal/class/html.formwebportal.class.php
Labels: PR to fix or conflict to solve

#30027 NEW Accountancy - Add partial reconcile on subledger
  htdocs/accountancy/bookkeeping/listbyaccount.php
  htdocs/accountancy/class/lettering.class.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR postponed

#29998 NEW filter on invoice dates in thirdparty margin tab
  htdocs/margin/tabs/thirdpartyMargins.php
Labels: PR postponed

#29997 NEW filter on invoice dates in product margin tab
  htdocs/margin/tabs/productMargins.php
Labels: PR postponed

#29970 NEW add pdf regenration to mass action for shipments
  htdocs/core/actions_massactions.inc.php
  htdocs/expedition/list.php
Labels: PR postponed

#29990 NEW : option to allow freezing qty in BOM service's line
  htdocs/bom/tpl/objectline_create.tpl.php
  htdocs/bom/tpl/objectline_edit.tpl.php
  htdocs/bom/tpl/objectline_title.tpl.php
  htdocs/bom/tpl/objectline_view.tpl.php
Labels: PR postponed

#29903 New TCPDF v6.7.5
  dev/dolibarr_changes.txt
  htdocs/core/modules/expedition/doc/pdf_espadon.modules.php
  htdocs/core/modules/hrm/doc/pdf_standard.modules.php
  htdocs/core/modules/movement/doc/pdf_standard.modules.php
  htdocs/core/modules/product/doc/pdf_standard.modules.php
  htdocs/core/modules/stock/doc/pdf_standard.modules.php
  htdocs/includes/tecnickcom/tcpdf/CHANGELOG.TXT
  htdocs/includes/tecnickcom/tcpdf/LICENSE.TXT
  htdocs/includes/tecnickcom/tcpdf/README.md
  htdocs/includes/tecnickcom/tcpdf/VERSION
  htdocs/includes/tecnickcom/tcpdf/composer.json
  htdocs/includes/tecnickcom/tcpdf/config/tcpdf_config.php
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.33/AUTHORS
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.33/BUGS
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.33/LICENSE
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.33/NEWS
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.33/README
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.33/langcover.txt
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.33/unicover.txt
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.34/AUTHORS
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.34/BUGS
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.34/LICENSE
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.34/NEWS
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.34/README
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.34/langcover.txt
  htdocs/includes/tecnickcom/tcpdf/fonts/dejavu-fonts-ttf-2.34/unicover.txt
  htdocs/includes/tecnickcom/tcpdf/fonts/freefont-20100919/CREDITS
  htdocs/includes/tecnickcom/tcpdf/fonts/freefont-20120503/CREDITS
  htdocs/includes/tecnickcom/tcpdf/include/barcodes/datamatrix.php
  htdocs/includes/tecnickcom/tcpdf/include/barcodes/pdf417.php
  htdocs/includes/tecnickcom/tcpdf/include/barcodes/qrcode.php
  htdocs/includes/tecnickcom/tcpdf/include/tcpdf_colors.php
  htdocs/includes/tecnickcom/tcpdf/include/tcpdf_filters.php
  htdocs/includes/tecnickcom/tcpdf/include/tcpdf_fonts.php
  htdocs/includes/tecnickcom/tcpdf/include/tcpdf_images.php
  htdocs/includes/tecnickcom/tcpdf/include/tcpdf_static.php
  htdocs/includes/tecnickcom/tcpdf/scripts/doctum.php
  htdocs/includes/tecnickcom/tcpdf/tcpdf.php
  htdocs/includes/tecnickcom/tcpdf/tcpdf_autoconfig.php
  htdocs/includes/tecnickcom/tcpdf/tcpdf_barcodes_1d.php
  htdocs/includes/tecnickcom/tcpdf/tcpdf_barcodes_2d.php
  htdocs/includes/tecnickcom/tcpdf/tcpdf_import.php
  htdocs/includes/tecnickcom/tcpdf/tcpdf_parser.php
Labels: PR postponed, DevCamp 2024 Montpellier

#30134 FIX #30132
  htdocs/core/class/html.formticket.class.php
Labels: Discussion

#30133 FIX #30120
  htdocs/comm/propal/card.php
Labels: Discussion

#30051 FIX rounding update price for expense report lines
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#30184 FIX: pos: invoice date incorrectly set beacause of timezome mismatches
  htdocs/takepos/invoice.php
Labels: PR not qualified

#30191 FIX force rounding mode 0 for expense report
  htdocs/core/class/commonobject.class.php
Labels: PR not sync and branch locked

#30088 NEW Add option to clone its default BOM when cloning a product
  htdocs/langs/en_US/mrp.lang
  htdocs/product/card.php
Labels: Discussion

#30081 FIX #30010 : Use conf TICKET_MESSAGE_MAIL_INTRO instead of translation key
  htdocs/ticket/class/ticket.class.php
Labels: Discussion
