Repository Dolibarr/dolibarr, pull requests merged in 2024-01, with the labels that each got.

#27252 #27249 [TPL] add: JS element target for contact line in contact tpl
  htdocs/core/tpl/contacts.tpl.php
Labels: Feature request

#27245 FIX #24185: v18: display of the merged pdf lists
  htdocs/adherents/list.php
  htdocs/admin/emailcollector_list.php
  htdocs/admin/mails_senderprofile_list.php
  htdocs/asset/list.php
  htdocs/asset/model/list.php
  htdocs/bom/bom_list.php
  htdocs/bookcal/availabilities_list.php
  htdocs/bookcal/booking_list.php
  htdocs/commande/list.php
  htdocs/compta/cashcontrol/cashcontrol_list.php
  htdocs/eventorganization/conferenceorbooth_list.php
  htdocs/eventorganization/conferenceorboothattendee_list.php
  htdocs/fichinter/list.php
  htdocs/hrm/evaluation_list.php
  htdocs/hrm/job_list.php
  htdocs/hrm/position.php
  htdocs/hrm/position_list.php
  htdocs/hrm/skill_card.php
  htdocs/hrm/skill_list.php
  htdocs/knowledgemanagement/knowledgerecord_list.php
  htdocs/modulebuilder/template/myobject_list.php
  htdocs/mrp/mo_list.php
  htdocs/opensurvey/list.php
  htdocs/partnership/partnership_list.php
  htdocs/product/inventory/list.php
  htdocs/product/stock/list.php
  htdocs/product/stock/movement_list.php
  htdocs/product/stock/productlot_list.php
  htdocs/product/stock/stocktransfer/stocktransfer_list.php
  htdocs/recruitment/recruitmentcandidature_list.php
  htdocs/recruitment/recruitmentjobposition_list.php
  htdocs/societe/website.php
  htdocs/ticket/list.php
  htdocs/variants/list.php
  htdocs/webhook/target_list.php
  htdocs/workstation/workstation_list.php
Labels: Bug, PR to fix or conflict to solve

#27269 NEW : add constant TAKEPOS_ALTERNATIVE_PAYMENT_SCREEN
  htdocs/takepos/index.php
Labels: Discussion

#27284 Use unique keys to link extrafields tables, fixes #22117 and #22467
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_actioncomm_extrafields.key.sql
  htdocs/install/mysql/tables/llx_adherent_extrafields.key.sql
  htdocs/install/mysql/tables/llx_adherent_type_extrafields.key.sql
  htdocs/install/mysql/tables/llx_bank_account_extrafields.key.sql
  htdocs/install/mysql/tables/llx_bank_extrafields.key.sql
  htdocs/install/mysql/tables/llx_bom_bom_extrafields.key.sql
  htdocs/install/mysql/tables/llx_categories_extrafields.key.sql
  htdocs/install/mysql/tables/llx_commande_extrafields.key.sql
  htdocs/install/mysql/tables/llx_commande_fournisseur_dispatch_extrafields.key.sql
  htdocs/install/mysql/tables/llx_commande_fournisseur_extrafields.key.sql
  htdocs/install/mysql/tables/llx_commande_fournisseurdet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_commandedet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_contrat_extrafields.key.sql
  htdocs/install/mysql/tables/llx_contratdet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_delivery_extrafields.key.sql
  htdocs/install/mysql/tables/llx_deliverydet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_ecm_directories_extrafields.key.sql
  htdocs/install/mysql/tables/llx_ecm_files_extrafields.key.sql
  htdocs/install/mysql/tables/llx_entrepot_extrafields.key.sql
  htdocs/install/mysql/tables/llx_eventorganization_conferenceorboothattendee_extrafields.key.sql
  htdocs/install/mysql/tables/llx_expedition_extrafields.key.sql
  htdocs/install/mysql/tables/llx_expeditiondet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_expensereport_extrafields.key.sql
  htdocs/install/mysql/tables/llx_facture_extrafields.key.sql
  htdocs/install/mysql/tables/llx_facture_fourn_det_extrafields.key.sql
  htdocs/install/mysql/tables/llx_facture_fourn_extrafields.key.sql
  htdocs/install/mysql/tables/llx_facture_fourn_rec_extrafields.key.sql
  htdocs/install/mysql/tables/llx_facture_rec_extrafields.key.sql
  htdocs/install/mysql/tables/llx_facturedet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_facturedet_rec_extrafields.key.sql
  htdocs/install/mysql/tables/llx_fichinter_extrafields.key.sql
  htdocs/install/mysql/tables/llx_fichinterdet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_holiday_extrafields.key.sql
  htdocs/install/mysql/tables/llx_hrm_evaluation_extrafields-hrm.key.sql
  htdocs/install/mysql/tables/llx_hrm_evaluationdet_extrafields-hrm.key.sql
  htdocs/install/mysql/tables/llx_hrm_job_extrafields-hrm.key.sql
  htdocs/install/mysql/tables/llx_knowledgemanagement_knowledgerecord_extrafields-knowledgemanagement.key.sql
  htdocs/install/mysql/tables/llx_mrp_mo_extrafields.key.sql
  htdocs/install/mysql/tables/llx_mrp_production_extrafields.key.sql
  htdocs/install/mysql/tables/llx_product_extrafields.key.sql
  htdocs/install/mysql/tables/llx_product_fournisseur_price_extrafields.key.sql
  htdocs/install/mysql/tables/llx_product_lot_extrafields.key.sql
  htdocs/install/mysql/tables/llx_projet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_projet_task_extrafields.key.sql
  htdocs/install/mysql/tables/llx_propal_extrafields.key.sql
  htdocs/install/mysql/tables/llx_propaldet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_reception_extrafields.key.sql
  htdocs/install/mysql/tables/llx_recruitment_recruitmentcandidature_extrafields-recruitment.key.sql
  htdocs/install/mysql/tables/llx_recruitment_recruitmentjobposition_extrafields-recruitment.key.sql
  htdocs/install/mysql/tables/llx_resource_extrafields.key.sql
  htdocs/install/mysql/tables/llx_salary_extrafields.key.sql
  htdocs/install/mysql/tables/llx_socpeople_extrafields.key.sql
  htdocs/install/mysql/tables/llx_stock_mouvement_extrafields.key.sql
  htdocs/install/mysql/tables/llx_supplier_proposal_extrafields.key.sql
  htdocs/install/mysql/tables/llx_supplier_proposaldet_extrafields.key.sql
  htdocs/install/mysql/tables/llx_user_extrafields.key.sql
  htdocs/install/mysql/tables/llx_usergroup_extrafields.key.sql
Labels: PR to fix or conflict to solve

#27200 QUAL professional identifiers - remove TODO by adding profid.lib.php
  htdocs/core/lib/profid.lib.php
  htdocs/societe/class/societe.class.php
Labels: PR postponed

#27144 NEW : llxHeader body css for command see #26856
  htdocs/commande/agenda.php
  htdocs/commande/card.php
  htdocs/commande/contact.php
  htdocs/commande/document.php
  htdocs/commande/list.php
  htdocs/commande/note.php
  htdocs/commande/stats/index.php
Labels: PR postponed

#27152 NEW : llxHeader body css for asset
  htdocs/asset/accountancy_codes.php
  htdocs/asset/agenda.php
  htdocs/asset/card.php
  htdocs/asset/depreciation.php
  htdocs/asset/depreciation_options.php
  htdocs/asset/disposal.php
  htdocs/asset/document.php
  htdocs/asset/list.php
  htdocs/asset/model/accountancy_codes.php
  htdocs/asset/model/agenda.php
  htdocs/asset/model/card.php
  htdocs/asset/model/depreciation_options.php
  htdocs/asset/model/list.php
  htdocs/asset/model/note.php
  htdocs/asset/note.php
Labels: PR postponed

#27153 NEW : llxHeader body css for donation
  htdocs/don/admin/donation.php
  htdocs/don/admin/donation_extrafields.php
  htdocs/don/card.php
  htdocs/don/document.php
  htdocs/don/index.php
  htdocs/don/info.php
  htdocs/don/list.php
  htdocs/don/note.php
  htdocs/don/payment/card.php
  htdocs/don/payment/payment.php
  htdocs/don/stats/index.php
  htdocs/langs/en_US/donations.lang
Labels: PR postponed

#27109 dont reopen billed orders
  htdocs/commande/card.php
Labels: PR to fix or conflict to solve

#27106 add noprint parameter to select_conditions_paiements
  htdocs/core/class/html.form.class.php
Labels: PR postponed

#27101 NEW add data type 'project' to blockedlog
  htdocs/blockedlog/class/blockedlog.class.php
Labels: PR postponed

#27191 QUAL extend api/status
  htdocs/api/class/api_status.class.php
Labels: PR to fix or conflict to solve

#21202 NEW : TAKEPOS-Clear search results
  htdocs/takepos/index.php
  htdocs/takepos/invoice.php
Labels: PR postponed

#27272 NEW : add hook AFTER_VAT_UPDATE
  htdocs/product/admin/product_tools.php
Labels: PR to fix or conflict to solve

#27248 25828 odt fix wrong styles
  ChangeLog
  htdocs/includes/odtphp/odf.php
Labels: Discussion

#27239 NEW: add table to store product relation with thirdparty
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_c_product_thirdparty_relation_type.sql
  htdocs/install/mysql/tables/llx_product_thirdparty.sql
Labels: PR to fix or conflict to solve

#27002 $user default value cant be int
  htdocs/product/class/productcustomerprice.class.php
Labels: PR postponed

#26589 QUAL: clean deprecated
  htdocs/compta/facture/agenda.php
  htdocs/compta/facture/card-rec.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/contact.php
  htdocs/compta/facture/document.php
  htdocs/compta/facture/note.php
  htdocs/compta/facture/prelevement.php
Labels: PR postponed

#27009 QUAL phpstan github action
  .gitattributes
  .github/workflows/phpstan.yml
  .gitignore
  build/phpstan/bootstrap_action.php
  phpstan_action.neon
  tmp/.gitkeep
Labels: PR postponed

#27373 FIX: Update mod_codeclient_* constructor to have $db argument as in callers.
  htdocs/core/modules/societe/mod_codeclient_elephant.php
  htdocs/core/modules/societe/mod_codeclient_leopard.php
  htdocs/core/modules/societe/mod_codeclient_monkey.php
  htdocs/core/modules/societe/modules_societe.class.php
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve

#27362 Correction of columns in accountancy/bookkeeping/balance.php when "Di…
  htdocs/accountancy/bookkeeping/balance.php
Labels: Discussion

#27141 fix default parameter
  htdocs/compta/paiement/cheque/class/remisecheque.class.php
Labels: PR to fix or conflict to solve

#27290 NEW allow [] in dol_eval
  htdocs/core/lib/functions.lib.php
Labels: PR to fix or conflict to solve

#27238 NEW: add column to store a label for the price
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_product.sql
  htdocs/install/mysql/tables/llx_product_customer_price.sql
  htdocs/install/mysql/tables/llx_product_customer_price_log.sql
  htdocs/install/mysql/tables/llx_product_price.sql
Labels: PR postponed, PR to fix or conflict to solve

#27083 add hooks to actions
  htdocs/comm/action/index.php
Labels: PR postponed, PR to fix or conflict to solve

#27087 remove status select from application add form
  htdocs/recruitment/class/recruitmentcandidature.class.php
Labels: PR postponed

#23478 NEW VAT - Add type
  htdocs/admin/dict.php
  htdocs/core/class/html.form.class.php
  htdocs/core/tpl/objectline_create.tpl.php
  htdocs/core/tpl/objectline_edit.tpl.php
  htdocs/expensereport/card.php
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/install/mysql/tables/llx_c_tva.sql
  htdocs/langs/en_US/admin.lang
  htdocs/product/price.php
Labels: PR to fix or conflict to solve

#27452 Qual: Ignore most shellcheck annotations, fix some
  build/debian/dolibarr.config
  build/debian/dolibarr.postinst
  build/debian/dolibarr.postrm
  build/debian/get-orig-source.sh
  build/docker/docker-run.sh
  build/patch/buildpatch.sh
  dev/initdemo/initdemo.sh
  dev/initdemo/initdemopassword.sh
  dev/initdemo/removeconfdemo.sh
  dev/initdemo/savedemo.sh
  dev/setup/git/hooks/pre-commit
  dev/tools/fixaltlanguages.sh
  dev/tools/fixdosfiles.sh
  dev/tools/fixduplicatelangkey.sh
  dev/tools/fixduplicatelanglines.sh
  dev/tools/fixhasRights.sh
  dev/tools/fixnotabfiles.sh
  dev/tools/fixperms.sh
  dev/tools/fixsnakeCaseToCamelCase.sh
  dev/tools/fixutf8bomfiles.sh
  dev/tools/github_authors_and_commits_peryear.sh
  dev/tools/github_commits_perversion.sh
  dev/tools/github_lines_perusers.sh
  dev/tools/make_sprite.sh
  dev/tools/optimize_images.sh
  dev/tools/php-cs-fixer/run-php-cs-fixer.sh
  dev/tools/resize_window.sh
  dev/translation/txpull.sh
  dev/translation/txpush.sh
  scripts/clicktodial/ekiga.sh
  scripts/clicktodial/linphone.sh
  scripts/odt2pdf/odt2pdf.sh
Labels: Discussion

#27459 feat: add hook in main.inc.php to override the manifest.json
  htdocs/main.inc.php
Labels: PR to fix or conflict to solve

#27222 New Feature: E-Mailcollector: Save attachments on operation "recordevent" for tickets
  htdocs/emailcollector/class/emailcollector.class.php
Labels: PR postponed

#27537 NEW: cronjob: deny to launch a method from a deactivated module
  htdocs/cron/class/cronjob.class.php
Labels: Discussion

#27099 add constant SUPPLIER_ORDER_MODE_OPTIONAL
  htdocs/fourn/commande/card.php
Labels: PR to fix or conflict to solve

#27544 fix phpstan
  htdocs/core/lib/date.lib.php
Labels: Discussion

#25740 NEW : hide external user in combobox
  htdocs/comm/mailing/class/html.formadvtargetemailing.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/class/html.formother.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: Discussion

#27582 QUAL Send API response data before completing post-processing tasks
  htdocs/api/index.php
Labels: Discussion

#27057 New column in website table for stock name of template imported
  htdocs/install/mysql/migration/19.0.0-20.0.0.sql
  htdocs/install/mysql/tables/llx_website-website.sql
Labels: PR to fix or conflict to solve

#27609 FIX: Fix supplier invoice security check
  htdocs/fourn/class/api_supplier_invoices.class.php
Labels: Bug

#27610 FIX: ModuleBuilder: make sure fk_object is unique on extrafields
  htdocs/modulebuilder/template/sql/llx_mymodule_myobject_extrafields.key.sql
Labels: Bug

#27612 fix: phpstan
  htdocs/compta/facture/card-rec.php
Labels: PR to fix - Continuous Integration Test failed

#27522 add function isDolTms
  htdocs/core/lib/functions.lib.php
  htdocs/projet/class/project.class.php
Labels: Discussion

#27654 qual: phpstan
  htdocs/comm/card.php
Labels: PR to fix or conflict to solve

#27659 qual: phpstan
  htdocs/compta/facture/card.php
Labels: PR to fix or conflict to solve

#27678 qual: phpstan
  htdocs/loan/class/paymentloan.class.php
  htdocs/loan/payment/payment.php
Labels: PR to fix or conflict to solve

#27700 Qual: Improve odt2pdf, add pandoc
  scripts/odt2pdf/odt2pdf.sh
Labels: Discussion

#27643 FIX avoid sql error (issue #26342)
  htdocs/compta/paiement/list.php
Labels: Discussion

#24911 NEW make sell or eat by mandatory in product lot
  htdocs/fourn/commande/dispatch.php
  htdocs/langs/en_US/productbatch.lang
  htdocs/product/ajax/product_lot.php
  htdocs/product/card.php
  htdocs/product/class/product.class.php
  htdocs/product/stock/class/productlot.class.php
  htdocs/product/stock/productlot_card.php
  htdocs/product/stock/tpl/stockcorrection.tpl.php
  htdocs/reception/class/reception.class.php
Labels: Priority - High / Blocking

#25879 NEW WebPortal module
  htdocs/core/lib/functions2.lib.php
  htdocs/public/webportal/css/global.css
  htdocs/public/webportal/css/login.css
  htdocs/public/webportal/css/mixin.css
  htdocs/public/webportal/css/pico.css
  htdocs/public/webportal/css/themes/custom.css.php
  htdocs/public/webportal/img/banner.svg
  htdocs/public/webportal/img/dolibarr_logo.svg
  htdocs/public/webportal/index.php
  htdocs/public/webportal/js/modal.js
  htdocs/public/webportal/js/theme.js
  htdocs/public/webportal/lib/webportal.lib.php
  htdocs/public/webportal/logout.php
  htdocs/public/webportal/tpl/404.tpl.php
  htdocs/public/webportal/tpl/errors.tpl.php
  htdocs/public/webportal/tpl/footer.tpl.php
  htdocs/public/webportal/tpl/header.tpl.php
  htdocs/public/webportal/tpl/header_login.tpl.php
  htdocs/public/webportal/tpl/hero-header-banner.tpl.php
  htdocs/public/webportal/tpl/home.tpl.php
  htdocs/public/webportal/tpl/login.tpl.php
  htdocs/public/webportal/tpl/menu.tpl.php
  htdocs/public/webportal/webportal.main.inc.php
  htdocs/webportal/README.md
  htdocs/webportal/admin/configcss.php
  htdocs/webportal/admin/setup.php
  htdocs/webportal/admin/setup_theme.php
  htdocs/webportal/class/context.class.php
  htdocs/webportal/class/controller.class.php
  htdocs/webportal/class/html.formcardwebportal.class.php
  htdocs/webportal/class/html.formlistwebportal.class.php
  htdocs/webportal/class/html.formwebportal.class.php
  htdocs/webportal/class/webPortalTheme.class.php
  htdocs/webportal/class/webportalinvoice.class.php
  htdocs/webportal/class/webportalmember.class.php
  htdocs/webportal/class/webportalorder.class.php
  htdocs/webportal/class/webportalpartnership.class.php
  htdocs/webportal/class/webportalpropal.class.php
  htdocs/webportal/controllers/default.controller.class.php
  htdocs/webportal/controllers/document.controller.class.php
  htdocs/webportal/controllers/invoicelist.controller.class.php
  htdocs/webportal/controllers/login.controller.class.php
  htdocs/webportal/controllers/membercard.controller.class.php
  htdocs/webportal/controllers/orderlist.controller.class.php
  htdocs/webportal/controllers/partnershipcard.controller.class.php
  htdocs/webportal/controllers/propallist.controller.class.php
  htdocs/webportal/core/modules/modWebPortal.class.php
  htdocs/webportal/langs/en_US/webportal.lang
  htdocs/webportal/lib/webportal.lib.php
  htdocs/website/websiteaccount_card.php
Labels: Priority - High / Blocking

#27817 FIX Https detection
  htdocs/filefunc.inc.php
  htdocs/main.inc.php
Labels: PR to fix or conflict to solve

#27572 NEW input in emailForm for put instructions
  htdocs/core/class/html.formmail.class.php
Labels: PR to fix or conflict to solve

#27058 New functionality for ovewrite modification in template
  htdocs/website/class/website.class.php
  htdocs/website/index.php
Labels: PR to fix or conflict to solve

#27082 ADD ticket subject on emails
  htdocs/core/class/html.formticket.class.php
  htdocs/ticket/class/ticket.class.php
Labels: Discussion

#27044 NEW : add some bank info on odt
  htdocs/core/class/commondocgenerator.class.php
Labels: PR postponed

#27039 NEW Supplier Invoice - List - Selector with choice on ECC country
  htdocs/fourn/facture/list.php
Labels: PR postponed

#27016 NEW : Payment page received from donations
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/don/paiement/list.php
  htdocs/langs/fr_FR/donations.lang
Labels: PR postponed

#27802 Qual phpstan societe class
  htdocs/societe/class/societe.class.php
Labels: PR to fix or conflict to solve

#27887 FIX : Adding hooks init
  htdocs/commande/contact.php
  htdocs/commande/document.php
Labels: PR to fix or conflict to solve
