Repository Dolibarr/dolibarr, pull requests merged in 2025-09, with the labels that each got.

#34717 FIX: Add security test for show terminal selection if no terminal selected when invoice.php is call
  htdocs/takepos/invoice.php
Labels: Discussion

#35332 add check in dolibarr phpinfo page
  htdocs/admin/system/phpinfo.php
Labels: Discussion

#35264 FIX delivery triggers and mail templates: correct inconsistencies in email triggers and templates`
  htdocs/admin/mails_templates.php
  htdocs/delivery/card.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/sendings.lang
Labels: Discussion

#35364 NEW Add mode in API of interventions to get linked objects
  htdocs/fichinter/class/api_interventions.class.php
Labels: PR to fix - See feedback in comments

#35203 NEW Add hook initialization for interventions API
  htdocs/fichinter/class/api_interventions.class.php
Labels: Discussion

#34498 Fix 34301 Project selector on supplier proposal filters incorrectly by thirdparty, ignoring global constant
  htdocs/fourn/commande/card.php
  htdocs/supplier_proposal/card.php
Labels: Discussion, Event: DevCamp 2025 Valence

#34446 QUAL replace $conf->XXX->dir_output by getMultidiroutput
  htdocs/api/class/api_documents.class.php
Labels: PR postponed, PR to fix - Conflict or CI error to solve, Event: DevCamp 2025 Valence

#35439 Fix: property api dir_temp
  htdocs/core/class/conf.class.php
Labels: Discussion

#35504 fix #35503 - Wrong format of buying price in dispatch.php / reception.php
  htdocs/fourn/commande/dispatch.php
  htdocs/reception/card.php
Labels: Event: Devcamp 2025 Vienna

#35499 Fix #35376
  htdocs/core/ajax/ajaxdirpreview.php
  htdocs/ecm/index_auto.php
Labels: Event: Devcamp 2025 Vienna

#35502 Fix #35354
  htdocs/fourn/facture/paiement.php
Labels: Event: Devcamp 2025 Vienna

#35506 Fix #35208 - Multicurrency fix for discount in invoice (Sponge)
  htdocs/core/modules/facture/doc/pdf_sponge.modules.php
Labels: Event: Devcamp 2025 Vienna

#35509 If the number of categories are smaller than the limit and the page is not 0, then we should not return anything
  htdocs/categories/class/categorie.class.php
Labels: Event: Devcamp 2025 Vienna
