Repository Dolibarr/dolibarr, pull requests merged in 2025-10, with the labels that each got.

#35531 NEW Api mass emailing
  htdocs/api/index.php
  htdocs/comm/mailing/class/api_mailings.class.php
  htdocs/comm/mailing/class/mailing.class.php
  htdocs/core/lib/functions2.lib.php
Labels: Event: Devcamp 2025 Vienna

#35293 UIUX adds a new permission that restricts the user to seeing their salaries and only those.
  htdocs/core/modules/modSalaries.class.php
  htdocs/langs/fr_FR/admin.lang
  htdocs/salaries/list.php
  htdocs/salaries/payments.php
  htdocs/salaries/stats/index.php
Labels: PR no feature/refacto into freezed/released branch

#35569 FIX #35568
  htdocs/core/actions_massactions.inc.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/class/fournisseur.facture.class.php
Labels: Discussion, Assigned to v18 maintenance Team

#34213 FIX: pgsql: error when calculating depreciations
  htdocs/asset/class/asset.class.php
Labels: Discussion

#35596 Restore the accountancy report by project to the eldy menu
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/langs/en_US/accountancy.lang
Labels: PR to fix - See feedback in comments

#35566 Use trigger prefix product also for supplier product.
  ChangeLog
  htdocs/fourn/class/fournisseur.product.class.php
Labels: Priority - High / Blocking

#35604 NEW Create simple shipment of non origin
  htdocs/expedition/class/expedition.class.php
  htdocs/expedition/class/expeditionligne.class.php
Labels: Priority - High / Blocking, PR to fix - See feedback in comments

#35469 New/Re add Custom module messaging
  htdocs/core/lib/functions.lib.php
Labels: PR to fix - See feedback in comments
