Repository Dolibarr/dolibarr, pull requests merged in 2025-02, with the labels that each got.

#32810 FIX : Mass file area rights with "objects"
  htdocs/core/lib/files.lib.php
Labels: PR not sync and branch locked

#32411 FIX select group and severity search fields on ticket list
  htdocs/core/class/html.formticket.class.php
Labels: Discussion

#32806 add an info against booking.class.php > calendar.class.php
  ChangeLog
Labels: PR to fix - Conflict or CI error to solve

#32691 TakePos Once payment is complet, a click on a product should start a new sale
  htdocs/takepos/index.php
  htdocs/takepos/pay.php
Labels: Discussion

#32886 QUAL: deleteObjectLinked() element value matching add_object_linked()
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#32616 zero could be a value
  htdocs/admin/dict.php
Labels: PR to fix - See feedback in comments

#33006 FIX: Correct HTML escaping function
  htdocs/core/lib/functions.lib.php
Labels: Discussion

#33024 FIX display full tree on shipment card when a kit contains a same component in other sub-kit
  htdocs/product/class/product.class.php
Labels: Reserved tag for devcamp preparation

#31963 NEW: vcard (vcf) download for third party (#31957)
  htdocs/societe/card.php
  htdocs/societe/contact.php
  htdocs/societe/vcard.php
Labels: PR postponed

#31953 feat: add entity in custom translation with multicompany
  htdocs/admin/translation.php
Labels: PR postponed

#31904 FIX go back status #24944
  htdocs/don/card.php
  htdocs/don/class/don.class.php
Labels: PR to fix - Conflict or CI error to solve, Event: Devcamp 2024 Nancy

#26693 Adherent type class refactoring
  htdocs/adherents/class/adherent_type.class.php
  htdocs/adherents/type.php
Labels: PR postponed, PR to fix - See feedback in comments, Event: DevCamp 2023 Lyon

#22849 NEW Add order tags
  htdocs/categories/class/api_categories.class.php
  htdocs/categories/class/categorie.class.php
  htdocs/categories/viewcat.php
  htdocs/commande/card.php
  htdocs/commande/class/commande.class.php
  htdocs/core/class/html.form.class.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/core/modules/modCategorie.class.php
  htdocs/langs/en_US/categories.lang
Labels: PR to fix - Conflict or CI error to solve

#33129 New add new setup in ai setup
  htdocs/ai/admin/custom_prompt.php
  htdocs/ai/admin/setup.php
  htdocs/ai/class/ai.class.php
  htdocs/ai/lib/ai.lib.php
  htdocs/langs/en_US/admin.lang
Labels: PR to fix - See feedback in comments

#33146 FIX #33145 wrong label status buy on product tooltip
  htdocs/core/class/commonobject.class.php
Labels: Discussion

#33162 Fix #33160 dol_check_secure_access_document bad value for productlot
  htdocs/core/lib/files.lib.php
Labels: Bug

#33091 FIX #33090 Is in sepa
  htdocs/compta/bank/card.php
  htdocs/compta/prelevement/class/bonprelevement.class.php
  htdocs/compta/prelevement/create.php
  htdocs/core/lib/company.lib.php
  htdocs/societe/class/societe.class.php
Labels: PR postponed

#32976 NEW: add const to not include default lib_head.js in top_htmlhead with DISABLE_LIB_HEAD_JS
  htdocs/main.inc.php
Labels: Discussion

#31829 New status for webhook Target
  htdocs/core/triggers/interface_95_modWebhook_WebhookTriggers.class.php
  htdocs/fourn/class/fournisseur.commande.class.php
  htdocs/fourn/commande/card.php
  htdocs/install/mysql/migration/20.0.0-21.0.0.sql
  htdocs/install/mysql/tables/llx_webhook_target-webhook.sql
  htdocs/langs/en_US/admin.lang
  htdocs/langs/en_US/main.lang
  htdocs/webhook/class/target.class.php
  htdocs/webhook/target_card.php
Labels: PR postponed

#32456 Fix email collector datetimelast ok and email fetching
  htdocs/emailcollector/class/emailcollector.class.php
Labels: Discussion

#31960 NEW: Add also start date fill buttons for salary clone
  htdocs/langs/en_US/salaries.lang
  htdocs/salaries/card.php
Labels: PR OK to merge, PR postponed

#33223 NEW: Add management of date begin/end and discount for a customer price (SQL)
  htdocs/install/mysql/migration/21.0.0-22.0.0.sql
  htdocs/install/mysql/tables/llx_product_customer_price.key.sql
  htdocs/install/mysql/tables/llx_product_customer_price.sql
  htdocs/install/mysql/tables/llx_product_customer_price_log.sql
Labels: Discussion

#33141 QUAL setup disable stock calculate on rules
  htdocs/admin/stock.php
Labels: Discussion
