Repository Dolibarr/dolibarr, pull requests merged in 2025-03, with the labels that each got.

#33229 FIX(ticket): Notification email without public interface
  htdocs/core/triggers/interface_50_modTicket_TicketEmail.class.php
  htdocs/langs/en_US/ticket.lang
  htdocs/langs/fr_FR/ticket.lang
Labels: Discussion

#30244 NEW : use specific landing page to home menu entry
  htdocs/core/menus/standard/eldy.lib.php
Labels: PR to fix - See feedback in comments

#33265 Fix Excel Export of zero values
  htdocs/core/modules/export/export_excel2007.modules.php
Labels: Discussion

#33250 NEW Add invoice tags
  htdocs/categories/class/categorie.class.php
  htdocs/categories/viewcat.php
  htdocs/compta/facture/card.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/core/menus/standard/eldy.lib.php
  htdocs/core/modules/modCategorie.class.php
  htdocs/langs/en_US/categories.lang
Labels: PR OK to merge

#33299 Fix dolGetButtonAction Tooltip
  htdocs/core/lib/functions.lib.php
Labels: Discussion

#33351 FIX : Count on supplier invoice list not correct
  htdocs/fourn/facture/list.php
Labels: Discussion

#32552 FIX|Fix # Update TimeSpent Issue
  htdocs/projet/tasks/time.php
Labels: Discussion

#33393 fix: thirdparty substitutions var ignored on automatic event
  htdocs/core/class/notify.class.php
Labels: PR to fix - See feedback in comments

#33384 NEW Accountancy - Add centralized account (SQL & migration part)
  htdocs/install/mysql/data/llx_accounting_account_fr.sql
  htdocs/install/mysql/migration/21.0.0-22.0.0.sql
  htdocs/install/mysql/tables/llx_accounting_account.sql
Labels: PR OK to merge

#33390 FIX : PAIEMENT Wrong field displayed for DateChequeReceived
  htdocs/compta/paiement/cheque/card.php
Labels: Discussion

#33252 feat(invoice-rec): new rule_for_lines_dates field - Impl
  htdocs/compta/facture/card-rec.php
  htdocs/compta/facture/class/facture-rec.class.php
  htdocs/compta/facture/class/facture.class.php
  htdocs/core/class/html.form.class.php
  htdocs/langs/en_US/compta.lang
Labels: PR to fix - See feedback in comments

#33373 NEW On list, see complete ref customer/supplier with constant MAIN_SHOW_GLOBAL_REF_CUSTOMER_SUPPLIER
  htdocs/compta/facture/list.php
Labels: Discussion

#26519 NEW shipment kits with dispatcher v2 (SQL)
  htdocs/install/mysql/migration/21.0.0-22.0.0.sql
  htdocs/install/mysql/tables/llx_expeditiondet.key.sql
  htdocs/install/mysql/tables/llx_expeditiondet.sql
Labels: Pending analysis of PR

#33543 NEW #33506 Add a constant to apply a ratio to resize images in ODT templates
  htdocs/core/modules/asset/doc/doc_generic_asset_odt.modules.php
  htdocs/core/modules/bom/doc/doc_generic_bom_odt.modules.php
  htdocs/core/modules/commande/doc/doc_generic_order_odt.modules.php
  htdocs/core/modules/contract/doc/doc_generic_contract_odt.modules.php
  htdocs/core/modules/expedition/doc/doc_generic_shipment_odt.modules.php
  htdocs/core/modules/facture/doc/doc_generic_invoice_odt.modules.php
  htdocs/core/modules/member/doc/doc_generic_member_odt.class.php
  htdocs/core/modules/mrp/doc/doc_generic_mo_odt.modules.php
  htdocs/core/modules/product/doc/doc_generic_product_odt.modules.php
  htdocs/core/modules/project/doc/doc_generic_project_odt.modules.php
  htdocs/core/modules/project/task/doc/doc_generic_task_odt.modules.php
  htdocs/core/modules/propale/doc/doc_generic_proposal_odt.modules.php
  htdocs/core/modules/reception/doc/doc_generic_reception_odt.modules.php
  htdocs/core/modules/societe/doc/doc_generic_odt.modules.php
  htdocs/core/modules/stock/doc/doc_generic_stock_odt.modules.php
  htdocs/core/modules/supplier_invoice/doc/doc_generic_supplier_invoice_odt.modules.php
  htdocs/core/modules/supplier_order/doc/doc_generic_supplier_order_odt.modules.php
  htdocs/core/modules/supplier_proposal/doc/doc_generic_supplier_proposal_odt.modules.php
  htdocs/core/modules/ticket/doc/doc_generic_ticket_odt.modules.php
  htdocs/core/modules/user/doc/doc_generic_user_odt.modules.php
  htdocs/core/modules/usergroup/doc/doc_generic_usergroup_odt.modules.php
  htdocs/includes/odtphp/Segment.php
  htdocs/includes/odtphp/odf.php
  htdocs/modulebuilder/template/core/modules/mymodule/doc/doc_generic_myobject_odt.modules.php
  htdocs/recruitment/core/modules/recruitment/doc/doc_generic_recruitmentjobposition_odt.modules.php
Labels: PR to fix - See feedback in comments

#33509 FIX: products with a single price by qty may have empty price when adding it in a commercial piece
  htdocs/core/lib/ajax.lib.php
Labels: Discussion

#33580 New js search filter in icons doc
  htdocs/admin/tools/ui/class/documentation.class.php
  htdocs/admin/tools/ui/components/badges.php
  htdocs/admin/tools/ui/components/event-message.php
  htdocs/admin/tools/ui/components/icons.php
  htdocs/admin/tools/ui/components/inputs.php
  htdocs/admin/tools/ui/css/doc-icons.css
  htdocs/bookmarks/bookmarks.lib.php
  htdocs/core/class/html.form.class.php
  htdocs/core/js/lib_foot.js.php
  htdocs/core/js/lib_foot_search_tool.js
  htdocs/langs/en_US/uxdocumentation.lang
  htdocs/theme/eldy/dropdown.inc.php
  htdocs/theme/eldy/global.inc.php
  htdocs/theme/eldy/search-input.inc.css
  htdocs/theme/md/dropdown.inc.php
  htdocs/theme/md/search-input.inc.css
  htdocs/theme/md/style.css.php
Labels: Feature request, PR to fix - Conflict or CI error to solve

#32750 NEW(mailing): Allow user to define the number of email sent by batch directly from mailing config page
  htdocs/admin/mailing.php
  htdocs/install/mysql/data/llx_const.sql
  htdocs/install/mysql/migration/21.0.0-22.0.0.sql
  htdocs/langs/en_US/mails.lang
Labels: Discussion

#33607 FIX|Fix # fatal trying update desc invoice situation
  htdocs/compta/facture/card.php
Labels: PR not sync and branch locked, Reserved tag for devcamp preparation
