Repository Dolibarr/dolibarr, pull requests merged in 2025-07, with the labels that each got.

#34511 fix: bad date management on update in time spent list if column is not displayed
  htdocs/projet/tasks/time.php
Labels: Discussion, Event: DevCamp 2025 Valence

#34663 UX Repair install script
  htdocs/install/repair.php
Labels: PR postponed

#34729 NEW Accountancy - Accounting by payment type
  htdocs/accountancy/journal/bankjournal.php
  htdocs/admin/dict.php
Labels: PR postponed

#34634 NEW Add thirdparty search on api list
  htdocs/comm/propal/class/api_proposals.class.php
  htdocs/commande/class/api_orders.class.php
  htdocs/compta/facture/class/api_invoices.class.php
  htdocs/contrat/class/api_contracts.class.php
  htdocs/expedition/class/api_shipments.class.php
  htdocs/fichinter/class/api_interventions.class.php
  htdocs/projet/class/api_projects.class.php
  htdocs/ticket/class/api_tickets.class.php
Labels: PR postponed

#34723 Fix(core): Ensure tms field is always updated in updateCommon
  htdocs/core/class/commonobject.class.php
Labels: PR to fix - See feedback in comments

#34760 Correction for the generation of the bankjournal for a paiement for different third parties
  htdocs/accountancy/journal/bankjournal.php
Labels: PR to fix - See feedback in comments

#34563 NEW : search all facture rec
  htdocs/compta/facture/invoicetemplate_list.php
  htdocs/core/ajax/selectsearchbox.php
  htdocs/langs/en_US/main.lang
Labels: PR postponed

#34537 NEW Can force_install_dolibarrpassword for automatic installation
  htdocs/install/install.forced.docker.php
  htdocs/install/install.forced.sample.php
  htdocs/install/step4.php
Labels: PR postponed

#34422 QUAL: OpenID Setup fused in Security Setup + Module removed -- WIP
  htdocs/admin/openid_connect.php
  htdocs/core/lib/admin.lib.php
  htdocs/core/lib/openid_connect.lib.php
  htdocs/core/modules/modOpenIDConnect.class.php
  htdocs/langs/en_US/admin.lang
  htdocs/langs/fr_FR/admin.lang
Labels: PR postponed, Event: DevCamp 2025 Valence

#34671 New: SQL for api rest tokens
  htdocs/install/upgrade2.php
  htdocs/langs/en_US/install.lang
Labels: PR to fix - See feedback in comments

#34649 NEW Withholdingtax how VatRefund
  htdocs/compta/facture/card.php
  htdocs/compta/tva/class/tva.class.php
Labels: PR to fix - See feedback in comments

#34803 UIUX - Add links to home info-box
  htdocs/index.php
  htdocs/theme/eldy/info-box.inc.php
  htdocs/theme/md/info-box.inc.php
Labels: Event: GIFF UI / UX 2024
