Repository Dolibarr/dolibarr, pull requests merged in 2025-08, with the labels that each got.

#34441 NEW add shipping address to propal
  htdocs/admin/pdf_other.php
  htdocs/core/modules/propale/doc/pdf_cyan.modules.php
  htdocs/langs/en_US/propal.lang
  htdocs/langs/fr_FR/propal.lang
Labels: PR postponed, Event: DevCamp 2025 Valence

#34377 QUAL: stop supporting old tab entries
  htdocs/core/lib/functions.lib.php
Labels: PR postponed

#34250 FIX: SQL query too heavy
  htdocs/install/mysql/migration/17.0.0-18.0.0.sql
  htdocs/install/mysql/tables/llx_user.key.sql
Labels: Discussion

#34725 FIX: asset: could not select invoice in disposal pop-in
  htdocs/asset/card.php
Labels: Pending analysis of PR (maintenance team)

#34897 FIX #34893
  htdocs/user/passwordforgotten.php
Labels: Discussion

#34612 Modifications made to allow search by EAN even when selecting in the product variants module to hide product variants #34567
  htdocs/core/class/html.form.class.php
Labels: PR to fix - See feedback in comments

#34520 NEW Display company logo on kanban view
  htdocs/societe/class/societe.class.php
Labels: PR to fix - Conflict or CI error to solve, Event: DevCamp 2025 Valence

#25635 NEW We added a hook to allow us to modify the Prospect Customer drop down…
  htdocs/societe/card.php
  htdocs/societe/list.php
Labels: PR to fix - See feedback in comments

#34929 FIX mailing destination list title
  htdocs/comm/mailing/cibles.php
Labels: Discussion

#35041 FIX set global mysoc and load langs in API access
  htdocs/api/class/api_access.class.php
Labels: Discussion
